let en = {
  translations: {
    Crafting: "Crafting",
    Clan: "Clan",
    Profile: "Profile",
    "Clan List": "Clan List",
    Members: "Members",
    "Walker List": "Walker List",
    "Resources maps": "Resources maps",
    Diplomacy: "Diplomacy",
    Trades: "Trades",
    "Auctions Timers": "Auctions Timers",
    "Other info": "Other info",
    "Github project": "Github project",
    "This website are utilities related to the game Last Oasis but is not affiliated with":
      "This website are utilities related to the game Last Oasis but is not affiliated with",
    "This website uses cookies to enhance the user experience.":
      "This website uses cookies to enhance the user experience.",
    "Login with discord": "Login with discord",
    Crafter: "Crafter",
    "Here you can see the materials needed to build each thing you need and with the amount you need as if it were a shopping list. It is in English and Spanish":
      "Here you can see the materials needed to build each thing you need and with the amount you need as if it were a shopping list. It is in English and Spanish",
    "See how much time is left to finish the auctions of the maps you want easily":
      "See how much time is left to finish the auctions of the maps you want easily",
    "Trading system": "Trading system",
    "You can create offers or search for them easily from here, you don't need to be on 20 discord servers looking for who to exchange with":
      "You can create offers or search for them easily from here, you don't need to be on 20 discord servers looking for who to exchange with",
    "Check when your walkers were last used and who used them in a simple and quick way. I have created a discord bot that apart from giving other functions allows you to control the walkers log in an easier way":
      "Check when your walkers were last used and who used them in a simple and quick way. I have created a discord bot that apart from giving other functions allows you to control the walkers log in an easier way",
    "Control the clan": "Control the clan",
    "Use this section to control your clan, make alliances or send wars and to easily show it to your clan members.":
      "Use this section to control your clan, make alliances or send wars and to easily show it to your clan members.",
    "Your details": "Your details",
    "Discord Tag": "Discord Tag",
    "Nick in Game": "Nick in Game",
    "Not defined": "Not defined",
    "No Clan": "No Clan",
    "Delete user": "Delete user",
    "Are you sure?": "Are you sure?",
    "This option is not reversible, your user and all his data will be deleted.":
      "This option is not reversible, your user and all his data will be deleted.",
    Cancel: "Cancel",
    "Add name in the game": "Add name in the game",
    "Your name in Last Oasis": "Your name in Last Oasis",
    Add: "Add",
    "Join a clan": "Join a clan",
    "Clan Name": "Clan Name",
    "Flag Color": "Flag Color",
    "(Optional)": "(Optional)",
    "Create a clan": "Create a clan",
    "Manage Clan": "Manage Clan",
    "Leave clan": "Leave clan",
    "Error when connecting to the API": "Error when connecting to the API",
    "This user cannot be found": "This user cannot be found",
    "You do not have permission to access this page":
      "You do not have permission to access this page",
    "Change language": "Change language",
    Spanish: "Spanish",
    English: "English",
    "Member List": "Member List",
    Kick: "Kick",
    "List of requests": "List of requests",
    Accept: "Accept",
    Reject: "Reject",
    "There are no pending requests": "There are no pending requests",
    "Loading the list of requests to enter the clan":
      "Loading the list of requests to enter the clan",
    "Transfer Clan": "Transfer Clan",
    "This option is not reversible, so be careful who you pass it on to in the leadership of the clan":
      "This option is not reversible, so be careful who you pass it on to in the leadership of the clan",
    "New leader:": "New leader:",
    "Change leader": "Change leader",
    Delete: "Delete",
    "Delete Clan": "Delete Clan",
    "By deleting the clan you will delete all the data linked to it, be careful because this option is not reversible":
      "By deleting the clan you will delete all the data linked to it, be careful because this option is not reversible",
    Menu: "Menu",
    "Total materials": "Total materials",
    "List of all necessary materials by": "List of all necessary materials by",
    "Download Totals": "Download Totals",
    "Application to enter the clan sent": "Application to enter the clan sent",
    Leader: "Leader",
    "Discord Invite Link": "Discord Invite Link",
    Actions: "Actions",
    "Send request": "Send request",
    "Walker ID": "Walker ID",
    "You don't have access here, try to log in again":
      "You don't have access here, try to log in again",
    "Error when kicking a member": "Error when kicking a member",
    "Error when add member": "Error when add member",
    "Error when reject member": "Error when reject member",
    "Clan deleted correctly": "Clan deleted correctly",
    "Error when delete clan": "Error when delete clan",
    "Error when change owner of clan": "Error when change owner of clan",
    Search: "Search",
    Clean: "Clean",
    Owner: "Owner",
    "Last User": "Last User",
    "Last Use": "Last Use",
    "You need to have a clan to access this section":
      "You need to have a clan to access this section",
    "For the walkers to appear it is necessary to link the discord server with the clan, only users with administration power can add the discord server.":
      "For the walkers to appear it is necessary to link the discord server with the clan, only users with administration power can add the discord server.",
    "Discord ID": "Discord ID",
    "Link discord server": "Link discord server",
    "Discord Bot": "Discord Bot",
    "You need to add the bot to your discord to compile the list of walkers from the log, but it also has other functions like checking what you need to do the different items":
      "You need to add the bot to your discord to compile the list of walkers from the log, but it also has other functions like checking what you need to do the different items",
    "Map List": "Map List",
    "Map Name": "Map Name",
    "New Map": "New Map",
    "Date of burning": "Date of burning",
    "Map Type": "Map Type",
    "Create new map": "Create new map",
    "Back to the list of maps": "Back to the list of maps",
    Type: "Type",
    Coordinate: "Coordinate",
    "Not the same as in the game": "Not the same as in the game",
    "Quality:": "Quality:",
    "Create resource": "Create resource",
    "Login again": "Login again",
    "Temporal Marker": "Temporal Marker",
    "Published Trades": "Published Trades",
    Supply: "Supply",
    Demand: "Demand",
    Resource: "Resource",
    Region: "Region",
    "Filter trades": "Filter trades",
    "Clean filter": "Clean filter",
    "If you want to publish your own exchange offers you have to be connected":
      "If you want to publish your own exchange offers you have to be connected",
    "Publish an trade": "Publish an trade",
    Quantity: "Quantity",
    Publish: "Publish",
    "No trade offers were found with this filter":
      "No trade offers were found with this filter",
    Allies: "Allies",
    "NAP or Settlers": "NAP or Settlers",
    War: "War",
    "Create a relationship": "Create a relationship",
    "This data is not saved, if you reload the page it will be deleted":
      "This data is not saved, if you reload the page it will be deleted",
    "Sound Off": "Sound Off",
    "Sound On": "Sound On",
    "Show map": "Show map",
    "Delete map": "Delete map",
    "Share map": "Share map",
    Hours: "Hours",
    "Try again later": "Try again later",
    Minutes: "Minutes",
    Seconds: "Seconds",
    Description: "Description",
    Start: "Start",
    Stop: "Stop",
    "Latest updates": "Latest updates",
    "Report Bugs": "Report Bugs",
    "I'd appreciate it if you find a bug and tell me about it on Github or another platform so that I can fix it":
      "I'd appreciate it if you find a bug and tell me about it on Github or another platform so that I can fix it",
    Report: "Report",
    "I have also created a discord bot useful to control the walkers and make a list of what is needed to create objects.":
      "I have also created a discord bot useful to control the walkers and make a list of what is needed to create objects.",
    "Go to Discord bot": "Go to Discord bot",
    "Dm94Dani´s Discord": "Dm94Dani´s Discord",
    "Steam Page": "Steam Page",
    "Official Discord": "Official Discord",
    Wiki: "Wiki",
    "Aloe vera": "Aloe",
    "Grasa animal": "Animal Fat",
    Manzana: "Apple",
    Ceniza: "Ash",
    "Cera de abejas": "Beeswax",
    "Nabo sangriento": "Blood Turnip",
    "Adhesivo de hueso": "Bone Glue",
    "Astilla de hueso": "Bone Splinter",
    "Carne de cactus": "Cactus Flesh",
    Enea: "Cattail",
    "Esquirla de cerámica": "Ceramic Shard",
    Carbón: "Charcoal",
    "Escama de quitina": "Chitin Plate",
    Arcilla: "Clay",
    "Agua contaminada": "Contaminated Water",
    Maiz: "Corn",
    Algodón: "Cotton",
    Ceresina: "Earth Wax",
    Pluma: "Feather",
    Fibra: "Fiber",
    "Tejido de Fibra": "Fiber Weave",
    Fragmento: "Fragment",
    "Vial de cristal": "Glass",
    Esconderse: "Hide",
    "Fruto de cactus enorme": "Huge Cactus Fruit",
    Insectos: "Insects",
    "Lingote de hierro": "Iron Ingot",
    "Material de hierro": "Iron Ore",
    Lava: "Lava",
    "Combustible líquido": "Liquid Fuel",
    "Carne de champiñon": "Mushroom Flesh",
    "Mineral de Nibiru": "Nibiran Mineral",
    "Tela Nomad": "Nomad Cloth",
    Obsidiana: "Obsidian",
    "Hojas de palmera": "Palm Leaves",
    Perla: "Pearl",
    "Agua Purificada": "Purified Water",
    "Platano rojo": "Red Banana",
    "Madera de secuoya roja": "Redwood Wood",
    "Reforzar tablón": "Reinforced Plank",
    Cuerda: "Rope",
    "Mantequilla de la tribu rupu": "Rupu Gel",
    "Piel rupu": "Rupu Pelt",
    "Vid Rupu": "Rupu Vine",
    "Roca de sal": "Salt Rock",
    Arena: "Sand",
    "Fragmentos hechos añicos": "Shattered Fragment",
    Piedra: "Stone",
    Azufre: "Sulfur",
    Placa: "Tablet",
    Brea: "Tar",
    Baya: "Thornberry",
    Torque: "Torque",
    Madera: "Wood",
    "Poste de Madera": "Wood Shaft",
    "Escama de gusano": "Worn Scale",
    "Seda de gusano": "Worn Silk",
  },
};

export default en;
