let all = {
    translations: {
        'New web update': 'Nueva actualización de la web',
        Update: 'Actualizar',
        Crafting: 'Crafteo',
        Clan: 'Clan',
        'User Profile': 'Perfil',
        'Clan List': 'Listado de clanes',
        Members: 'Miembros',
        'Walker List': 'Listado de walkers',
        'Resource Maps': 'Mapas de recursos',
        Diplomacy: 'Diplomacia',
        Trades: 'Intercambios',
        'Auction Timers': 'Temporizadores de subastas',
        About: 'Otra info',
        'Github project': 'Proyecto en GitHub',
        'Light Theme Mode': 'Tema claro',
        Profile: 'Perfil',
        'Members List': 'Lista de miembros',
        Crafter: 'Crafter',
        'Tech Tree': 'Árbol tecnológico',
        'Quality Calculator': 'Quality Calculator',
        'Walkers Upgrades Cost': 'Costes de actualizaciones de los walkers',
        'Help to translate the website': 'Ayuda a traducir la web',
        'This website uses utilities related to the game \'Last Oasis\' but is not affiliated with': 'Este sitio web son utilidades relacionadas con el juego Last Oasis pero no está afiliado a',
        'This website uses cookies to enhance the user experience.': 'Este sitio web utiliza cookies para mejorar la experiencia del usuario.',
        'Login with discord': 'Conectar con discord',
        'Connect in demo mode': 'Conectar en modo demo',
        'Crafting Calculator': 'Calculadora de crafteo',
        'Here you can see and automatically calculate the materials needed to build each item. It is in English and Spanish': 'Aquí puedes ver los materiales necesarios para construir cada cosa que necesites y con la cantidad que necesites como si fuera una lista de la compra. Está en inglés y en español',
        'See how much time is left to finish the auctions of the maps you want easily': 'Mira cuánto tiempo queda para terminar las subastas de los mapas que quieras fácilmente',
        'Trading System': 'Sistema de intercambio',
        'You can create offers or search for them easily from here, you don\'t need to be on 20 discord servers looking for who to exchange with': 'Puedes crear ofertas o buscarlas fácilmente desde aquí, no necesitas estar en 20 servidores de discord buscando con quien intercambiar',
        'Check when your walkers were last used and who used them in a simple and quick way. I have created a discord bot that apart from giving other functions allows you to control the walkers log in an easier way': 'Comprueba cuándo se usaron los walkers por última vez y quién los usó de forma sencilla y rápida. He creado un bot de discord que además de dar otras funciones te permite controlar el registro de walkers de una manera más fácil',
        'Clan Diplomacy': 'Controla el clan',
        'Use this section to control your clan, make alliances or send wars and to easily show it to your clan members.': 'Usa esta sección para controlar tu clan, hacer alianzas o enviar guerras y mostrarlo fácilmente a los miembros de tu clan.',
        'Create and edit maps to add resources or strategic points.': 'Crea y edita mapas para añadir recursos o puntos estratégicos.',
        'Your details': 'Tus datos',
        'Discord Tag': 'Discord Tag',
        'Nick in Game': 'Nick en el juego',
        'Not defined': 'No definido',
        'No Clan': 'Sin clan',
        'Delete user': 'Borrar usuario',
        'Close session': 'Cerrar sesión',
        'Are you sure?': '¿Estás seguro?',
        'This option is not reversible, your user and all his data will be deleted.': 'Esta opción no es reversible, su usuario y todos sus datos serán eliminados.',
        Cancel: 'Cancelar',
        'Add name in the game': 'Añade tu nombre en el juego',
        'Your name in Last Oasis': 'Tu nombre en Last Oasis',
        Add: 'Añadir',
        Share: 'Compartir',
        Copy: 'Copiar al portapapeles',
        'Join a clan': 'Unirse a un clan',
        'Clan Name': 'Nombre del clan',
        'Flag Color': 'Color de la bandera',
        '(Optional)': '(Opcional)',
        'Create a clan': 'Crear el clan',
        'Manage Clan': 'Controlar el clan',
        'Leave clan': 'Salirse del clan',
        'Error when connecting to the API': 'Error al conectarse con la API',
        'The page you are looking for does not exist': 'La página que estas buscando no existe',
        'This user cannot be found': 'Este usuario no pudo ser encontrado',
        'You do not have permission to access this page': 'No tienes permiso para acceder a esta página',
        'Change language': 'Cambiar idioma',
        Spanish: 'Español',
        English: 'Ingles',
        Russian: 'Ruso',
        French: 'Francés',
        German: 'Alemán',
        Transactions: 'Transacciones',
        Transaction: 'Transacción',
        Total: 'Total',
        Date: 'Fecha',
        'Member List': 'Listado de miembros',
        Kick: 'Expulsar',
        'List of requests': 'Listado de solicitudes',
        Accept: 'Aceptar',
        Reject: 'Rechazar',
        'There are no pending requests': 'No hay solicitudes pendientes',
        'Loading the list of requests to enter the clan': 'Cargando la lista de solicitudes para entrar en el clan',
        'Transfer Clan': 'Transferir el clan',
        'This option is not reversible, so be careful who you pass it on to in the leadership of the clan': 'Esta opción no es reversible, así que ten cuidado a quién eliges como líder del clan',
        'New leader:': 'Nuevo líder:',
        'Change leader': 'Cambiar líder',
        Delete: 'Borrar',
        'Delete Clan': 'Borrar Clan',
        'By deleting the clan you will delete all the data linked to it, be careful because this option is not reversible': 'Borrando el clan se borrarán todos los datos vinculados a él, ten cuidado porque esta opción no es reversible',
        Menu: 'Menú',
        'Total materials': 'Total de materiales',
        'To make': 'To make',
        'You need the following materials': 'You need the following materials',
        'Copy to clipboard': 'Copy to clipboard',
        'Generate a link to share it': 'Generate a link to share it',
        'List of all necessary materials by': 'Lista de todos los materiales necesarios por',
        'Download Totals': 'Descargar totales',
        'Application to enter the clan sent': 'La solicitud para entrar en el clan fue enviada',
        Leader: 'Líder',
        'Discord Invite Link': 'Enlace para discord',
        Actions: 'Acciones',
        'Send request': 'Enviar solicitud',
        'Walker ID': 'ID del Walker',
        Request: 'Solicitud',
        'Request message': 'Mensaje de la solicitud',
        'You don\'t have access here, try to log in again': 'No tienes acceso aquí, intenta entrar de nuevo',
        'Error when kicking a member': 'Error al expulsar al miembro',
        'Error when add member': 'Error añadir el nuevo miembro',
        'Error when reject member': 'Error al rechazar la solicitud',
        'Clan deleted correctly': 'El clan se ha borrado correctamente',
        'Error when delete clan': 'Error al borrar el clan',
        'Error when change owner of clan': 'Error al cambiar de líder del clan',
        'This option is not reversible': 'Esta opción no es reversible',
        Search: 'Buscar',
        Clean: 'Limpiar',
        Owner: 'Dueño',
        'Last User': 'Último usuario',
        'Last Use': 'Último uso',
        'You need to have a clan to access this section': 'Necesitas estar en un clan para acceder a esta sección',
        'For the walkers to appear it is necessary to link the discord server with the clan, only users with administration power can add the discord server.': 'Para que aparezcan los walkers es necesario vincular el servidor de discord con el clan, sólo los usuarios que son admins pueden agregar el servidor de discord.',
        'Discord ID': 'ID de Discord',
        'Link discord server': 'Vincular servidor de discord',
        'Discord Bot': 'Bot de Discord',
        'You need to add the bot to your discord to compile the list of walkers from the log, but it also has other functions like checking what you need to do the different items': 'Necesitas añadir el bot a tu discord para leer la lista de walkers desde el log, pero también tiene otras funciones como comprobar lo que necesitas para hacer los diferentes objetos',
        'Map List': 'Lista de mapas',
        'Map Name': 'Nombre del mapa',
        'Open a map that has already been created': 'Abrir un mapa ya creado',
        'Open map': 'Abrir el mapa',
        'New Map': 'Nuevo mapa',
        'Map ID': 'Map ID',
        'Map Pass': 'Map Pass',
        'Show Grid': 'Mostrar la cuadrícula',
        'Hide Grid': 'Ocultar la cuadrícula',
        'Allow Editing': 'Permitir la edición',
        'Read Only': 'Sólo lectura',
        'Enable editing with the link': 'Habilitar la edición con el enlace',
        'Date of burning': 'Fecha del quemado',
        'Map Type': 'Tipo de mapa',
        'Create new map': 'Crear un nuevo mapa',
        'Back to the list of maps': 'Volver a la lista de mapas',
        List: 'Lista',
        Edit: 'Editar',
        Password: 'Contraseña',
        'Update Data': 'Actualizar Datos',
        'Updated data': 'Datos actualizados',
        'Change Password': 'Cambiar contraseña',
        'Password changed': 'Contraseña cambiada',
        Error: 'Error',
        Information: 'Información',
        Type: 'Tipo',
        Coordinate: 'Coordenada',
        'Not the same as in the game': 'No es la misma que en el juego',
        Quality: 'Calidad',
        'Create resource': 'Crear recurso',
        'Login again': 'Conéctate de nuevo',
        'Temporal Marker': 'Marca temporal',
        'Published Trades': 'Intercambios publicados',
        Supply: 'Suministro',
        Demand: 'Demanda',
        Resource: 'Recurso',
        'Resource or mats for': 'Recurso o materiales para',
        Region: 'Región',
        'Filter trades': 'Filtrar',
        'Clean filter': 'Limpiar filtro',
        'If you want to publish your own exchange offers you have to be connected': 'Si quieres publicar tus propios intercambios tienes que estar conectado',
        'Publish an trade': 'Publicar un intercambio',
        Quantity: 'Cantidad',
        Publish: 'Publicar',
        'Price per unit': 'Precio por unidad',
        Unit: 'ud',
        'No trade offers were found with this filter': 'No se encontraron intercambios con este filtro',
        Allies: 'Aliados',
        'NAP or Settlers': 'NAP o Colonos',
        Symbol: 'Símbolo',
        War: 'Guerra',
        'Create a relationship': 'Crear una relación',
        'This data is not saved, if you reload the page it will be deleted': 'Estos datos no se guardan, si recargas la página se borrarán',
        'Sound Off': 'Sonido apagado',
        'Sound On': 'Sonido encendido',
        'Show map': 'Ver mapa',
        'Delete map': 'Borrar mapa',
        'Share map': 'Compartir mapa',
        Hours: 'Horas',
        'Try again later': 'Inténtalo de nuevo más tarde',
        Minutes: 'Minutos',
        Seconds: 'Segundos',
        Description: 'Descripción',
        Start: 'Iniciar',
        Stop: 'Parar',
        'made on': 'Se fabrica en:',
        'Cost to learn': 'Cost to learn',
        Recipe: 'Recipe',
        'Who have learned it?': 'Who have learned it?',
        'Latest updates': 'Últimas actualizaciones',
        'Report Bugs': 'Reportar fallos',
        'If you find a bug, let me know on GitHub so it can be fixed!': 'Agradecería si encuentras un error y me lo cuentas en GitHub o en otra plataforma para que pueda arreglarlo',
        Report: 'Reportar',
        'I have also created a discord bot useful to control the walkers and make a list of what is needed to create objects.': 'También he creado un bot para discord útil para controlar los walkers y hacer una lista de lo que se necesita para crear objetos.',
        'Go to Discord bot': 'Ir al bot de Discord',
        'Dm94Dani´s Discord': 'El discord de Dm94Dani',
        'Buy me a coffee': 'Cómprame un café',
        'Steam Page': 'Página de steam',
        'Official Discord': 'Discord Oficial',
        Wiki: 'Wiki',
        'Privacy Agreement': 'Política de privacidad',
        'Cookies - This site only uses Google cookies to view web traffic.': 'Cookies - Esta web solo usa las cookies de Google para analizar el trafico de la web.',
        'Private data - The only registration data saved is Discord ID and Discord Tag': 'Datos privados - Los únicos datos de registro que se guardan son el Discord ID y el Discord Tag',
        'Data added to the website such as diplomacy, map resources or clan members are stored in a database and the necessary security measures are taken so that no one can access these data.': 'Los datos que se añaden a la web como la diplomacia, recursos del mapa o miembros de un clan se almacenan en una base de datos y se toman las medidas de seguridad necesarias para que nadie pueda acceder a esos datos.',
        'Source Code is published on GitHub for full disclosure where you can also report any issues found.': 'Si crees que esta pagina no es segura, todo su código esta publicado en GitHub y proporciono todos los medios para que reportes el fallo.',
        Vitamins: 'Vitaminas',
        Equipment: 'Equipamiento',
        Construction: 'Construcción',
        Walkers: 'Walkers',
        'Point Of Interest': 'Punto de interés',
        'Trade Station': 'Estación de comercio',
        Proxy: 'Proxy',
        All: 'Todos',
        Aloe: 'Aloe vera',
        'Animal Fat': 'Grasa animal',
        Apple: 'Manzana',
        Ash: 'Ceniza',
        Beeswax: 'Cera de abejas',
        'Blood Turnip': 'Nabo sangriento',
        'Bone Glue': 'Adhesivo de hueso',
        'Bone Splinter': 'Astilla de hueso',
        'Cactus Flesh': 'Carne de cactus',
        Cattail: 'Enea',
        'Ceramic Shard': 'Esquirla de cerámica',
        Charcoal: 'Carbón',
        'Chitin Plate': 'Escama de quitina',
        Clay: 'Arcilla',
        'Contaminated Water': 'Agua contaminada',
        Corn: 'Maíz',
        Cotton: 'Algodón',
        'Earth Wax': 'Ceresina',
        Feather: 'Pluma',
        Fiber: 'Fibra',
        'Fiber Weave': 'Tejido de Fibra',
        Fragment: 'Fragmento',
        Glass: 'Vial de cristal',
        Hide: 'Esconderse',
        'Huge Cactus Fruit': 'Fruto de cactus enorme',
        Insects: 'Insectos',
        'Iron Ingot': 'Lingote de hierro',
        'Iron Ore': 'Material de hierro',
        Lava: 'Lava',
        'Liquid Fuel': 'Combustible líquido',
        'Mushroom Flesh': 'Carne de champiñón',
        'Nibiran Mineral': 'Mineral de Nibiru',
        'Nomad Cloth': 'Tela Nomad',
        'Proxy License': 'Proxy License',
        Obsidian: 'Obsidiana',
        'Palm Leaves': 'Hojas de palmera',
        Pearl: 'Perla',
        'Purified Water': 'Agua Purificada',
        'Red Banana': 'Plátano rojo',
        'Redwood Wood': 'Madera de secuoya roja',
        'Reinforced Plank': 'Reforzar tablón',
        Rope: 'Cuerda',
        'Rupu Gel': 'Mantequilla de la tribu rupu',
        'Rupu Pelt': 'Piel rupu',
        'Rupu Vine': 'Vid Rupu',
        'Salt Rock': 'Roca de sal',
        Sand: 'Arena',
        'Shattered Fragment': 'Fragmentos hechos añicos',
        Stone: 'Piedra',
        Sulfur: 'Azufre',
        Tablet: 'Placa',
        'Terrain: Clay Spots': 'Terrain: Clay Spots',
        'Terrain: Black Soil': 'Terrain: Black Soil',
        'Terrain: Excavatable': 'Terrain: Excavatable',
        Tar: 'Brea',
        Thornberry: 'Baya',
        Torque: 'Torque',
        Wood: 'Madera',
        'Wood Shaft': 'Poste de Madera',
        'Worm Scale': 'Escama de gusano',
        'Worm Silk': 'Seda de gusano',
        Base: 'Base',
        'Enemy Base': 'Base Enemiga',
        'Friend Base': 'Base Amiga',
        Trader: 'Comerciante',
        'Barrier Base': 'Base de barrera',
        'Barrier Gate': 'Compuerta de barrera',
        'Barrier Plank': 'Tablón de barrera',
        Bed: 'Cama',
        Hammock: 'Hamaca',
        'Sand Bed': 'Cama de arena',
        'Cement Battlements': 'Almenas de hormigón',
        'Cement Corner': 'Esquina de hormigón',
        'Cement Door': 'Puerta de hormigón',
        'Cement Foundation': 'Base de hormigón',
        'Cement Roof': 'Techo de hormigón',
        'Cement Wall 1': 'Pared de hormigón 1',
        'Cement Wall 2': 'Pared de hormigón 2',
        'Cement Wall With Window 1': 'Pared con ventana de hormigón 1',
        'Cement Wall With Window 2': 'Pared con ventana de hormigón 2',
        'Cement Wall With Windows 1': 'Pared con ventanas de hormigón 1',
        'Cement Wall With Windows 2': 'Pared con ventanas de hormigón 2',
        'Clay Battlement': 'Almenas de arcilla',
        'Clay Corner': 'Esquina de arcilla',
        'Clay Door': 'Puerta de arcilla',
        'Clay Foundation': 'Base de arcilla',
        'Clay Roof': 'Techo de arcilla',
        'Clay Wall': 'Pared de arcilla',
        'Clay Wall with Window': 'Pared con ventana de arcilla',
        'Clay Wall with Windows': 'Pared con ventanas de arcilla',
        'Stone Wall': 'Pared de piedra',
        'Stone Door': 'Puerta de piedra',
        'Stone Roof': 'Techo de piedra',
        'Stone Wall with Window': 'Pared con ventana de piedra',
        'Ammo Chest': 'Cofre de municiones',
        'Gigantic Chest': 'Cofre gigante',
        'Large Chest': 'Cofre grande',
        'Large Water Bag': 'Contenedor grande de agua',
        'Medium Chest': 'Cofre mediano',
        'Medium Water Bag': 'Recipiente de líquidos mediano',
        'Obsidian Canister': 'Obsidian Canister',
        'Obsidian Pot': 'Obsidian Pot',
        'Small Water Bag': 'Bolsa de agua pequeña',
        'Small Chest': 'Cofre pequeño',
        'Water Pitcher': 'Cántaro de agua',
        'Clan Flag': 'Bandera del clan',
        'Clan Flag Hanging': 'Bandera de clan colgando',
        'Heavy Wood Battlements': 'Almenas de madera pesada',
        'Heavy Wood Corner': 'Esquina de madera pesada',
        'Heavy Wood Door': 'Puerta de madera pesada',
        'Heavy Wood Double Slit Wall': 'Doble hendidura en la pared de madera pesada',
        'Heavy Wood Foundation': 'Base de madera pesada',
        'Heavy Wood Roof': 'Techo de madera pesada',
        'Heavy Wood Slit Wall': 'Hendidura en la pared de madera pesada',
        'Heavy Wood Wall 1': 'Pared 1 de madera pesada',
        'Heavy Wood Wall 2': 'Pared 2 de madera pesada',
        'Light Wood Door': 'Puerta de madera ligera',
        'Light Wood Foundation': 'Base de madera ligera',
        'Light Wood Guard Rail': 'Barandilla de madera ligera',
        'Light Wood Roof': 'Techo de madera ligera',
        'Light Wood Stairs': 'Escaleras de madera ligera',
        'Light Wood Wooden Battlements': 'Almenas de madera ligera',
        'Light Wood Wooden Corner': 'Esquina de madera ligera',
        'Light Wood Wooden Double Slit Wall': 'Muro con doble apertura de madera ligera',
        'Light Wood Wooden Slit Wall': 'Muro de madera con doble hendidura ligera',
        'Light Wood Wooden Wall': 'Muro de madera ligera',
        'Medium Wood Battlements': 'Almenas de madera mediana',
        'Medium Wood Door': 'Puerta de madera mediana',
        'Medium Wood Double Slit Wall': 'Doble hendidura en la pared de madera mediana',
        'Medium Wood Foundation': 'Base de madera mediana',
        'Medium Wood Roof': 'Techo de madera mediana',
        'Medium Wood Slit Wall': 'Hendidura en la pared de madera mediana',
        'Medium Wood Wall': 'Pared de madera mediana',
        'Cloth Door': 'Puerta de tela',
        'Sandbag Roof': 'Techo de sacos de arena',
        'Sandbag Wall': 'Muro de sacos de arena',
        'Sandbag Wall Window': 'Muro de sacos de arena con ventana',
        Crane: 'Grúa',
        'Hose Station': 'Estación de manguera',
        Rangefinder: 'Telémetro',
        Ballista: 'Ballesta',
        Catapult: 'Catapulta',
        'Gun Pod': 'Cápsula de armas',
        'Net Thrower': 'Lanzarredes',
        'Remote Ballista': 'Ballesta a distancia',
        Repeater: 'Rifle',
        'Scattershot Gun': 'Escopeta de dispersión',
        Slingshot: 'Resortera',
        'Small Ballista': 'Ballesta pequeña',
        'Gun Pod Plating': 'Revestimiento de la cápsula de armas',
        'Gun Pod Shell': 'Armazón de la capsula de armas',
        'Chair Comfortable': 'Chair Comfortable',
        'Chair Simple': 'Chair Simple',
        'Chair Throne': 'Chair Throne',
        Table: 'Table',
        'Basket Open': 'Basket Open',
        'Basket Tall': 'Basket Tall',
        'Basket Wide': 'Basket Wide',
        'Carpet Dark': 'Carpet Dark',
        'Carpet Light': 'Carpet Light',
        'Fire Goblet': 'Fire Goblet',
        'Lamp Double Hanging': 'Lamp Double Hanging',
        'Lamp Overhanging': 'Lamp Overhanging',
        'Lamp Single Hanging': 'Lamp Single Hanging',
        'Lamp Standing': 'Lamp Standing',
        'Advanced Fiberworking Station': 'Estación de procesamiento textil avanzada',
        'Advanced Furnace': 'Caldera avanzada',
        'Advanced Woodworking Station': 'Estación de carpintería avanzada',
        'Artificer Woodworking Station': 'Estación artesanal de carpintería',
        'Camp Fire': 'Fogata',
        'Fiberworking Station': 'Estación de procesamiento textil',
        Furnace: 'Horno',
        Lumbermill: 'Aserradero',
        'Obsidian Machine': 'Obsidian Machine',
        'Purification Station': 'Estación de purificación',
        Quarry: 'Cantera',
        'Infused Obsidian Bottle': 'Infused Obsidian Bottle',
        'Soil Excavator': 'Excavadora',
        'Stomping Station': 'Estación de prensado',
        'Torque Windmill': 'Molino energético',
        'Water Condenser': 'Condensador de agua',
        'Woodworking Station': 'Estación de carpintería',
        'Cauterizing Station': 'Estación médica',
        'Defensive Tower': 'Torre de defensa',
        'Rupu Sling': 'Resortera rupu',
        'Bone Bolt': 'Perno de hueso',
        'Bone Harpoon': 'Arpón de hueso',
        'Ceramic-Tipped Bolt': 'Flecha con punta de cerámica',
        'Ceramic-Tipped Harpoon': 'Arpón con punta de cerámica',
        'Fire Bolt': 'Perno incendiario',
        'Flint Bolt': 'Perno de sílex',
        'Flint Harpoon': 'Arpón de sílex',
        'Hellfire Bolt': 'Perno infernal',
        'Iron-Tipped Bolt': 'Perno con punta de hierro',
        'Iron-Tipped Harpoon': 'Arpón con punta de hierro',
        'Explosive Bolt': 'Explosive Bolt',
        'Catapult Boulder': 'Roca para catapulta',
        'Fire Bomb': 'Bomba incendiaria',
        'Hullbreaker Rock': 'Perno rompecascos',
        Bombolt: 'Bombolt',
        Net: 'Red',
        Dart: 'Dardo',
        'Floating Mine': 'Floating Mine',
        'Explosive Dart': 'Explosive Dart',
        'Hullbreaker Scattershot': 'Rompecascos de dispersión',
        Scattershot: 'Munición de dispersión',
        'Aloe Goo Bomb': 'Aloe Goo Bomb',
        'Chalk Bomb': 'Chalk Bomb',
        'Cluster Bomb': 'Cluster Bomb',
        'Green Death Bomb': 'Bomba mortal verde',
        'Insect Bomb': 'Insect Bomb',
        'Rupu Rock': 'Roca rupu',
        'Small Boulder': 'Roca pequeña',
        'Sulfur Bomb': 'Bomba de azufre',
        'Gas Mask': 'Gas Mask',
        'Baskwood Armor': 'Armadura de espartadera',
        'Baskwood Boots': 'Botas de espartadera',
        'Baskwood Bracers': 'Brazaletes de espartadera',
        'Carapace Armor': 'Armadura de caparazón',
        'Carapace Boots': 'Botas caparazón',
        'Carapace Gauntlets': 'Guanteletes caparazón',
        Cloak: 'Capa',
        'Feather Boots': 'Botas con plumas',
        'Fiber Arm Wraps': 'Vendas de fibras para los brazos',
        'Fiber Headwrap': 'Turbante de fibras',
        'Fiber Sandals': 'Sandalias de fibra',
        'Fiber Shirt And Trousers': 'Pantalones y camisetas de fibra',
        'Brittle Bone Armor': 'Armadura de hueso quebradiza',
        'Forester\'s Armor': 'Armadura de guardabosques',
        'Forester\'s Sandals': 'Sandalias de guardabosques',
        'Forester\'s Sleeves': 'Mangas de guardabosques',
        'Iron Studded Armor': 'Armadura con tachuelas de hierro',
        'Iron Studded Boots': 'Botas con tachuelas de hierro',
        'Iron Studded Gauntlets': 'Guanteletes con tachuelas de hierro',
        'Redwood Wood Armor': 'Armadura de secuoya roja',
        'Redwood Wood Boots': 'Botas de secuoya roja',
        'Redwood Wood Bracers': 'Brazaletes de secuoya roja',
        'Cloaked Rupu Fur Armor': 'Armadura de piel de rupu con manto',
        'Rupu Fur Armor': 'Armadura de piel de rupu',
        'Rupu Fur Sandals': 'Sandalias de lana rupu',
        'Rupu Fur Sleeves': 'Mangas de piel de rupu',
        'Triple Stitch Armor': 'Armadura de triple puntada',
        'Triple Stitch Boots': 'Botas de triple puntada',
        'Triple Stitch Bracers': 'Brazaletes de triple puntada',
        Kite: 'Cometa',
        Exoskeleton: 'Exoskeleton',
        'Durable Water Sack': 'Saco de agua resistente',
        'Heavy Backpack': 'Mochila pesada',
        'Light Backpack': 'Mochila ligera',
        'Split Durable Water Sack': 'Zurrón dividido resistente de agua',
        'Medium Backpack': 'Mochila mediana',
        'Torque Backpack': 'Mochila energética',
        'Water Circulator': 'Distribuidor de agua',
        Wingsuit: 'Traje aéreo',
        'Bone Bottle': 'Botella de hueso',
        'Ceramic Flask': 'Botella de cerámica',
        'Improvised Bottle': 'Botella improvisada (20)',
        'Makeshift Bottle': 'Botella improvisada (5)',
        'Obsidian Flask': 'Obsidian Flask',
        'Split Bone Bottle': 'Botella de hueso dividida',
        'Split Ceramic Flask': 'Botella dividida de cerámica',
        'Foraging Pouch': 'Bolsa de recolector',
        'Large Gathering Pouch': 'Bolsa de recolección grande',
        'Beltless Grappling Hook': 'Arpeo sin cinturón',
        'Fast Grappling Hook': 'Arpeo rápido',
        'Long Grappling Hook': 'Arpeo largo',
        'Repaired Grappling Hook': 'Arpeo arreglado',
        'Torque Battery': 'Acumulador de energía',
        'Primitive Bandage': 'Vendaje primitivo',
        'Sterile Bandage': 'Vendaje esterilizado',
        Bonebreaker: 'Rompehuesos',
        'Desert Mule': 'Mula del desierto',
        'Fury Fumes': 'Humos de ira',
        'Jojo Mojo': 'Jojo Mojo',
        'Race Dust': 'Polvo veloz',
        'Rupu Repellent': 'Repelente de rupu',
        'Sinus Destroyer': 'Destrozatabiques',
        'Vision Powder': 'Polvos de visión',
        'Beat Stick': 'Palo',
        'Blunt Quarterstaff': 'Bastón largo contundente',
        'Bonespike Sword': 'Espada con punta de hueso',
        'Bouldercut Battle Axe': 'Hacha rompepiedras de mano',
        'Firestone Bladestaff': 'Firestone Bladestaff',
        'Firestone Bludgeon': 'Firestone Bludgeon',
        'Firestone Bozdogan': 'Firestone Bozdogan',
        'Firestone Hammerstaff': 'Firestone Hammerstaff',
        'Firestone Kopesh': 'Firestone Kopesh',
        'Firestone Longblade': 'Firestone Longblade',
        'Ironblade Quarterstaff': 'Bastón largo de hierro',
        'Jaggertooth Club': 'Garrote dentado',
        'Jaggertooth Maul': 'Mazo dentado',
        Javelin: 'Jabalina',
        'Long Bonespike Swordstaff': 'Bastón afilado de hueso largo',
        'Long Ceramic Hoofmace': 'Mazo largo con pezuña de ceramica',
        'Nibiran Battle Axe': 'Hacha de combate de nibiru',
        'Nibiran Curved Dagger': 'Daga curvada de nibiru',
        'Nibiran Decapitator': 'Decapitador de nibiru',
        'Nibiran Hammer': 'Martillo de nibiru',
        'Nibiran Quarterstaff': 'Baston largo de nibiru',
        'Nibiran Warhammer': 'Martillo de guerra de nibiru',
        'Paddleblade Quarterstaff': 'Baston largo con paleta afilada',
        'Rawbone Club': 'Garrote de hueso',
        'Rawbone Maul': 'Mazo de hueso',
        'Rawbone Quarterstaff': 'Baston largo de hueso',
        'Sawtooth Sword': 'Espada serrada',
        'Short Ceramic Hoofmace': 'Mazo corto con pezuña de ceramica',
        'Short Malletblade': 'Mazo afilado corto',
        Singblade: 'Espada doble',
        'Spikebone Club': 'Palo de puntas de hueso',
        'Spikebone Maul': 'Mazo con punta de hueso',
        'Throwing Net': 'Throwing Net',
        Torch: 'Antorcha',
        'Traveller\'s Staff': 'Baston del viajero',
        'Wyndan Flame Sword': 'Espada ardiente de wyndan',
        'Wyndan Hammer': 'Martillo de wyndan',
        'Wyndan Sabre': 'Sable wyndan',
        'Wyndan Warhammer': 'Martillo de guerra wyndan',
        'Wyndanblade Quarterstaff': 'Baston largo de wyndan',
        Firebomb: 'Firebomb',
        'Firestone Axe': 'Firestone Axe',
        'Firestone Battleaxe': 'Firestone Battleaxe',
        'Advanced Hatchet': 'Hacha avanzada',
        'Bouldercut Hand Axe': 'Hacha rompepiedras de mano',
        'Heavy Rawbone Hand Axe': 'Hacha de hueso pesada',
        'Nibiran Hand Axe': 'Hacha de mano de nibiru',
        'Rawbone Battle Axe': 'Hacha de batalla de hueso larga',
        'Rawbone Hand Axe': 'Hacha de batalla de hueso',
        'Woodcutter\'s Hatchet': 'Hacha del talador',
        'Advanced Pickaxe': 'Pico avanzado',
        'Master Pickaxe': 'Pico maestro',
        'Simple Pickaxe': 'Pico simple',
        'Simple Repair Hammer': 'Martillo de reparación simple',
        Scythe: 'Guadaña',
        'Simple Sickle': 'Hoz simple',
        'Nibiran Ingot': 'Nibiran Ingot',
        'Lava Fuel': 'Lava Fuel',
        'Buffalo Walker Body': 'Cuerpo Walker Búfalo',
        'Buffalo Walker Legs (1 of 2)': 'Patas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Legs Armored': 'Patas Blindadas de Walker Búfalo',
        'Buffalo Walker Legs Heavy': 'Patas Pesadas de Walker Búfalo',
        'Buffalo Walker Heavy Wings (1 of 2)': 'Buffalo Walker Heavy Wings (1 of 2)',
        'Buffalo Walker Medium Wings (1 of 2)': 'Alas medianas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Raider Wings (1 of 2)': 'Buffalo Walker Raider Wings (1 of 2)',
        'Buffalo Walker Rugged Wings (1 of 2)': 'Buffalo Walker Rugged Wings (1 of 2)',
        'Buffalo Walker Skirmish Wings (1 of 2)': 'Buffalo Walker Skirmish Wings (1 of 2)',
        'Buffalo Walker Small Wings (1 of 2)': 'Alas pequeñas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Wings (1 of 2)': 'Alas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Upgrade - Cargo - Tier 2': 'Mejora del walker búfalo - Capacidad de carga - Mejora de rango 2',
        'Buffalo Walker Upgrade - Durability - Tier 2': 'Mejora del walker búfalo - Durabilidad - Mejora de rango 2',
        'Buffalo Walker Upgrade - Gear - Tier 2': 'Mejora del walker búfalo - Almacenamiento de mecanismos - Mejora de rango 2',
        'Buffalo Walker Upgrade - Mobility - Tier 2': 'Mejora del walker búfalo - Mobility - Mejora de rango 2',
        'Buffalo Walker Upgrade - Torque - Tier 2': 'Mejora del walker búfalo - Capacidad energética - Mejora de rango 2',
        'Buffalo Walker Upgrade - Water - Tier 2': 'Mejora del walker búfalo - Depósito de agua - Mejora de rango 2',
        'Buffalo Walker Upgrade - Cargo - Tier 3': 'Mejora del walker búfalo - Capacidad de carga - Mejora de rango 3',
        'Buffalo Walker Upgrade - Durability - Tier 3': 'Mejora del walker búfalo - Durabilidad - Mejora de rango 3',
        'Buffalo Walker Upgrade - Gear - Tier 3': 'Mejora del walker búfalo - Almacenamiento de mecanismos - Mejora de rango 3',
        'Buffalo Walker Upgrade - Mobility - Tier 3': 'Mejora del walker búfalo - Mobility - Mejora de rango 3',
        'Buffalo Walker Upgrade - Torque - Tier 3': 'Mejora del walker búfalo - Capacidad energética - Mejora de rango 3',
        'Buffalo Walker Upgrade - Water - Tier 3': 'Mejora del walker búfalo - Depósito de agua - Mejora de rango 3',
        'Buffalo Walker Upgrade - Cargo - Tier 4': 'Mejora del walker búfalo - Capacidad de carga - Mejora de rango 4',
        'Buffalo Walker Upgrade - Durability - Tier 4': 'Mejora del walker búfalo - Durabilidad - Mejora de rango 4',
        'Buffalo Walker Upgrade - Gear - Tier 4': 'Mejora del walker búfalo - Almacenamiento de mecanismos - Mejora de rango 4',
        'Buffalo Walker Upgrade - Mobility - Tier 4': 'Mejora del walker búfalo - Mobility - Mejora de rango 4',
        'Buffalo Walker Upgrade - Torque - Tier 4': 'Mejora del walker búfalo - Capacidad energética - Mejora de rango 4',
        'Buffalo Walker Upgrade - Water - Tier 4': 'Mejora del walker búfalo - Depósito de agua - Mejora de rango 4',
        'Camelop Walker Body': 'Cuerpo de Walker Camelop',
        'Camelop Walker Legs (1 of 2)': 'Patas del Walker Camelop (1 de 2)',
        'Camelop Walker Upgrade - Torque - Tier 2': 'Mejora del walker Camelop - Capacidad energética - Mejora de rango 2',
        'Camelop Walker Upgrade - Water - Tier 2': 'Mejora del walker Camelop - Depósito de agua - Mejora de rango 2',
        'Camelop Walker Upgrade - Torque - Tier 3': 'Mejora del walker Camelop - Capacidad energética - Mejora de rango 3',
        'Camelop Walker Upgrade - Water - Tier 3': 'Mejora del walker Camelop - Depósito de agua - Mejora de rango 3',
        'Camelop Walker Upgrade - Torque - Tier 4': 'Mejora del walker Camelop - Capacidad energética - Mejora de rango 4',
        'Camelop Walker Upgrade - Water - Tier 4': 'Mejora del walker Camelop - Depósito de agua - Mejora de rango 4',
        'Cobra Walker Body': 'Cuerpo de Walker Cobra',
        'Cobra Walker Legs (1 of 2)': 'Cobra Walker Legs (1 of 2)',
        'Cobra Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Cobra - Capacidad de carga - Mejora de rango 2',
        'Cobra Walker Upgrade - Torque - Tier 2': 'Mejora del walker Cobra - Capacidad energética - Mejora de rango 2',
        'Cobra Walker Upgrade - Water - Tier 2': 'Mejora del walker Cobra - Depósito de agua - Mejora de rango 2',
        'Cobra Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Cobra - Capacidad de carga - Mejora de rango 3',
        'Cobra Walker Upgrade - Torque - Tier 3': 'Mejora del walker Cobra - Capacidad energética - Mejora de rango 3',
        'Cobra Walker Upgrade - Water - Tier 3': 'Mejora del walker Cobra - Depósito de agua - Mejora de rango 3',
        'Cobra Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Cobra - Capacidad de carga - Mejora de rango 4',
        'Cobra Walker Upgrade - Torque - Tier 4': 'Mejora del walker Cobra - Capacidad energética - Mejora de rango 4',
        'Cobra Walker Upgrade - Water - Tier 4': 'Mejora del walker Cobra - Depósito de agua - Mejora de rango 4',
        'Dinghy Walker Body': 'Cuerpo del Walker Dinghy',
        'Dinghy Walker Legs (1 of 2)': 'Patas del Walker Dinghy',
        'Dinghy Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Dinghy (1 de 2)',
        'Dinghy Walker Wings (1 of 2)': 'Alas del Walker Dinghy (1 de 2)',
        'Dinghy Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Dinghy - Capacidad de carga - Mejora de rango 2',
        'Dinghy Walker Upgrade - Durability - Tier 2': 'Mejora del walker Dinghy - Durabilidad - Mejora de rango 2',
        'Dinghy Walker Upgrade - Gear - Tier 2': 'Mejora del walker Dinghy - Almacenamiento de mecanismos - Mejora de rango 2',
        'Dinghy Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Dinghy - Mobility - Mejora de rango 2',
        'Dinghy Walker Upgrade - Torque - Tier 2': 'Mejora del walker Dinghy - Capacidad energética - Mejora de rango 2',
        'Dinghy Walker Upgrade - Water - Tier 2': 'Mejora del walker Dinghy - Depósito de agua - Mejora de rango 2',
        'Dinghy Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Dinghy - Capacidad de carga - Mejora de rango 3',
        'Dinghy Walker Upgrade - Durability - Tier 3': 'Mejora del walker Dinghy - Durabilidad - Mejora de rango 3',
        'Dinghy Walker Upgrade - Gear - Tier 3': 'Mejora del walker Dinghy - Almacenamiento de mecanismos - Mejora de rango 3',
        'Dinghy Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Dinghy - Mobility - Mejora de rango 3',
        'Dinghy Walker Upgrade - Torque - Tier 3': 'Mejora del walker Dinghy - Capacidad energética - Mejora de rango 3',
        'Dinghy Walker Upgrade - Water - Tier 3': 'Mejora del walker Dinghy - Depósito de agua - Mejora de rango 3',
        'Dinghy Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Dinghy - Capacidad de carga - Mejora de rango 4',
        'Dinghy Walker Upgrade - Durability - Tier 4': 'Mejora del walker Dinghy - Durabilidad - Mejora de rango 4',
        'Dinghy Walker Upgrade - Gear - Tier 4': 'Mejora del walker Dinghy - Almacenamiento de mecanismos - Mejora de rango 4',
        'Dinghy Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Dinghy - Mobility - Mejora de rango 4',
        'Dinghy Walker Upgrade - Torque - Tier 4': 'Mejora del walker Dinghy - Capacidad energética - Mejora de rango 4',
        'Dinghy Walker Upgrade - Water - Tier 4': 'Mejora del walker Dinghy - Depósito de agua - Mejora de rango 4',
        'Domus Walker Body': 'Cuerpo del Walker Domus',
        'Armored Domus Walker Legs (1 of 2)': 'Patas blindadas del walker Domus (1 de 2)',
        'Domus Walker Legs (1 of 2)': 'Patas del Walker Domus (1 de 2)',
        'Heavy Domus Walker Legs (1 of 2)': 'Patas pesadas del Walker Domus (1 de 2)',
        'Domus Walker Heavy Wings (1 of 2)': 'Domus Walker Heavy Wings (1 of 2)',
        'Domus Walker Large Wings (1 of 2)': 'Domus Walker Large Wings (1 of 2)',
        'Domus Walker Medium Wings (1 of 2)': 'Alas medianas del Walker Domus (1 de 2)',
        'Domus Walker Raider Wings (1 of 2)': 'Domus Walker Raider Wings (1 of 2)',
        'Domus Walker Rugged Wings (1 of 2)': 'Domus Walker Rugged Wings (1 of 2)',
        'Domus Walker Skirmish Wings (1 of 2)': 'Domus Walker Skirmish Wings (1 of 2)',
        'Domus Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Domus (1 de 2)',
        'Domus Walker Wings (1 of 2)': 'Alas del Walker Domus (1 de 2)',
        'Domus Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Domus - Capacidad de carga - Mejora de rango 2',
        'Domus Walker Upgrade - Durability - Tier 2': 'Mejora del walker Domus - Durabilidad - Mejora de rango 2',
        'Domus Walker Upgrade - Gear - Tier 2': 'Mejora del walker Domus - Almacenamiento de mecanismos - Mejora de rango 2',
        'Domus Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Domus - Mobility - Mejora de rango 2',
        'Domus Walker Upgrade - Torque - Tier 2': 'Mejora del walker Domus - Capacidad energética - Mejora de rango 2',
        'Domus Walker Upgrade - Water - Tier 2': 'Mejora del walker Domus - Depósito de agua - Mejora de rango 2',
        'Domus Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Domus - Capacidad de carga - Mejora de rango 3',
        'Domus Walker Upgrade - Durability - Tier 3': 'Mejora del walker Domus - Durabilidad - Mejora de rango 3',
        'Domus Walker Upgrade - Gear - Tier 3': 'Mejora del walker Domus - Almacenamiento de mecanismos - Mejora de rango 3',
        'Domus Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Domus - Mobility - Mejora de rango 3',
        'Domus Walker Upgrade - Torque - Tier 3': 'Mejora del walker Domus - Capacidad energética - Mejora de rango 3',
        'Domus Walker Upgrade - Water - Tier 3': 'Mejora del walker Domus - Depósito de agua - Mejora de rango 3',
        'Domus Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Domus - Capacidad de carga - Mejora de rango 4',
        'Domus Walker Upgrade - Durability - Tier 4': 'Mejora del walker Domus - Durabilidad - Mejora de rango 4',
        'Domus Walker Upgrade - Gear - Tier 4': 'Mejora del walker Domus - Almacenamiento de mecanismos - Mejora de rango 4',
        'Domus Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Domus - Mobility - Mejora de rango 4',
        'Domus Walker Upgrade - Torque - Tier 4': 'Mejora del walker Domus - Capacidad energética - Mejora de rango 4',
        'Domus Walker Upgrade - Water - Tier 4': 'Mejora del walker Domus - Depósito de agua - Mejora de rango 4',
        'Falco Walker Body': 'Cuerpo de Walker Falco',
        'Armored Falco Walker Legs (1 of 2)': 'Patas blindadas de Walker Falco (1 de 2)',
        'Falco Walker Legs (1 of 2)': 'Patas de Walker Falco (1 de 2)',
        'Heavy Falco Walker Legs (1 of 2)': 'Patas pesadas de Walker Falco (1 de 2)',
        'Falco Walker Wings (1 of 2)': 'Alas de Walker Falco (1 de 2)',
        'Falco Walker Wings Heavy (1 of 2)': 'Falco Walker Wings Heavy (1 of 2)',
        'Falco Walker Wings Large (1 of 2)': 'Alas grandes de Walker Falco (1 de 2)',
        'Falco Walker Wings Medium (1 of 2)': 'Alas medianas de Walker Falco (1 de 2)',
        'Falco Walker Wings Raider (1 of 2)': 'Falco Walker Wings Raider (1 of 2)',
        'Falco Walker Wings Rugged (1 of 2)': 'Falco Walker Wings Rugged (1 of 2)',
        'Falco Walker Wings Skirmish (1 of 2)': 'Falco Walker Wings Skirmish (1 of 2)',
        'Falco Walker Wings Small (1 of 2)': 'Alas pequeñas de Walker Falco (1 de 2)',
        'Falco Walker Upgrade - Cargo - Tier 1': 'Mejora del walker Falco - Capacidad de carga - Mejora de rango 1',
        'Falco Walker Upgrade - Durability - Tier 1': 'Mejora del walker Falco - Durabilidad - Mejora de rango 1',
        'Falco Walker Upgrade - Gear - Tier 1': 'Mejora del walker Falco - Almacenamiento de mecanismos - Mejora de rango 1',
        'Falco Walker Upgrade - Mobility - Tier 1': 'Mejora del walker Falco - Mobility - Mejora de rango 1',
        'Falco Walker Upgrade - Torque - Tier 1': 'Mejora del walker Falco - Capacidad energética - Mejora de rango 1',
        'Falco Walker Upgrade - Water - Tier 1': 'Mejora del walker Falco - Depósito de agua - Mejora de rango 1',
        'Falco Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Falco - Capacidad de carga - Mejora de rango 2',
        'Falco Walker Upgrade - Durability - Tier 2': 'Mejora del walker Falco - Durabilidad - Mejora de rango 2',
        'Falco Walker Upgrade - Gear - Tier 2': 'Mejora del walker Falco - Almacenamiento de mecanismos - Mejora de rango 2',
        'Falco Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Falco - Mobility - Mejora de rango 2',
        'Falco Walker Upgrade - Torque - Tier 2': 'Mejora del walker Falco - Capacidad energética - Mejora de rango 2',
        'Falco Walker Upgrade - Water - Tier 2': 'Mejora del walker Falco - Depósito de agua - Mejora de rango 2',
        'Falco Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Falco - Capacidad de carga - Mejora de rango 3',
        'Falco Walker Upgrade - Durability - Tier 3': 'Mejora del walker Falco - Durabilidad - Mejora de rango 3',
        'Falco Walker Upgrade - Gear - Tier 3': 'Mejora del walker Falco - Almacenamiento de mecanismos - Mejora de rango 3',
        'Falco Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Falco - Mobility - Mejora de rango 3',
        'Falco Walker Upgrade - Torque - Tier 3': 'Mejora del walker Falco - Capacidad energética - Mejora de rango 3',
        'Falco Walker Upgrade - Water - Tier 3': 'Mejora del walker Falco - Depósito de agua - Mejora de rango 3',
        'Falco Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Falco - Capacidad de carga - Mejora de rango 4',
        'Falco Walker Upgrade - Durability - Tier 4': 'Mejora del walker Falco - Durabilidad - Mejora de rango 4',
        'Falco Walker Upgrade - Gear - Tier 4': 'Mejora del walker Falco - Almacenamiento de mecanismos - Mejora de rango 4',
        'Falco Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Falco - Mobility - Mejora de rango 4',
        'Falco Walker Upgrade - Torque - Tier 4': 'Mejora del walker Falco - Capacidad energética - Mejora de rango 4',
        'Falco Walker Upgrade - Water - Tier 4': 'Mejora del walker Falco - Depósito de agua - Mejora de rango 4',
        'Firefly Walker Body': 'Cuerpo del Walker Luciérnaga',
        'Firefly Walker Legs (1 of 2)': 'Patas del Walker firefly (1 de 2)',
        'Firefly Walker Wings (1 of 2)': 'Alas del Walker firefly (1 de 2)',
        'Firefly Walker Upgrade - Cargo - Tier 1': 'Mejora del walker Luciérnaga - Capacidad de carga - Mejora de rango 1',
        'Firefly Walker Upgrade - Durability - Tier 1': 'Mejora del walker Luciérnaga - Durabilidad - Mejora de rango 1',
        'Firefly Walker Upgrade - Gear - Tier 1': 'Mejora del walker Luciérnaga - Almacenamiento de mecanismos - Mejora de rango 1',
        'Firefly Walker Upgrade - Mobility - Tier 1': 'Mejora del walker Luciérnaga - Mobility - Mejora de rango 1',
        'Firefly Walker Upgrade - Water - Tier 1': 'Mejora del walker Luciérnaga - Depósito de agua - Mejora de rango 1',
        'Firefly Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Luciérnaga - Capacidad de carga - Mejora de rango 2',
        'Firefly Walker Upgrade - Durability - Tier 2': 'Mejora del walker Luciérnaga - Durabilidad - Mejora de rango 2',
        'Firefly Walker Upgrade - Gear - Tier 2': 'Mejora del walker Luciérnaga - Almacenamiento de mecanismos - Mejora de rango 2',
        'Firefly Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Luciérnaga - Mobility - Mejora de rango 2',
        'Firefly Walker Upgrade - Torque - Tier 2': 'Mejora del walker Luciérnaga - Capacidad energética - Mejora de rango 2',
        'Firefly Walker Upgrade - Water - Tier 2': 'Mejora del walker Luciérnaga - Depósito de agua - Mejora de rango 2',
        'Firefly Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Luciérnaga - Capacidad de carga - Mejora de rango 3',
        'Firefly Walker Upgrade - Durability - Tier 3': 'Mejora del walker Luciérnaga - Durabilidad - Mejora de rango 3',
        'Firefly Walker Upgrade - Gear - Tier 3': 'Mejora del walker Luciérnaga - Almacenamiento de mecanismos - Mejora de rango 3',
        'Firefly Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Luciérnaga - Mobility - Mejora de rango 3',
        'Firefly Walker Upgrade - Torque - Tier 3': 'Mejora del walker Luciérnaga - Capacidad energética - Mejora de rango 3',
        'Firefly Walker Upgrade - Water - Tier 3': 'Mejora del walker Luciérnaga - Depósito de agua - Mejora de rango 3',
        'Firefly Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Luciérnaga - Capacidad de carga - Mejora de rango 4',
        'Firefly Walker Upgrade - Durability - Tier 4': 'Mejora del walker Luciérnaga - Durabilidad - Mejora de rango 4',
        'Firefly Walker Upgrade - Gear - Tier 4': 'Mejora del walker Luciérnaga - Almacenamiento de mecanismos - Mejora de rango 4',
        'Firefly Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Luciérnaga - Mobility - Mejora de rango 4',
        'Firefly Walker Upgrade - Torque - Tier 4': 'Mejora del walker Luciérnaga - Capacidad energética - Mejora de rango 4',
        'Firefly Walker Upgrade - Water - Tier 4': 'Mejora del walker Luciérnaga - Depósito de agua - Mejora de rango 4',
        'Hornet Walker Body': 'Cuerpo de Walker Hornet',
        'Hornet Walker Legs (1 of 2)': 'Patas del Walker Hornet (1 de 2)',
        'Hornet Walker Legs Armored': 'Patas blindadas de Walker Hornet',
        'Hornet Walker Legs Heavy': 'Patas Pesadas de Walker Hornet',
        'Hornet Walker Heavy Wings (1 of 2)': 'Hornet Walker Heavy Wings (1 of 2)',
        'Hornet Walker Large Wings (1 of 2)': 'Alas grandes del Walker Hornet (1 de 2)',
        'Hornet Walker Medium Wings (1 of 2)': 'Alas medianas del Walker Hornet (1 de 2)',
        'Hornet Walker Raider Wings (1 of 2)': 'Hornet Walker Raider Wings (1 of 2)',
        'Hornet Walker Rugged Wings (1 of 2)': 'Hornet Walker Rugged Wings (1 of 2)',
        'Hornet Walker Skirmish Wings (1 of 2)': 'Hornet Walker Skirmish Wings (1 of 2)',
        'Hornet Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Hornet (1 de 2)',
        'Hornet Walker Wings (1 of 2)': 'Alas del Walker Hornet (1 de 2)',
        'Hornet Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Hornet - Capacidad de carga - Mejora de rango 2',
        'Hornet Walker Upgrade - Durability - Tier 2': 'Mejora del walker Hornet - Durabilidad - Mejora de rango 2',
        'Hornet Walker Upgrade - Gear - Tier 2': 'Mejora del walker Hornet - Almacenamiento de mecanismos - Mejora de rango 2',
        'Hornet Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Hornet - Mobility - Mejora de rango 2',
        'Hornet Walker Upgrade - Torque - Tier 2': 'Mejora del walker Hornet - Capacidad energética - Mejora de rango 2',
        'Hornet Walker Upgrade - Water - Tier 2': 'Mejora del walker Hornet - Depósito de agua - Mejora de rango 2',
        'Hornet Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Hornet - Capacidad de carga - Mejora de rango 3',
        'Hornet Walker Upgrade - Durability - Tier 3': 'Mejora del walker Hornet - Durabilidad - Mejora de rango 3',
        'Hornet Walker Upgrade - Gear - Tier 3': 'Mejora del walker Hornet - Almacenamiento de mecanismos - Mejora de rango 3',
        'Hornet Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Hornet - Mobility - Mejora de rango 3',
        'Hornet Walker Upgrade - Torque - Tier 3': 'Mejora del walker Hornet - Capacidad energética - Mejora de rango 3',
        'Hornet Walker Upgrade - Water - Tier 3': 'Mejora del walker Hornet - Depósito de agua - Mejora de rango 3',
        'Hornet Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Hornet - Capacidad de carga - Mejora de rango 4',
        'Hornet Walker Upgrade - Durability - Tier 4': 'Mejora del walker Hornet - Durabilidad - Mejora de rango 4',
        'Hornet Walker Upgrade - Gear - Tier 4': 'Mejora del walker Hornet - Almacenamiento de mecanismos - Mejora de rango 4',
        'Hornet Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Hornet - Mobility - Mejora de rango 4',
        'Hornet Walker Upgrade - Torque - Tier 4': 'Mejora del walker Hornet - Capacidad energética - Mejora de rango 4',
        'Hornet Walker Upgrade - Water - Tier 4': 'Mejora del walker Hornet - Depósito de agua - Mejora de rango 4',
        'Mollusk Walker Body': 'Mollusk Walker Body',
        'Mollusk Walker Legs (1 of 2)': 'Mollusk Walker Legs (1 of 2)',
        'Mollusk Walker Legs Armored (1 of 2)': 'Mollusk Walker Legs Armored (1 of 2)',
        'Mollusk Walker Wings (1 of 2)': 'Mollusk Walker Wings (1 of 2)',
        'Mollusk Walker Wings Heavy (1 of 2)': 'Mollusk Walker Wings Heavy (1 of 2)',
        'Mollusk Walker Wings Medium (1 of 2)': 'Mollusk Walker Wings Medium (1 of 2)',
        'Mollusk Walker Wings Raider (1 of 2)': 'Mollusk Walker Wings Raider (1 of 2)',
        'Mollusk Walker Wings Rugged (1 of 2)': 'Mollusk Walker Wings Rugged (1 of 2)',
        'Mollusk Walker Wings Skirmish (1 of 2)': 'Mollusk Walker Wings Skirmish (1 of 2)',
        'Mollusk Walker Wings Small (1 of 2)': 'Mollusk Walker Wings Small (1 of 2)',
        'Mollusk Walker Upgrade - Cargo - Tier 1': 'Mejora del Walker Mollusk - Capacidad de carga - Mejora de rango 1',
        'Mollusk Walker Upgrade - Durability - Tier 1': 'Mejora del Walker Mollusk - Durabilidad - Mejora de rango 1',
        'Mollusk Walker Upgrade - Gear - Tier 1': 'Mejora del Walker Mollusk - Almacenamiento de mecanismos - Mejora de rango 1',
        'Mollusk Walker Upgrade - Mobility - Tier 1': 'Mejora del Walker Mollusk - Mobility - Mejora de rango 1',
        'Mollusk Walker Upgrade - Torque - Tier 1': 'Mejora del Walker Mollusk - Capacidad energética - Mejora de rango 1',
        'Mollusk Walker Upgrade - Water - Tier 1': 'Mejora del Walker Mollusk - Depósito de agua - Mejora de rango 1',
        'Mollusk Walker Upgrade - Cargo - Tier 2': 'Mejora del Walker Mollusk - Capacidad de carga - Mejora de rango 2',
        'Mollusk Walker Upgrade - Durability - Tier 2': 'Mejora del Walker Mollusk - Durabilidad - Mejora de rango 2',
        'Mollusk Walker Upgrade - Gear - Tier 2': 'Mejora del Walker Mollusk - Almacenamiento de mecanismos - Mejora de rango 2',
        'Mollusk Walker Upgrade - Mobility - Tier 2': 'Mejora del Walker Mollusk - Mobility - Mejora de rango 2',
        'Mollusk Walker Upgrade - Torque - Tier 2': 'Mejora del Walker Mollusk - Capacidad energética - Mejora de rango 2',
        'Mollusk Walker Upgrade - Water - Tier 2': 'Mejora del Walker Mollusk - Depósito de agua - Mejora de rango 2',
        'Mollusk Walker Upgrade - Cargo - Tier 3': 'Mejora del Walker Mollusk - Capacidad de carga - Mejora de rango 3',
        'Mollusk Walker Upgrade - Durability - Tier 3': 'Mejora del Walker Mollusk - Durabilidad - Mejora de rango 3',
        'Mollusk Walker Upgrade - Gear - Tier 3': 'Mejora del Walker Mollusk - Almacenamiento de mecanismos - Mejora de rango 3',
        'Mollusk Walker Upgrade - Mobility - Tier 3': 'Mejora del Walker Mollusk - Mobility - Mejora de rango 3',
        'Mollusk Walker Upgrade - Torque - Tier 3': 'Mejora del Walker Mollusk - Capacidad energética - Mejora de rango 3',
        'Mollusk Walker Upgrade - Water - Tier 3': 'Mejora del Walker Mollusk - Depósito de agua - Mejora de rango 3',
        'Mollusk Walker Upgrade - Cargo - Tier 4': 'Mejora del Walker Mollusk - Capacidad de carga - Mejora de rango 4',
        'Mollusk Walker Upgrade - Durability - Tier 4': 'Mejora del Walker Mollusk - Durabilidad - Mejora de rango 4',
        'Mollusk Walker Upgrade - Gear - Tier 4': 'Mejora del Walker Mollusk - Almacenamiento de mecanismos - Mejora de rango 4',
        'Mollusk Walker Upgrade - Mobility - Tier 4': 'Mejora del Walker Mollusk - Mobility - Mejora de rango 4',
        'Mollusk Walker Upgrade - Torque - Tier 4': 'Mejora del Walker Mollusk - Capacidad energética - Mejora de rango 4',
        'Mollusk Walker Upgrade - Water - Tier 4': 'Mejora del Walker Mollusk - Depósito de agua - Mejora de rango 4',
        'Panda Walker Body': 'Cuerpo de Walker Panda',
        'Armored Panda Walker Legs (1 of 2)': 'Armored Panda Walker Legs (1 of 2)',
        'Heavy Panda Walker Legs (1 of 2)': 'Heavy Panda Walker Legs (1 of 2)',
        'Panda Walker Legs (1 of 2)': 'Panda Walker Legs (1 of 2)',
        'Panda Walker Heavy Wings (1 of 2)': 'Panda Walker Heavy Wings (1 of 2)',
        'Panda Walker Large Wings (1 of 2)': 'Panda Walker Large Wings (1 of 2)',
        'Panda Walker Medium Wings (1 of 2)': 'Panda Walker Medium Wings (1 of 2)',
        'Panda Walker Raider Wings (1 of 2)': 'Panda Walker Raider Wings (1 of 2)',
        'Panda Walker Rugged Wings (1 of 2)': 'Panda Walker Rugged Wings (1 of 2)',
        'Panda Walker Skirmish Wings (1 of 2)': 'Panda Walker Skirmish Wings (1 of 2)',
        'Panda Walker Small Wings (1 of 2)': 'Panda Walker Small Wings (1 of 2)',
        'Panda Walker Wings (1 of 2)': 'Panda Walker Wings (1 of 2)',
        'Panda Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Panda - Capacidad de carga - Mejora de rango 2',
        'Panda Walker Upgrade - Durability - Tier 2': 'Mejora del walker Panda - Durabilidad - Mejora de rango 2',
        'Panda Walker Upgrade - Gear - Tier 2': 'Mejora del walker Panda - Almacenamiento de mecanismos - Mejora de rango 2',
        'Panda Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Panda - Mobility - Mejora de rango 2',
        'Panda Walker Upgrade - Torque - Tier 2': 'Mejora del walker Panda - Capacidad energética - Mejora de rango 2',
        'Panda Walker Upgrade - Water - Tier 2': 'Mejora del walker Panda - Depósito de agua - Mejora de rango 2',
        'Panda Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Panda - Capacidad de carga - Mejora de rango 3',
        'Panda Walker Upgrade - Durability - Tier 3': 'Mejora del walker Panda - Durabilidad - Mejora de rango 3',
        'Panda Walker Upgrade - Gear - Tier 3': 'Mejora del walker Panda - Almacenamiento de mecanismos - Mejora de rango 3',
        'Panda Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Panda - Mobility - Mejora de rango 3',
        'Panda Walker Upgrade - Torque - Tier 3': 'Mejora del walker Panda - Capacidad energética - Mejora de rango 3',
        'Panda Walker Upgrade - Water - Tier 3': 'Mejora del walker Panda - Depósito de agua - Mejora de rango 3',
        'Panda Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Panda - Capacidad de carga - Mejora de rango 4',
        'Panda Walker Upgrade - Durability - Tier 4': 'Mejora del walker Panda - Durabilidad - Mejora de rango 4',
        'Panda Walker Upgrade - Gear - Tier 4': 'Mejora del walker Panda - Almacenamiento de mecanismos - Mejora de rango 4',
        'Panda Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Panda - Mobility - Mejora de rango 4',
        'Panda Walker Upgrade - Torque - Tier 4': 'Mejora del walker Panda - Capacidad energética - Mejora de rango 4',
        'Panda Walker Upgrade - Water - Tier 4': 'Mejora del walker Panda - Depósito de agua - Mejora de rango 4',
        'Proxy Walker Body': 'Cuerpo de Walker de ocupación',
        'Armored Proxy Walker Legs (1 of 2)': 'Patas blindadas del Walker de ocupación (1 de 2)',
        'Heavy Proxy Walker Legs (1 of 2)': 'Patas pesadas de Walker de ocupación (1 de 2)',
        'Proxy Walker Legs (1 of 2)': 'Patas de Walker de ocupación (1 de 2)',
        'Schmetterling Walker Body': 'Cuerpo de Walker Schmetterling',
        'Armored Schmetterling Walker Legs (1 of 2)': 'Patas blindadas de Walker Schmetterling (1 de 2)',
        'Heavy Schmetterling Walker Legs (1 of 2)': 'Patas pesadas del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Legs (1 of 2)': 'Patas del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Heavy Wings (1 of 2)': 'Schmetterling Walker Heavy Wings (1 of 2)',
        'Schmetterling Walker Large Wings (1 of 2)': 'Alas grandes del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Medium Wings (1 of 2)': 'Alas medianas del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Raider Wings (1 of 2)': 'Schmetterling Walker Raider Wings (1 of 2)',
        'Schmetterling Walker Rugged Wings (1 of 2)': 'Schmetterling Walker Rugged Wings (1 of 2)',
        'Schmetterling Walker Skirmish Wings (1 of 2)': 'Schmetterling Walker Skirmish Wings (1 of 2)',
        'Schmetterling Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Wings (1 of 2)': 'Alas del Walker Schmetterling (1 de 2)',
        'Schmetterling Walker Upgrade - Cargo - Tier 1': 'Mejora del walker Schmetterling - Capacidad de carga - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Durability - Tier 1': 'Mejora del walker Schmetterling - Durabilidad - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Gear - Tier 1': 'Mejora del walker Schmetterling - Almacenamiento de mecanismos - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Mobility - Tier 1': 'Mejora del walker Schmetterling - Mobility - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Torque - Tier 1': 'Mejora del walker Schmetterling - Capacidad energética - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Water - Tier 1': 'Mejora del walker Schmetterling - Depósito de agua - Mejora de rango 1',
        'Schmetterling Walker Upgrade - Cargo - Tier 2': 'Mejora del walker Schmetterling - Capacidad de carga - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Durability - Tier 2': 'Mejora del walker Schmetterling - Durabilidad - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Gear - Tier 2': 'Mejora del walker Schmetterling - Almacenamiento de mecanismos - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Mobility - Tier 2': 'Mejora del walker Schmetterling - Mobility - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Torque - Tier 2': 'Mejora del walker Schmetterling - Capacidad energética - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Water - Tier 2': 'Mejora del walker Schmetterling - Depósito de agua - Mejora de rango 2',
        'Schmetterling Walker Upgrade - Cargo - Tier 3': 'Mejora del walker Schmetterling - Capacidad de carga - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Durability - Tier 3': 'Mejora del walker Schmetterling - Durabilidad - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Gear - Tier 3': 'Mejora del walker Schmetterling - Almacenamiento de mecanismos - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Mobility - Tier 3': 'Mejora del walker Schmetterling - Mobilidad - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Torque - Tier 3': 'Mejora del walker Schmetterling - Capacidad energética - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Water - Tier 3': 'Mejora del walker Schmetterling - Depósito de agua - Mejora de rango 3',
        'Schmetterling Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Schmetterling - Capacidad de carga - Mejora de rango 4',
        'Schmetterling Walker Upgrade - Durability - Tier 4': 'Mejora del walker Schmetterling - Durabilidad - Mejora de rango 4',
        'Schmetterling Walker Upgrade - Gear - Tier 4': 'Mejora del walker Schmetterling - Almacenamiento de mecanismos - Mejora de rango 4',
        'Schmetterling Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Schmetterling - Mobilidad - Mejora de rango 4',
        'Schmetterling Walker Upgrade - Torque - Tier 4': 'Mejora del walker Schmetterling - Capacidad energética - Mejora de rango 4',
        'Schmetterling Walker Upgrade - Water - Tier 4': 'Mejora del walker Schmetterling - Depósito de agua - Mejora de rango 4',
        'Nomad Spider Walker Body': 'Cuerpo de Walker Nomad Spider',
        'Spider Walker With Ballista': 'Cuerpo de Walker Araña con ballesta',
        'Armored Spider Walker Legs (1 of 2)': 'Patas blindadas de Walker Spider (1 de 2)',
        'Spider Walker Legs (1 of 2)': 'Patas de Walker Spider (1 de 2)',
        'Spider Walker Upgrade - Cargo - Tier 1': 'Mejora de walker Spider - Capacidad de carga - Mejora de rango 1',
        'Spider Walker Upgrade - Durability - Tier 1': 'Mejora de walker Spider - Durabilidad - Mejora de rango 1',
        'Spider Walker Upgrade - Gear - Tier 1': 'Mejora de walker Spider - Almacenamiento de mecanismos - Mejora de rango 1',
        'Spider Walker Upgrade - Mobility - Tier 1': 'Mejora de walker Spider - Mobility - Mejora de rango 1',
        'Spider Walker Upgrade - Water - Tier 1': 'Mejora de walker Spider - Depósito de agua - Mejora de rango 1',
        'Spider Walker Upgrade - Cargo - Tier 2': 'Mejora de walker Spider - Capacidad de carga - Mejora de rango 2',
        'Spider Walker Upgrade - Durability - Tier 2': 'Mejora de walker Spider - Durabilidad - Mejora de rango 2',
        'Spider Walker Upgrade - Gear - Tier 2': 'Mejora de walker Spider - Almacenamiento de mecanismos - Mejora de rango 2',
        'Spider Walker Upgrade - Mobility - Tier 2': 'Mejora de walker Spider - Mobility - Mejora de rango 2',
        'Spider Walker Upgrade - Torque - Tier 2': 'Spider Walker Upgrade - Torque - Tier 2',
        'Spider Walker Upgrade - Water - Tier 2': 'Mejora de walker Spider - Depósito de agua - Mejora de rango 2',
        'Spider Walker Upgrade - Cargo - Tier 3': 'Mejora de walker Spider - Capacidad de carga - Mejora de rango 3',
        'Spider Walker Upgrade - Durability - Tier 3': 'Mejora de walker Spider - Durabilidad - Mejora de rango 3',
        'Spider Walker Upgrade - Gear - Tier 3': 'Mejora de walker Spider - Almacenamiento de mecanismos - Mejora de rango 3',
        'Spider Walker Upgrade - Mobility - Tier 3': 'Mejora de walker Spider - Mobility - Mejora de rango 3',
        'Spider Walker Upgrade - Torque - Tier 3': 'Spider Walker Upgrade - Torque - Tier 3',
        'Spider Walker Upgrade - Water - Tier 3': 'Mejora de walker Spider - Depósito de agua - Mejora de rango 3',
        'Spider Walker Upgrade - Cargo - Tier 4': 'Mejora de walker Spider - Capacidad de carga - Mejora de rango 4',
        'Spider Walker Upgrade - Durability - Tier 4': 'Mejora de walker Spider - Durabilidad - Mejora de rango 4',
        'Spider Walker Upgrade - Gear - Tier 4': 'Mejora de walker Spider - Almacenamiento de mecanismos - Mejora de rango 4',
        'Spider Walker Upgrade - Mobility - Tier 4': 'Mejora de walker Spider - Mobility - Mejora de rango 4',
        'Spider Walker Upgrade - Torque - Tier 4': 'Spider Walker Upgrade - Torque - Tier 4',
        'Spider Walker Upgrade - Water - Tier 4': 'Mejora de walker Spider - Depósito de agua - Mejora de rango 4',
        'Stiletto Walker Body': 'Cuerpo de Walker Stiletto',
        'Stiletto Walker Legs (1 of 2)': 'Patas de Walker Stiletto (1 de 2)',
        'Stiletto Walker Legs Armored': 'Patas blindadas de Walker Stiletto',
        'Stiletto Walker Heavy Wings (1 of 2)': 'Stiletto Walker Heavy Wings (1 of 2)',
        'Stiletto Walker Medium Wings (1 of 2)': 'Alas medianas de Walker Stiletto (1 de 2)',
        'Stiletto Walker Raider Wings (1 of 2)': 'Stiletto Walker Raider Wings (1 of 2)',
        'Stiletto Walker Rugged Wings (1 of 2)': 'Stiletto Walker Rugged Wings (1 of 2)',
        'Stiletto Walker Skirmish Wings (1 of 2)': 'Stiletto Walker Skirmish Wings (1 of 2)',
        'Stiletto Walker Small Wings (1 of 2)': 'Alas pequeñas de Walker Stiletto (1 de 2)',
        'Stiletto Walker Wings (1 of 2)': 'Alas de Walker Stiletto (1 de 2)',
        'Stiletto Walker Upgrade - Cargo - Tier 2': 'Mejora de walker Stiletto - Capacidad de carga - Mejora de rango 2',
        'Stiletto Walker Upgrade - Durability - Tier 2': 'Mejora de walker Stiletto - Durabilidad - Mejora de rango 2',
        'Stiletto Walker Upgrade - Gear - Tier 2': 'Mejora de walker Stiletto - Almacenamiento de mecanismos - Mejora de rango 2',
        'Stiletto Walker Upgrade - Mobility - Tier 2': 'Mejora de walker Stiletto - Mobility - Mejora de rango 2',
        'Stiletto Walker Upgrade - Torque - Tier 2': 'Mejora de walker Stiletto - Capacidad energética - Mejora de rango 2',
        'Stiletto Walker Upgrade - Water - Tier 2': 'Mejora de walker Stiletto - Depósito de agua - Mejora de rango 2',
        'Stiletto Walker Upgrade - Cargo - Tier 3': 'Mejora de walker Stiletto - Capacidad de carga - Mejora de rango 3',
        'Stiletto Walker Upgrade - Durability - Tier 3': 'Mejora de walker Stiletto - Durabilidad - Mejora de rango 3',
        'Stiletto Walker Upgrade - Gear - Tier 3': 'Mejora de walker Stiletto - Almacenamiento de mecanismos - Mejora de rango 3',
        'Stiletto Walker Upgrade - Mobility - Tier 3': 'Mejora de walker Stiletto - Mobility - Mejora de rango 3',
        'Stiletto Walker Upgrade - Torque - Tier 3': 'Mejora de walker Stiletto - Capacidad energética - Mejora de rango 3',
        'Stiletto Walker Upgrade - Water - Tier 3': 'Mejora de walker Stiletto - Depósito de agua - Mejora de rango 3',
        'Stiletto Walker Upgrade - Cargo - Tier 4': 'Mejora de walker Stiletto - Capacidad de carga - Mejora de rango 4',
        'Stiletto Walker Upgrade - Durability - Tier 4': 'Mejora de walker Stiletto - Durabilidad - Mejora de rango 4',
        'Stiletto Walker Upgrade - Gear - Tier 4': 'Mejora de walker Stiletto - Almacenamiento de mecanismos - Mejora de rango 4',
        'Stiletto Walker Upgrade - Mobility - Tier 4': 'Mejora de walker Stiletto - Mobility - Mejora de rango 4',
        'Stiletto Walker Upgrade - Torque - Tier 4': 'Mejora de walker Stiletto - Capacidad energética - Mejora de rango 4',
        'Stiletto Walker Upgrade - Water - Tier 4': 'Mejora de walker Stiletto - Depósito de agua - Mejora de rango 4',
        'Titan Walker Body': 'Cuerpo de Walker Titan',
        'Armored Titan Walker Legs (1 of 2)': 'Patas blindadas de Walker Titan (1 de 2)',
        'Heavy Titan Walker Legs (1 of 2)': 'Patas pesadas de Walker Titan (1 de 2)',
        'Titan Walker Legs (1 of 2)': 'Patas de Walker Titan (1 de 2)',
        'Titan Walker Heavy Wings (1 of 2)': 'Titan Walker Heavy Wings (1 of 2)',
        'Titan Walker Large Wings (1 of 2)': 'Alas grandes de Walker Titan (1 de 2)',
        'Titan Walker Medium Wings (1 of 2)': 'Alas medianas de Walker Titan (1 de 2)',
        'Titan Walker Raider Wings (1 of 2)': 'Titan Walker Raider Wings (1 of 2)',
        'Titan Walker Rugged Wings (1 of 2)': 'Titan Walker Rugged Wings (1 of 2)',
        'Titan Walker Skirmish Wings (1 of 2)': 'Titan Walker Skirmish Wings (1 of 2)',
        'Titan Walker Small Wings (1 of 2)': 'Alas pequeñas de Walker Titan (1 de 2)',
        'Titan Walker Wings (1 of 2)': 'Alas del Walker Titan (1 de 2)',
        'Titan Walker Upgrade - Cargo - Tier 2': 'Mejora de walker Titan - Capacidad de carga - Mejora de rango 2',
        'Titan Walker Upgrade - Durability - Tier 2': 'Mejora de walker Titan - Durabilidad - Mejora de rango 2',
        'Titan Walker Upgrade - Gear - Tier 2': 'Mejora de walker Titan - Almacenamiento de mecanismos - Mejora de rango 2',
        'Titan Walker Upgrade - Mobility - Tier 2': 'Mejora de walker Titan - Mobility - Mejora de rango 2',
        'Titan Walker Upgrade - Torque - Tier 2': 'Mejora de walker Titan - Capacidad energética - Mejora de rango 2',
        'Titan Walker Upgrade - Water - Tier 2': 'Mejora de walker Titan - Depósito de agua - Mejora de rango 2',
        'Titan Walker Upgrade - Cargo - Tier 3': 'Mejora de walker Titan - Capacidad de carga - Mejora de rango 3',
        'Titan Walker Upgrade - Durability - Tier 3': 'Mejora de walker Titan - Durabilidad - Mejora de rango 3',
        'Titan Walker Upgrade - Gear - Tier 3': 'Mejora de walker Titan - Almacenamiento de mecanismos - Mejora de rango 3',
        'Titan Walker Upgrade - Mobility - Tier 3': 'Mejora de walker Titan - Mobility - Mejora de rango 3',
        'Titan Walker Upgrade - Torque - Tier 3': 'Mejora de walker Titan - Capacidad energética - Mejora de rango 3',
        'Titan Walker Upgrade - Water - Tier 3': 'Mejora de walker Titan - Depósito de agua - Mejora de rango 3',
        'Titan Walker Upgrade - Cargo - Tier 4': 'Mejora de walker Titan - Capacidad de carga - Mejora de rango 4',
        'Titan Walker Upgrade - Durability - Tier 4': 'Mejora de walker Titan - Durabilidad - Mejora de rango 4',
        'Titan Walker Upgrade - Gear - Tier 4': 'Mejora de walker Titan - Almacenamiento de mecanismos - Mejora de rango 4',
        'Titan Walker Upgrade - Mobility - Tier 4': 'Mejora de walker Titan - Mobility - Mejora de rango 4',
        'Titan Walker Upgrade - Torque - Tier 4': 'Mejora de walker Titan - Capacidad energética - Mejora de rango 4',
        'Titan Walker Upgrade - Water - Tier 4': 'Mejora de walker Titan - Depósito de agua - Mejora de rango 4',
        'Toboggan Walker Body': 'Cuerpo de Walker Toboggan',
        'Armored Toboggan Walker Legs (1 of 2)': 'Patas blindadas de Walker Toboggan (1 de 2)',
        'Heavy Toboggan Walker Legs (1 of 2)': 'Patas pesadas del Walker Toboggan (1 de 2)',
        'Toboggan Walker Legs (1 of 2)': 'Patas del Walker Toboggan (1 de 2)',
        'Toboggan Walker Heavy Wings (1 of 2)': 'Toboggan Walker Heavy Wings (1 of 2)',
        'Toboggan Walker Large Wings (1 of 2)': 'Alas grandes del Walker Toboggan (1 de 2)',
        'Toboggan Walker Medium Wings (1 of 2)': 'Alas medianas del Walker Toboggan (1 de 2)',
        'Toboggan Walker Raider Wings (1 of 2)': 'Toboggan Walker Raider Wings (1 of 2)',
        'Toboggan Walker Rugged Wings (1 of 2)': 'Toboggan Walker Rugged Wings (1 of 2)',
        'Toboggan Walker Skirmish Wings (1 of 2)': 'Toboggan Walker Skirmish Wings (1 of 2)',
        'Toboggan Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Toboggan (1 de 2)',
        'Toboggan Walker Wings (1 of 2)': 'Alas del Walker Toboggan (1 de 2)',
        'Toboggan Walker Upgrade - Cargo - Tier 2': 'Mejora de walker Toboggan - Capacidad de carga - Mejora de rango 2',
        'Toboggan Walker Upgrade - Durability - Tier 2': 'Mejora de walker Toboggan - Durabilidad - Mejora de rango 2',
        'Toboggan Walker Upgrade - Gear - Tier 2': 'Mejora de walker Toboggan - Almacenamiento de mecanismos - Mejora de rango 2',
        'Toboggan Walker Upgrade - Mobility - Tier 2': 'Mejora de walker Toboggan - Mobility - Mejora de rango 2',
        'Toboggan Walker Upgrade - Torque - Tier 2': 'Mejora de walker Toboggan - Capacidad energética - Mejora de rango 2',
        'Toboggan Walker Upgrade - Water - Tier 2': 'Mejora de walker Toboggan - Depósito de agua - Mejora de rango 2',
        'Toboggan Walker Upgrade - Cargo - Tier 3': 'Mejora de walker Toboggan - Capacidad de carga - Mejora de rango 3',
        'Toboggan Walker Upgrade - Durability - Tier 3': 'Mejora de walker Toboggan - Durabilidad - Mejora de rango 3',
        'Toboggan Walker Upgrade - Gear - Tier 3': 'Mejora de walker Toboggan - Almacenamiento de mecanismos - Mejora de rango 3',
        'Toboggan Walker Upgrade - Mobility - Tier 3': 'Mejora de walker Toboggan - Mobility - Mejora de rango 3',
        'Toboggan Walker Upgrade - Torque - Tier 3': 'Mejora de walker Toboggan - Capacidad energética - Mejora de rango 3',
        'Toboggan Walker Upgrade - Water - Tier 3': 'Mejora de walker Toboggan - Depósito de agua - Mejora de rango 3',
        'Toboggan Walker Upgrade - Cargo - Tier 4': 'Mejora de walker Toboggan - Capacidad de carga - Mejora de rango 4',
        'Toboggan Walker Upgrade - Durability - Tier 4': 'Mejora de walker Toboggan - Durabilidad - Mejora de rango 4',
        'Toboggan Walker Upgrade - Gear - Tier 4': 'Mejora de walker Toboggan - Almacenamiento de mecanismos - Mejora de rango 4',
        'Toboggan Walker Upgrade - Mobility - Tier 4': 'Mejora de walker Toboggan - Mobility - Mejora de rango 4',
        'Toboggan Walker Upgrade - Torque - Tier 4': 'Mejora de walker Toboggan - Capacidad energética - Mejora de rango 4',
        'Toboggan Walker Upgrade - Water - Tier 4': 'Mejora de walker Toboggan - Depósito de agua - Mejora de rango 4',
        'Long Sawblade': 'Sierra giratoria grande',
        'Sawblade Tool': 'Hoja de sierra',
        'Steering Levers': 'Timón',
        'Tool Pod': 'Cápsula de herramientas',
        'Walker Climber': 'Trepador de walker',
        'Walker Packing Compartment': 'Walker Packing Compartment',
        'Tusker Walker Body': 'Cuerpo del Walker Tusker',
        'Armored Tusker Walker Legs (1 of 2)': 'Patas blindadas del Walker Tusker (1 de 2)',
        'Heavy Tusker Walker Legs (1 of 2)': 'Patas pesadas del Walker Tusker (1 de 2)',
        'Tusker Walker Legs (1 of 2)': 'Patas del Walker Tusker (1 de 2)',
        'Tusker Walker Heavy Wings (1 of 2)': 'Tusker Walker Heavy Wings (1 of 2)',
        'Tusker Walker Large Wings (1 of 2)': 'Alas grandes del Walker Tusker (1 de 2)',
        'Tusker Walker Medium Wings (1 of 2)': 'Alas medianas del Walker Tusker (1 de 2)',
        'Tusker Walker Raider Wings (1 of 2)': 'Tusker Walker Raider Wings (1 of 2)',
        'Tusker Walker Rugged Wings (1 of 2)': 'Tusker Walker Rugged Wings (1 of 2)',
        'Tusker Walker Skirmish Wings (1 of 2)': 'Tusker Walker Skirmish Wings (1 of 2)',
        'Tusker Walker Small Wings (1 of 2)': 'Alas pequeñas del Walker Tusker (1 de 2)',
        'Tusker Walker Wings (1 of 2)': 'Alas del Walker Tusker (1 de 2)',
        'Tusker Walker Upgrade - Cargo - Tier 2': 'Mejora de walker Tusker - Capacidad de carga - Mejora de rango 2',
        'Tusker Walker Upgrade - Durability - Tier 2': 'Mejora de walker Tusker - Durabilidad - Mejora de rango 2',
        'Tusker Walker Upgrade - Gear - Tier 2': 'Mejora de walker Tusker - Almacenamiento de mecanismos - Mejora de rango 2',
        'Tusker Walker Upgrade - Mobility - Tier 2': 'Mejora de walker Tusker - Mobility - Mejora de rango 2',
        'Tusker Walker Upgrade - Torque - Tier 2': 'Mejora de walker Tusker - Capacidad energética - Mejora de rango 2',
        'Tusker Walker Upgrade - Water - Tier 2': 'Mejora de walker Tusker - Depósito de agua - Mejora de rango 2',
        'Tusker Walker Upgrade - Cargo - Tier 3': 'Mejora de walker Tusker - Capacidad de carga - Mejora de rango 3',
        'Tusker Walker Upgrade - Durability - Tier 3': 'Mejora de walker Tusker - Durabilidad - Mejora de rango 3',
        'Tusker Walker Upgrade - Gear - Tier 3': 'Mejora de walker Tusker - Almacenamiento de mecanismos - Mejora de rango 3',
        'Tusker Walker Upgrade - Mobility - Tier 3': 'Mejora de walker Tusker - Mobility - Mejora de rango 3',
        'Tusker Walker Upgrade - Torque - Tier 3': 'Mejora de walker Tusker - Capacidad energética - Mejora de rango 3',
        'Tusker Walker Upgrade - Water - Tier 3': 'Mejora de walker Tusker - Depósito de agua - Mejora de rango 3',
        'Tusker Walker Upgrade - Cargo - Tier 4': 'Mejora del walker Tusker - Capacidad de carga - Mejora de rango 4',
        'Tusker Walker Upgrade - Durability - Tier 4': 'Mejora del walker Tusker - Durabilidad - Mejora de rango 4',
        'Tusker Walker Upgrade - Gear - Tier 4': 'Mejora del walker Tusker - Almacenamiento de mecanismos - Mejora de rango 4',
        'Tusker Walker Upgrade - Mobility - Tier 4': 'Mejora del walker Tusker - Mobility - Mejora de rango 4',
        'Tusker Walker Upgrade - Torque - Tier 4': 'Mejora del walker Tusker - Capacidad energética - Mejora de rango 4',
        'Tusker Walker Upgrade - Water - Tier 4': 'Mejora del walker Tusker - Depósito de agua - Mejora de rango 4',
        'Silur Walker Body': 'Cuerpo de Walker Silur',
        'Silur Walker Legs (1 of 2)': 'Patas del Walker Silur (1 de 2)',
        'Silur Walker Upgrade - Water - Tier 2': 'Mejora del walker Silur - Depósito de agua - Mejora de rango 2',
        'Silur Walker Upgrade - Torque - Tier 2': 'Mejora del walker Silur - Capacidad energética - Mejora de rango 2',
        'Silur Walker Upgrade - Torque - Tier 3': 'Mejora del walker Silur - Capacidad energética - Mejora de rango 3',
        'Silur Walker Upgrade - Water - Tier 3': 'Mejora del walker Silur - Depósito de agua - Mejora de rango 3',
        'Silur Walker Upgrade - Torque - Tier 4': 'Mejora del walker Silur - Capacidad energética - Mejora de rango 4',
        'Silur Walker Upgrade - Water - Tier 4': 'Mejora del walker Silur - Depósito de agua - Mejora de rango 4',
        'Silur Walker Legs Armored': 'Patas blindadas del Walker Silur (1 de 2)',
        'Silur Walker Legs Heavy': 'Patas Pesadas del Walker Silur (1 de 2)',
        'Battle Fan': 'Battle Fan',
        'Hardened Hellfire Bolt': 'Hardened Hellfire Bolt',
        'Base Maintenance Chest': 'Base Maintenance Chest',
        'Hercul Walker Body': 'Cuerpo Walker Hercul',
        'Hercul Walker Legs (1 of 2)': 'Patas de Walker Hercul (1 de 2)',
        'Hercul Walker Wings': 'Alas del Walker Hercul (1 de 2)',
        'Hercul Walker Legs Armored': 'Patas blindadas de Walker Hercul (1 de 2)',
        'Hercul Walker Wings Heavy': 'Hercul Walker Wings Heavy',
        'Hercul Walker Wings Medium': 'Alas medianas de Walker Hercul (1 de 2)',
        'Hercul Walker Wings Raider': 'Hercul Walker Wings Raider',
        'Hercul Walker Wings Rugged': 'Hercul Walker Wings Rugged',
        'Hercul Walker Wings Skirmish': 'Hercul Walker Wings Skirmish',
        'Hercul Walker Wings Small': 'Alas pequeñas de Walker Hercul (1 de 2)',
        'Hercul Walker Upgrade - Torque - Tier 2': 'Mejora del walker hercul - Capacidad energética - Mejora de rango 2',
        'Hercul Walker Upgrade - Water - Tier 2': 'Mejora del walker hercul - Depósito de agua - Mejora de rango 2',
        'Hercul Walker Upgrade - Torque - Tier 3': 'Mejora del walker hercul - Capacidad energética - Mejora de rango 3',
        'Hercul Walker Upgrade - Water - Tier 3': 'Mejora del walker hercul - Depósito de agua - Mejora de rango 3',
        'Hercul Walker Upgrade - Torque - Tier 4': 'Mejora del walker hercul - Capacidad energética - Mejora de rango 4',
        'Hercul Walker Upgrade - Water - Tier 4': 'Mejora del walker hercul - Depósito de agua - Mejora de rango 4',
        'Balang Walker Body': 'Cuerpo Walker Balang',
        'Balang Walker Legs (1 of 2)': 'Patas del Walker Balang (1 de 2)',
        'Balang Walker Wings': 'Alas del walker balang (1 de 2)',
        'Balang Walker Wings Small': 'Alas pequeñas de Walker Balang (1 de 2)',
        'Balang Walker Upgrade - Torque - Tier 2': 'Mejora del walker Balang - Capacidad energética - Mejora de rango 2',
        'Balang Walker Upgrade - Water - Tier 2': 'Mejora del walker Balang - Depósito de agua - Mejora de rango 2',
        'Balang Walker Upgrade - Torque - Tier 3': 'Mejora del walker Balang - Capacidad energética - Mejora de rango 3',
        'Balang Walker Upgrade - Water - Tier 3': 'Mejora del walker Balang - Depósito de agua - Mejora de rango 3',
        'Balang Walker Upgrade - Torque - Tier 4': 'Mejora del walker Balang - Capacidad energética - Mejora de rango 4',
        'Balang Walker Upgrade - Water - Tier 4': 'Mejora del walker Balang - Depósito de agua - Mejora de rango 4',
        'Large Base Walker Packer': 'Large Base Walker Packer',
        'Small Base Walker Packer': 'Small Base Walker Packer',
        'Poaching Hut': 'Poaching Hut',
        'Giant Wall': 'Giant Wall',
        'Giant Wall Gate': 'Giant Wall Gate',
        'Steering Levers Cage': 'Steering Levers Cage',
        'Compacted Torque Battery': 'Compacted Torque Battery',
        'Net Pouch': 'Net Pouch',
        'Bent Wooden Planks': 'Bent Wooden Planks',
        'Fiery Concoction': 'Fiery Concoction',
        Lightwood: 'Lightwood',
        'Wood Log': 'Wood Log',
        'Worm Sand': 'Worm Sand',
        'Armory Module': 'Módulo de Armamento',
        'Battery Module': 'Módulo de batería',
        'Bullrush Module': 'Módulo de Defensa',
        'Craftsman Module': 'Módulo Artesano',
        'Foraging Module': 'Módulo de recolección',
        'Fireproof Module': 'Fireproof Module',
        'Fortress Module': 'Módulo Fortaleza',
        'Harpoon Protection Module': 'Harpoon Protection Module',
        'Hearth Module': 'Módulo de Hogar',
        'Hull Hardening Module': 'Hull Hardening Module',
        'Lifeforce Module': 'Módulo de Fuerza Vital',
        'Lumberjack Module': 'Módulo Leñador',
        'Merchant Module': 'Módulo Mercantil',
        'Pack Mule Module': 'Recoger Módulo Mula',
        'Sandy Module': 'Módulo Arenoso',
        'Scavenger Module': 'Módulo Carroñero',
        'Torque Module': 'Módulo de energía',
        'Watery Module': 'Módulo acuoso',
        'Weightless Module': 'Módulo Ligero',
        'Giant Wall Packer': 'Giant Wall Packer',
        'Buffalo Walker Legs Armored (1 of 2)': 'Patas Blindadas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Legs Heavy (1 of 2)': 'Patas Pesadas de Walker Búfalo (1 de 2)',
        'Buffalo Walker Upgrade - Cargo - Tier 1': 'Mejora del walker búfalo - Capacidad de carga - Mejora de rango 1',
        'Buffalo Walker Upgrade - Durability - Tier 1': 'Mejora del walker búfalo - Durabilidad - Mejora de rango 1',
        'Buffalo Walker Upgrade - Gear - Tier 1': 'Mejora del walker búfalo - Almacenamiento de mecanismos - Mejora de rango 1',
        'Buffalo Walker Upgrade - Mobility - Tier 1': 'Mejora del walker búfalo - Mobility - Mejora de rango 1',
        'Buffalo Walker Upgrade - Torque - Tier 1': 'Mejora del walker búfalo - Capacidad energética - Mejora de rango 1',
        'Buffalo Walker Upgrade - Water - Tier 1': 'Mejora del walker búfalo - Depósito de agua - Mejora de rango 1',
        'Cobra Walker Upgrade - Water - Tier 1': 'Mejora del walker cobra - Depósito de agua - Mejora de rango 2',
        'Dinghy Walker Upgrade - Cargo - Tier 1': 'Mejora del walker dinghy - Capacidad de carga - Mejora de rango 1',
        'Dinghy Walker Upgrade - Durability - Tier 1': 'Mejora del walker dinghy - Durabilidad - Mejora de rango 1',
        'Dinghy Walker Upgrade - Gear - Tier 1': 'Mejora del walker dinghy - Almacenamiento de mecanismos - Mejora de rango 1',
        'Dinghy Walker Upgrade - Mobility - Tier 1': 'Mejora del walker dinghy - Movilidad - Mejora de rango 1',
        'Dinghy Walker Upgrade - Torque - Tier 1': 'Mejora del walker dinghy - Capacidad energética - Mejora de rango 1',
        'Dinghy Walker Upgrade - Water - Tier 1': 'Mejora del walker dinghy - Depósito de agua - Mejora de rango 1',
        'Hornet Walker Legs Armored (1 of 2)': 'Patas Blindadas de Walker Hornet (1 de 2)',
        'Hornet Walker Legs Heavy (1 of 2)': 'Patas Pesadas de Walker Hornet (1 de 2)',
        'Hornet Walker Upgrade - Cargo - Tier 1': 'Hornet Walker Upgrade - Cargo - Tier 1',
        'Hornet Walker Upgrade - Durability - Tier 1': 'Hornet Walker Upgrade - Durability - Tier 1',
        'Hornet Walker Upgrade - Gear - Tier 1': 'Hornet Walker Upgrade - Gear - Tier 1',
        'Hornet Walker Upgrade - Mobility - Tier 1': 'Hornet Walker Upgrade - Mobility - Tier 1',
        'Hornet Walker Upgrade - Torque - Tier 1': 'Hornet Walker Upgrade - Torque - Tier 1',
        'Hornet Walker Upgrade - Water - Tier 1': 'Hornet Walker Upgrade - Water - Tier 1',
        'Stiletto Walker Legs Armored (1 of 2)': 'Stiletto Walker Legs Armored (1 of 2)',
        'Titan Walker Upgrade - Cargo - Tier 1': 'Titan Walker Upgrade - Cargo - Tier 1',
        'Titan Walker Upgrade - Durability - Tier 1': 'Titan Walker Upgrade - Durability - Tier 1',
        'Titan Walker Upgrade - Gear - Tier 1': 'Titan Walker Upgrade - Gear - Tier 1',
        'Titan Walker Upgrade - Mobility - Tier 1': 'Titan Walker Upgrade - Mobility - Tier 1',
        'Titan Walker Upgrade - Torque - Tier 1': 'Titan Walker Upgrade - Torque - Tier 1',
        'Titan Walker Upgrade - Water - Tier 1': 'Titan Walker Upgrade - Water - Tier 1',
        'Toboggan Walker Upgrade - Cargo - Tier 1': 'Toboggan Walker Upgrade - Cargo - Tier 1',
        'Toboggan Walker Upgrade - Durability - Tier 1': 'Toboggan Walker Upgrade - Durability - Tier 1',
        'Toboggan Walker Upgrade - Gear - Tier 1': 'Toboggan Walker Upgrade - Gear - Tier 1',
        'Toboggan Walker Upgrade - Mobility - Tier 1': 'Toboggan Walker Upgrade - Mobility - Tier 1',
        'Toboggan Walker Upgrade - Torque - Tier 1': 'Toboggan Walker Upgrade - Torque - Tier 1',
        'Toboggan Walker Upgrade - Water - Tier 1': 'Toboggan Walker Upgrade - Water - Tier 1',
        'Tusker Walker Upgrade - Cargo - Tier 1': 'Tusker Walker Upgrade - Cargo - Tier 1',
        'Tusker Walker Upgrade - Durability - Tier 1': 'Tusker Walker Upgrade - Durability - Tier 1',
        'Tusker Walker Upgrade - Gear - Tier 1': 'Tusker Walker Upgrade - Gear - Tier 1',
        'Tusker Walker Upgrade - Mobility - Tier 1': 'Tusker Walker Upgrade - Mobility - Tier 1',
        'Tusker Walker Upgrade - Torque - Tier 1': 'Tusker Walker Upgrade - Torque - Tier 1',
        'Tusker Walker Upgrade - Water - Tier 1': 'Tusker Walker Upgrade - Water - Tier 1',
        'Silur Walker Legs Armored (1 of 2)': 'Silur Walker Legs Armored (1 of 2)',
        'Silur Walker Legs Heavy (1 of 2)': 'Silur Walker Legs Heavy (1 of 2)',
        'Hercul Walker Wings (1 of 2)': 'Hercul Walker Wings (1 of 2)',
        'Hercul Walker Legs Armored (1 of 2)': 'Hercul Walker Legs Armored (1 of 2)',
        'Hercul Walker Wings Heavy (1 of 2)': 'Hercul Walker Wings Heavy (1 of 2)',
        'Hercul Walker Wings Medium (1 of 2)': 'Hercul Walker Wings Medium (1 of 2)',
        'Hercul Walker Wings Raider (1 of 2)': 'Hercul Walker Wings Raider (1 of 2)',
        'Hercul Walker Wings Rugged (1 of 2)': 'Hercul Walker Wings Rugged (1 of 2)',
        'Hercul Walker Wings Skirmish (1 of 2)': 'Hercul Walker Wings Skirmish (1 of 2)',
        'Hercul Walker Wings Small (1 of 2)': 'Hercul Walker Wings Small (1 of 2)',
        'Balang Walker Wings (1 of 2)': 'Balang Walker Wings (1 of 2)',
        'Balang Walker Wings Small (1 of 2)': 'Balang Walker Wings Small (1 of 2)',
        'Raptor Sky Walker Body': 'Raptor Sky Walker Body',
        'Raptor Sky Walker Legs (1 of 2)': 'Raptor Sky Walker Legs (1 of 2)',
        'Raptor Sky Walker Wings (1 of 2)': 'Raptor Sky Walker Wings (1 of 2)',
        'Raptor Walker Upgrade - Cargo - Tier 1': 'Raptor Walker Upgrade - Cargo - Tier 1',
        'Raptor Walker Upgrade - Durability - Tier 1': 'Raptor Walker Upgrade - Durability - Tier 1',
        'Raptor Walker Upgrade - Gear - Tier 1': 'Raptor Walker Upgrade - Gear - Tier 1',
        'Raptor Walker Upgrade - Torque - Tier 1': 'Raptor Walker Upgrade - Torque - Tier 1',
        'Raptor Walker Upgrade - Water - Tier 1': 'Raptor Walker Upgrade - Water - Tier 1',
        'Raptor Walker Upgrade - Cargo - Tier 2': 'Raptor Walker Upgrade - Cargo - Tier 2',
        'Raptor Walker Upgrade - Durability - Tier 2': 'Raptor Walker Upgrade - Durability - Tier 2',
        'Raptor Walker Upgrade - Gear - Tier 2': 'Raptor Walker Upgrade - Gear - Tier 2',
        'Raptor Walker Upgrade - Torque - Tier 2': 'Raptor Walker Upgrade - Torque - Tier 2',
        'Raptor Walker Upgrade - Water - Tier 2': 'Raptor Walker Upgrade - Water - Tier 2',
        'Raptor Walker Upgrade - Cargo - Tier 3': 'Raptor Walker Upgrade - Cargo - Tier 3',
        'Raptor Walker Upgrade - Durability - Tier 3': 'Raptor Walker Upgrade - Durability - Tier 3',
        'Raptor Walker Upgrade - Gear - Tier 3': 'Raptor Walker Upgrade - Gear - Tier 3',
        'Raptor Walker Upgrade - Torque - Tier 3': 'Raptor Walker Upgrade - Torque - Tier 3',
        'Raptor Walker Upgrade - Water - Tier 3': 'Raptor Walker Upgrade - Water - Tier 3',
        'Raptor Walker Upgrade - Cargo - Tier 4': 'Raptor Walker Upgrade - Cargo - Tier 4',
        'Raptor Walker Upgrade - Durability - Tier 4': 'Raptor Walker Upgrade - Durability - Tier 4',
        'Raptor Walker Upgrade - Gear - Tier 4': 'Raptor Walker Upgrade - Gear - Tier 4',
        'Raptor Walker Upgrade - Torque - Tier 4': 'Raptor Walker Upgrade - Torque - Tier 4',
        'Raptor Walker Upgrade - Water - Tier 4': 'Raptor Walker Upgrade - Water - Tier 4'
    }
};
export default all;