let es = {
  translations: {
    Crafting: "Crafteo",
    Clan: "Clan",
    Profile: "Perfil",
    "Clan List": "Listado de clanes",
    Members: "Miembros",
    "Walker List": "Listado de walkers",
    "Resources maps": "Mapas de recursos",
    Diplomacy: "Diplomacia",
    Trades: "Intercambios",
    "Auctions timers": "Temporizadores de subastas",
    "Other info": "Otra info",
    "Github project": "Projecto en Github",
    "This website are utilities related to the game Last Oasis but is not affiliated with":
      "Este sitio web son utilidades relacionadas con el juego Last Oasis pero no está afiliado a",
    "This website uses cookies to enhance the user experience.":
      "Este sitio web utiliza cookies para mejorar la experiencia del usuario.",
    "Login with discord": "Conectar con discord",
    Crafter: "Crafter",
    "Here you can see the materials needed to build each thing you need and with the amount you need as if it were a shopping list. It is in English and Spanish":
      "Aquí puedes ver los materiales necesarios para construir cada cosa que necesites y con la cantidad que necesites como si fuera una lista de la compra. Está en inglés y en español",
    "See how much time is left to finish the auctions of the maps you want easily":
      "Mira cuánto tiempo queda para terminar las subastas de los mapas que quieras fácilmente",
    "Trading system": "Sistema de intercambio",
    "You can create offers or search for them easily from here, you don't need to be on 20 discord servers looking for who to exchange with":
      "Puedes crear ofertas o buscarlas fácilmente desde aquí, no necesitas estar en 20 servidores de discord buscando con quien intercambiar",
    "Check when your walkers were last used and who used them in a simple and quick way. I have created a discord bot that apart from giving other functions allows you to control the walkers log in an easier way":
      "Comprueba cuándo se usaron los walkers por última vez y quién los usó de forma sencilla y rápida. He creado un bot de discord que además de dar otras funciones te permite controlar el registro de walkers de una manera más fácil",
    "Control the clan": "Controla el clan",
    "Use this section to control your clan, make alliances or send wars and to easily show it to your clan members.":
      "Usa esta sección para controlar tu clan, hacer alianzas o enviar guerras y mostrarlo fácilmente a los miembros de tu clan.",
    "Create and edit maps to add resources or strategic points.":
      "Crea y edita mapas para añadir recursos o puntos estratégicos.",
    "Your details": "Tus dattos",
    "Discord Tag": "Discord Tag",
    "Nick in Game": "Nick en el juego",
    "Not defined": "No definido",
    "No Clan": "Sin clan",
    "Delete user": "Borrar usuario",
    "Are you sure?": "¿Estás seguro?",
    "This option is not reversible, your user and all his data will be deleted.":
      "Esta opción no es reversible, su usuario y todos sus datos serán eliminados.",
    Cancel: "Cancelar",
    "Add name in the game": "Añade tu nombre en el juego",
    "Your name in Last Oasis": "Tu nombre en Last Oasis",
    Add: "Añadir",
    "Join a clan": "Unirse a un clan",
    "Clan Name": "Nombre del clan",
    "Flag Color": "Color de la bandera",
    "(Optional)": "(Opcional)",
    "Create a clan": "Crear el clan",
    "Manage Clan": "Controlar el clan",
    "Leave clan": "Salirse del clan",
    "Error when connecting to the API": "Error al conectarse con la API",
    "This user cannot be found": "Este usuario no pudo ser encontrado",
    "You do not have permission to access this page":
      "No tienes permiso para acceder a esta página",
    "Change language": "Cambiar idioma",
    Spanish: "Español",
    English: "Ingles",
    "Member List": "Listado de miembros",
    Kick: "Expulsar",
    "List of requests": "Listado de solicitudes",
    Accept: "Aceptar",
    Reject: "Rechazar",
    "There are no pending requests": "No hay solicitudes pendientes",
    "Loading the list of requests to enter the clan":
      "Cargando la lista de solicitudes para entrar en el clan",
    "Transfer Clan": "Transferir el clan",
    "This option is not reversible, so be careful who you pass it on to in the leadership of the clan":
      "Esta opción no es reversible, así que ten cuidado a quién eliges como lider del clan.",
    "New leader:": "Nuevo lider:",
    "Change leader": "Cambiar lider",
    Delete: "Borrar",
    "Delete Clan": "Borrar Clan",
    "By deleting the clan you will delete all the data linked to it, be careful because this option is not reversible":
      "Borrando el clan se borrarán todos los datos vinculados a él, ten cuidado porque esta opción no es reversible",
    Menu: "Menú",
    "Total materials": "Total de materiales",
    "List of all necessary materials by":
      "Lista de todos los materiales necesarios por",
    "Download Totals": "Descargar totales",
    "Application to enter the clan sent":
      "La solicitud para entrar en el clan fue enviada",
    Leader: "Lider",
    "Discord Invite Link": "Enlace para discord",
    Actions: "Acciones",
    "Send request": "Enviar solicitud",
    "Walker ID": "ID del Walker",
    "You don't have access here, try to log in again":
      "No tienes acceso aquí, intenta entrar de nuevo.",
    "Error when kicking a member": "Error al expulsar al miembro",
    "Error when add member": "Error añadir el nuevo miembro",
    "Error when reject member": "Error al rechazar la solicitud",
    "Clan deleted correctly": "El clan se ha borrado correctamente",
    "Error when delete clan": "Error al borrar el clan",
    "Error when change owner of clan": "Error al cambiar de lider del clan",
    Search: "Buscar",
    Clean: "Limpiar",
    Owner: "Dueño",
    "Last User": "Último usuario",
    "Last Use": "Último uso",
    "You need to have a clan to access this section":
      "Necesitas estar en un clan para acceder a esta sección",
    "For the walkers to appear it is necessary to link the discord server with the clan, only users with administration power can add the discord server.":
      "Para que aparezcan los walkers es necesario vincular el servidor de discord con el clan, sólo los usuarios que son admins pueden agregar el servidor de discord.",
    "Discord ID": "ID de Discord",
    "Link discord server": "Vincular servidor de discord",
    "Discord Bot": "Bot de Discord",
    "You need to add the bot to your discord to compile the list of walkers from the log, but it also has other functions like checking what you need to do the different items":
      "Necesitas añadir el bot a tu discord para leer la lista de walkers desde el log, pero también tiene otras funciones como comprobar lo que necesitas para hacer los diferentes objetos",
    "Map List": "Lista de mapas",
    "Map Name": "Nombre del mapa",
    "New Map": "Nuevo mapa",
    "Date of burning": "Fecha del quemado",
    "Map Type": "Tipo de mapa",
    "Create new map": "Crear un nuevo mapa",
    "Back to the list of maps": "Volver a la lista de mapas",
    Type: "Tipo",
    Coordinate: "Coordenada",
    "Not the same as in the game": "No es la misma que en el juego",
    "Quality:": "Calidad:",
    "Create resource": "Crear recurso",
    "Login again": "Conectate de nuevo",
    "Temporal Marker": "Marca temporal",
    "Published Trades": "Intercambios publicados",
    Supply: "Suministro",
    Demand: "Demanda",
    Resource: "Recurso",
    Region: "Región",
    "Filter trades": "Filtrar",
    "Clean filter": "Limpiar filtro",
    "If you want to publish your own exchange offers you have to be connected":
      "Si quieres publicar tus propios intercambios tienes que estar conectado",
    "Publish an trade": "Publicar un intercambio",
    Quantity: "Cantidad",
    Publish: "Publicar",
    "No trade offers were found with this filter":
      "No se encontraron intercambios con este filtro",
    Allies: "Aliados",
    "NAP or Settlers": "NAP o Colonos",
    War: "Guerra",
    "Create a relationship": "Crear una relación",
    "This data is not saved, if you reload the page it will be deleted":
      "Estos datos no se guardan, si recargas la página se borrarán",
    "Sound Off": "Sonido apagado",
    "Sound On": "Sonido encendido",
    "Show map": "Ver mapa",
    "Delete map": "Borrar mapa",
    "Share map": "Compartir mapa",
    Hours: "Horas",
    "Try again later": "Inténtalo de nuevo más tarde.",
    Minutes: "Minutos",
    Seconds: "Segundos",
    Description: "Descripción",
    Start: "Iniciar",
    Stop: "Parar",
    "Latest updates": "Últimas actualizaciones",
    "Report Bugs": "Reportar fallos",
    "I'd appreciate it if you find a bug and tell me about it on Github or another platform so that I can fix it":
      "Agradecería si encuentras un error y me lo cuentas en Github o en otra plataforma para que pueda arreglarlo.",
    Report: "Reportar",
    "I have also created a discord bot useful to control the walkers and make a list of what is needed to create objects.":
      "También he creado un bot para discord útil para controlar los walkers y hacer una lista de lo que se necesita para crear objetos.",
    "Go to Discord bot": "Ir al bot de Discord",
    "Dm94Dani´s Discord": "El discord de Dm94Dani",
    "Steam Page": "Página de steam",
    "Official Discord": "Discord Oficial",
    Wiki: "Wiki",
    "Aloe vera": "Aloe vera",
    "Grasa animal": "Grasa animal",
    Manzana: "Manzana",
    Ceniza: "Ceniza",
    "Cera de abejas": "Cera de abejas",
    "Nabo sangriento": "Nabo sangriento",
    "Adhesivo de hueso": "Adhesivo de hueso",
    "Astilla de hueso": "Astilla de hueso",
    "Carne de cactus": "Carne de cactus",
    Enea: "Enea",
    "Esquirla de cerámica": "Esquirla de cerámica",
    Carbón: "Carbón",
    "Escama de quitina": "Escama de quitina",
    Arcilla: "Arcilla",
    "Agua contaminada": "Agua contaminada",
    Maiz: "Maiz",
    Algodón: "Algodón",
    Ceresina: "Ceresina",
    Pluma: "Pluma",
    Fibra: "Fibra",
    "Tejido de Fibra": "Tejido de Fibra",
    Fragmento: "Fragmento",
    "Vial de cristal": "Vial de cristal",
    Esconderse: "Esconderse",
    "Fruto de cactus enorme": "Fruto de cactus enorme",
    Insectos: "Insectos",
    "Lingote de hierro": "Lingote de hierro",
    "Material de hierro": "Material de hierro",
    Lava: "Lava",
    "Combustible líquido": "Combustible líquido",
    "Carne de champiñon": "Carne de champiñon",
    "Mineral de Nibiru": "Mineral de Nibiru",
    "Tela Nomad": "Tela Nomad",
    Obsidiana: "Obsidiana",
    "Hojas de palmera": "Hojas de palmera",
    Perla: "Perla",
    "Agua Purificada": "Agua Purificada",
    "Platano rojo": "Platano rojo",
    "Madera de secuoya roja": "Madera de secuoya roja",
    "Reforzar tablón": "Reforzar tablón",
    Cuerda: "Cuerda",
    "Mantequilla de la tribu rupu": "Mantequilla de la tribu rupu",
    "Piel rupu": "Piel rupu",
    "Vid Rupu": "Vid Rupu",
    "Roca de sal": "Roca de sal",
    Arena: "Arena",
    "Fragmentos hechos añicos": "Fragmentos hechos añicos",
    Piedra: "Piedra",
    Azufre: "Azufre",
    Placa: "Placa",
    Brea: "Brea",
    Baya: "Baya",
    Torque: "Torque",
    Madera: "Madera",
    "Poste de Madera": "Poste de Madera",
    "Escama de gusano": "Escama de gusano",
    "Seda de gusano": "Seda de gusano",
  },
};

export default es;
