let all = {
    translations: {
        'New web update': 'New web update',
        Update: 'Update',
        Crafting: 'Artisanat',
        Clan: 'Clan',
        'User Profile': 'Profil',
        'Clan List': 'Liste des clans',
        Members: 'Membres',
        'Walker List': 'Liste des marcheurs',
        'Resource Maps': 'Cartes des ressources',
        Diplomacy: 'Diplomatie',
        Trades: 'Métiers',
        'Auction Timers': 'Minuteurs d\'enchères',
        About: 'Autres informations',
        'Github project': 'Github project',
        'Light Theme Mode': 'Light Theme Mode',
        Profile: 'Profile',
        'Members List': 'Members List',
        Crafter: 'Crafter',
        'Tech Tree': 'Tech Tree',
        'Quality Calculator': 'Quality Calculator',
        'Walkers Upgrades Cost': 'Walkers Upgrades Cost',
        'Help to translate the website': 'Help to translate the website',
        'This website uses utilities related to the game \'Last Oasis\' but is not affiliated with': 'Ce site web sont des utilitaires liés au jeu Last Oasis mais n\'est pas affilié à',
        'This website uses cookies to enhance the user experience.': 'Ce site web utilise des cookies pour améliorer l\'expérience des utilisateurs.',
        'Login with discord': 'Connexion avec discorde',
        'Connect in demo mode': 'Se connecter en mode démo',
        'Crafting Calculator': 'Crafter',
        'Here you can see and automatically calculate the materials needed to build each item. It is in English and Spanish': 'Vous pouvez voir ici les matériaux nécessaires pour construire chaque chose dont vous avez besoin et avec la quantité nécessaire comme s\'il s\'agissait d\'une liste de courses. Il est en anglais et en espagnol',
        'See how much time is left to finish the auctions of the maps you want easily': 'Voyez combien de temps il reste pour terminer facilement les enchères des cartes que vous souhaitez',
        'Trading System': 'Système d\'échange',
        'You can create offers or search for them easily from here, you don\'t need to be on 20 discord servers looking for who to exchange with': 'Vous pouvez créer des offres ou les rechercher facilement à partir d\'ici, vous n\'avez pas besoin d\'être sur 20 serveurs de discordance pour chercher avec qui échanger',
        'Check when your walkers were last used and who used them in a simple and quick way. I have created a discord bot that apart from giving other functions allows you to control the walkers log in an easier way': 'Vérifiez quand vos déambulateurs ont été utilisés pour la dernière fois et qui les a utilisés de manière simple et rapide. J\'ai créé un robot de discordance qui, en plus d\'offrir d\'autres fonctions, vous permet de contrôler le journal des déambulateurs de manière plus simple',
        'Clan Diplomacy': 'Contrôler le clan',
        'Use this section to control your clan, make alliances or send wars and to easily show it to your clan members.': 'Utilisez cette section pour contrôler votre clan, faire des alliances ou envoyer des guerres et pour le montrer facilement aux membres de votre clan.',
        'Create and edit maps to add resources or strategic points.': 'Créer et modifier des cartes pour ajouter des ressources ou des points stratégiques.',
        'The administrator will be notified to delete the user, the user will not be deleted directly.': 'The administrator will be notified to delete the user, the user will not be deleted directly.',
        'Your details': 'Vos coordonnées',
        'Discord Tag': 'Tag de la discorde',
        'Nick in Game': 'Nick dans le jeu',
        'Not defined': 'Non défini',
        'No Clan': 'Pas de clan',
        'Delete user': 'Supprimer un utilisateur',
        'Close session': 'Se déconnecter',
        'Are you sure?': 'Êtes-vous sûr ?',
        'This option is not reversible, your user and all his data will be deleted.': 'Cette option n\'est pas réversible, votre utilisateur et toutes ses données seront supprimés.',
        Cancel: 'Annuler',
        'Add name in the game': 'Ajouter un nom dans le jeu',
        'Your name in Last Oasis': 'Votre nom dans Last Oasis',
        Add: 'Ajouter',
        Share: 'Partager',
        Copy: 'Copie',
        'Join a clan': 'Rejoindre un clan',
        'Clan Name': 'Nom du clan',
        'Flag Color': 'Couleur du drapeau',
        '(Optional)': '(Facultatif)',
        'Create a clan': 'Créer un clan',
        'Manage Clan': 'Gérer le clan',
        'Leave clan': 'Quitter le clan',
        'Error when connecting to the API': 'Erreur lors de la connexion à l\'API',
        'The page you are looking for does not exist': 'The page you are looking for does not exist',
        'Log in again': 'Log in again',
        'You do not have permission to access this page': 'Vous n\'avez pas la permission d\'accéder à cette page',
        'Change language': 'Changer de langue',
        Spanish: 'Espagnol',
        English: 'Anglais',
        Russian: 'Russe',
        French: 'Française',
        German: 'German',
        Transactions: 'Transactions',
        Transaction: 'Transaction',
        Total: 'Total',
        Date: 'Date',
        'Member List': 'Liste des membres',
        Kick: 'Cliquez sur',
        'List of requests': 'Liste des demandes',
        Accept: 'Accepter',
        Reject: 'Rejeter',
        'There are no pending requests': 'Il n\'y a pas de demandes en cours',
        'Loading the list of requests to enter the clan': 'Chargement de la liste des demandes d\'entrée dans le clan',
        'Transfer Clan': 'Clan de transfert',
        'This option is not reversible, so be careful who you pass it on to in the leadership of the clan': 'Cette option n\'est pas réversible, alors faites attention à qui vous la transmettez dans la direction du clan',
        'New leader:': 'Nouveau leader:',
        'Change leader': 'Changer de leader',
        Delete: 'Supprimer',
        'Delete Clan': 'Supprimer le clan',
        'By deleting the clan you will delete all the data linked to it, be careful because this option is not reversible': 'En supprimant le clan, vous supprimez toutes les données qui y sont liées, soyez prudent car cette option n\'est pas réversible',
        Menu: 'Menu',
        'Total materials': 'Total des matériaux',
        'To make': 'To make',
        'You need the following materials': 'You need the following materials',
        'Copy to clipboard': 'Copy to clipboard',
        'Generate a link to share it': 'Generate a link to share it',
        'List of all necessary materials by': 'Liste de tous les matériaux nécessaires par',
        'Download Totals': 'Télécharger les totaux',
        'Application to enter the clan sent': 'Envoi de la demande d\'entrée dans le clan',
        Leader: 'Leader',
        'Discord Invite Link': 'Lien Invitation à la discorde',
        Actions: 'Actions',
        'Send request': 'Envoyer une demande',
        'Walker ID': 'Walker ID',
        'Clan Configuration': 'Clan Configuration',
        'Last Harvested': 'Last Harvested',
        'Harvested now': 'Harvested now',
        Now: 'Now',
        'Estimated current Quality': 'Estimated current Quality',
        'Max quality in': 'Max quality in',
        Request: 'Request',
        'Request message': 'Request message',
        'You don\'t have access here, try to log in again': 'Vous n\'avez pas d\'accès ici, essayez de vous connecter à nouveau',
        'Error when kicking a member': 'Erreur lors d\'un coup de pied à un membre',
        'Error when add member': 'Erreur lors de l\'ajout d\'un membre',
        'Error when reject member': 'Erreur lors du rejet d\'un membre',
        'Clan deleted correctly': 'Clan supprimé correctement',
        'Error when delete clan': 'Erreur lors de la suppression d\'un clan',
        'Error when change owner of clan': 'Erreur lors du changement de propriétaire du clan',
        'This option is not reversible': 'Cette option n\'est pas réversible',
        Search: 'Recherchez',
        Clean: 'Clean',
        Owner: 'Propriétaire',
        Use: 'Use',
        'Last User': 'Dernier utilisateur',
        'Last Use': 'Dernière utilisation',
        'You need to have a clan to access this section': 'Vous devez avoir un clan pour accéder à cette section',
        'For the walkers to appear it is necessary to link the discord server with the clan, only users with administration power can add the discord server.': 'Pour que les marcheurs apparaissent, il est nécessaire de relier le serveur de discorde avec le clan, seuls les utilisateurs ayant un pouvoir d\'administration peuvent ajouter le serveur de discorde.',
        'Discord ID': 'Discord ID',
        'Link discord server': 'Link discord server',
        'Discord Bot': 'Discord Bot',
        'You need to add the bot to your discord to compile the list of walkers from the log, but it also has other functions like checking what you need to do the different items': 'Vous devez ajouter le bot à votre discorde pour compiler la liste des marcheurs à partir du journal, mais il a aussi d\'autres fonctions comme la vérification de ce dont vous avez besoin pour faire les différents éléments',
        'Map List': 'Liste des cartes',
        'Map Name': 'Nom de la carte',
        'Open a map that has already been created': 'Ouvrir une carte déjà créée',
        'Open map': 'Ouvrir la carte',
        'New Map': 'Nouvelle carte',
        'Map ID': 'Map ID',
        'Map Pass': 'Map Pass',
        'Show Grid': 'Afficher la grille',
        'Hide Grid': 'Cacher la grille',
        'Allow Editing': 'Autoriser l\'édition',
        'Read Only': 'Lecture seule',
        'Enable editing with the link': 'Activer l\'édition avec le lien',
        'Date of burning': 'Date d\'incinération',
        'Map Type': 'Type de carte',
        'Create new map': 'Créer une nouvelle carte',
        'Back to the list of maps': 'Retour à la liste des cartes',
        List: 'Liste',
        Edit: 'Editer',
        Password: 'Mot de passe',
        'Update Data': 'Données actualisées',
        'Updated data': 'Données actualisées',
        'Change Password': 'Changer le mot de passe',
        'Password changed': 'Mot de passe modifié',
        Error: 'Erreur',
        Information: 'Informations',
        Type: 'Tapez',
        Coordinate: 'Coordonner',
        'Not the same as in the game': 'Pas la même chose que dans le jeu',
        'Not necessary': 'Not necessary',
        'Quality of your tool': 'Quality of your tool',
        'Quality of Harvested Resource': 'Quality of Harvested Resource',
        Quality: 'La qualité',
        'Create resource': 'Créer une ressource',
        'Login again': 'Se connecter à nouveau',
        'Temporal Marker': 'Marqueur temporel',
        'Published Trades': 'Métiers publiés',
        Supply: 'Fournir',
        Demand: 'Demande',
        Resource: 'Ressource',
        'Resource or mats for': 'Ressources ou matériels pour',
        Region: 'Région',
        'Filter trades': 'Filtrer les métiers',
        'Clean filter': 'Nettoyer le filtre',
        'If you want to publish your own exchange offers you have to be connected': 'Si vous souhaitez publier vos propres offres d\'échange, vous devez être connecté',
        'Publish an trade': 'Publier un commerce',
        Quantity: 'Quantité',
        Publish: 'Publier',
        'Price per unit': 'Prix par unité',
        Unit: 'Unité',
        'No trade offers were found with this filter': 'Aucune offre commerciale n\'a été trouvée avec ce filtre',
        Allies: 'Alliés',
        'NAP or Settlers': 'PAN ou Colons',
        Symbol: 'Symbole',
        War: 'Guerre',
        'Create a relationship': 'Créer une relation',
        'This data is not saved, if you reload the page it will be deleted': 'Ces données ne sont pas sauvegardées, si vous rechargez la page, elles seront supprimées',
        'Sound Off': 'Sonnerie',
        'Sound On': 'Sound On',
        'Show map': 'Afficher la carte',
        'Delete map': 'Effacer la carte',
        'Share map': 'Partager la carte',
        Hours: 'Heures',
        'Try again later': 'Réessayer plus tard',
        Minutes: 'Procès-verbal',
        Seconds: 'Secondes',
        Description: 'Description',
        Start: 'Démarrer',
        Stop: 'Stop',
        'made on': 'C\'est fait :',
        'Cost to learn': 'Cost to learn',
        Recipe: 'Recipe',
        'Who has learned it?': 'Who has learned it?',
        'Latest updates': 'Dernières mises à jour',
        'Report Bugs': 'Signaler les bugs',
        'If you find a bug, let me know on GitHub so it can be fixed!': 'J\'apprécierais que vous trouviez un bug et que vous m\'en parliez sur Github ou une autre plateforme afin que je puisse le corriger',
        Report: 'Rapport',
        'I have also created a discord bot useful to control the walkers and make a list of what is needed to create objects.': 'J\'ai également créé un robot de discorde utile pour contrôler les marcheurs et faire une liste de ce qui est nécessaire pour créer des objets.',
        'Go to Discord bot': 'Aller à Discord bot',
        'Dm94Dani´s Discord': 'Dm94Dani´s Discord',
        'Help keep the website running': 'Help keep the website running',
        'Steam Page': 'Steam Page',
        'Official Discord': 'Official Discord',
        'Save Tree Data': 'Save Tree Data',
        'Delete Tree Data': 'Delete Tree Data',
        'See who has learned it': 'See who has learned it',
        'No one has learnt it': 'No one has learnt it',
        'You need a clan for this function': 'You need a clan for this function',
        Wiki: 'Wiki',
        'Privacy Policy': 'Privacy Policy',
        'What information do we collect?': 'What information do we collect?',
        'Cookies - This site only uses Google cookies to view web traffic.': 'Cookies - This site only uses Google cookies to view web traffic.',
        'Private data - The only registration data saved is Discord ID and Discord Tag.': 'Private data - The only registration data saved is Discord ID and Discord Tag.',
        'What do we use this data for?': 'What do we use this data for?',
        'To improve the web experience.': 'To improve the web experience.',
        'To provide some functions such as clan management and map management.': 'To provide some functions such as clan management and map management.',
        'Our website, products and services are directed to persons who are at least 13 years of age or older.': 'Our website, products and services are directed to persons who are at least 13 years of age or older.',
        'Changes to the privacy policy': 'Changes to the privacy policy',
        'To ensure that our policies always comply with current legal requirements, we reserve the right to make changes to ensure that we are always in line with current legislation.': 'To ensure that our policies always comply with current legal requirements, we reserve the right to make changes to ensure that we are always in line with current legislation.',
        'Last modification of the policy': 'Last modification of the policy',
        'Data added to the website such as diplomacy, map resources or clan members are stored in a database and the necessary security measures are taken so that no one can access these data.': 'Data added to the website such as diplomacy, map resources or clan members are stored in a database and the necessary security measures are taken so that no one can access these data.',
        'Source Code is published on GitHub for full disclosure where you can also report any issues found.': 'Source Code is published on GitHub for full disclosure where you can also report any issues found.',
        'Discord Bot Configuration': 'Discord Bot Configuration',
        'Bot language': 'Bot language',
        'If you want the bot to read the clan log, it is necessary for other functions.': 'If you want the bot to read the clan log, it is necessary for other functions.',
        'Read discord clan log.': 'Read discord clan log.',
        'Read the clan log and if a member was kicked, kick from here too.': 'Read the clan log and if a member was kicked, kick from here too.',
        'Automatic kick members from the clan': 'Automatic kick members from the clan',
        'Automatically if a PVP walker is used it is marked as not ready.': 'Automatically if a PVP walker is used it is marked as not ready.',
        'Warns if someone brings out a walker they don\'t own.': 'Warns if someone brings out a walker they don\'t own.',
        'Sponsored servers': 'Sponsored servers',
        Close: 'Close',
        Save: 'Save',
        Vitamins: 'Vitamins',
        Equipment: 'Equipment',
        Construction: 'Construction',
        Walkers: 'Walkers',
        'Point Of Interest': 'Point Of Interest',
        'Trade Station': 'Trade Station',
        Proxy: 'Proxy',
        All: 'All',
        Aloe: 'Aloe',
        'Animal Fat': 'Animal Fat',
        Apple: 'Apple',
        Ash: 'Ash',
        Beeswax: 'Beeswax',
        'Blood Turnip': 'Blood Turnip',
        'Bone Glue': 'Bone Glue',
        'Bone Splinter': 'Bone Splinter',
        'Cactus Flesh': 'Cactus Flesh',
        Cattail: 'Cattail',
        'Ceramic Shard': 'Ceramic Shard',
        Charcoal: 'Charcoal',
        'Chitin Plate': 'Chitin Plate',
        Clay: 'Clay',
        'Contaminated Water': 'Contaminated Water',
        Corn: 'Corn',
        Cotton: 'Cotton',
        'Earth Wax': 'Earth Wax',
        Feather: 'Feather',
        Fiber: 'Fiber',
        'Fiber Weave': 'Fiber Weave',
        Fragment: 'Fragment',
        Glass: 'Glass',
        Hide: 'Hide',
        'Huge Cactus Fruit': 'Huge Cactus Fruit',
        Insects: 'Insects',
        'Iron Ingot': 'Iron Ingot',
        'Iron Ore': 'Iron Ore',
        Lava: 'Lava',
        'Liquid Fuel': 'Liquid Fuel',
        'Meteor Core': 'Meteor Core',
        'Mushroom Flesh': 'Mushroom Flesh',
        'Nibiran Mineral': 'Nibiran Mineral',
        'Nomad Cloth': 'Nomad Cloth',
        'Proxy License': 'Proxy License',
        Obsidian: 'Obsidian',
        'Palm Leaves': 'Palm Leaves',
        Pearl: 'Pearl',
        'Purified Water': 'Purified Water',
        'Red Banana': 'Red Banana',
        'Redwood Wood': 'Redwood Wood',
        'Reinforced Plank': 'Reinforced Plank',
        Rope: 'Rope',
        'Rupu Gel': 'Rupu Gel',
        'Rupu Pelt': 'Rupu Pelt',
        'Rupu Vine': 'Rupu Vine',
        'Salt Rock': 'Salt Rock',
        Sand: 'Sand',
        'Shattered Fragment': 'Shattered Fragment',
        Stone: 'Stone',
        Sulfur: 'Sulfur',
        Tablet: 'Tablet',
        'Terrain: Clay Spots': 'Terrain: Clay Spots',
        'Terrain: Black Soil': 'Terrain: Black Soil',
        'Terrain: Excavatable': 'Terrain: Excavatable',
        Tar: 'Tar',
        Thornberry: 'Thornberry',
        Torque: 'Torque',
        'Walker Mechanism': 'Walker Mechanism',
        Wood: 'Wood',
        'Wood Shaft': 'Wood Shaft',
        'Worm Scale': 'Worm Scale',
        'Worm Silk': 'Worm Silk',
        Base: 'Base',
        'Enemy Base': 'Base ennemie',
        'Friend Base': 'Base d\'amis',
        Trader: 'Marchand',
        'Barrier Base': 'Barrier Base',
        'Barrier Gate': 'Barrier Gate',
        'Barrier Plank': 'Barrier Plank',
        Bed: 'Bed',
        Hammock: 'Hammock',
        'Sand Bed': 'Sand Bed',
        'Cement Battlements': 'Cement Battlements',
        'Cement Corner': 'Cement Corner',
        'Cement Door': 'Cement Door',
        'Cement Foundation': 'Cement Foundation',
        'Cement Roof': 'Cement Roof',
        'Cement Wall 1': 'Cement Wall 1',
        'Cement Wall 2': 'Cement Wall 2',
        'Cement Wall With Window 1': 'Cement Wall With Window 1',
        'Cement Wall With Window 2': 'Cement Wall With Window 2',
        'Cement Wall With Windows 1': 'Cement Wall With Windows 1',
        'Cement Wall With Windows 2': 'Cement Wall With Windows 2',
        'Clay Battlement': 'Clay Battlement',
        'Clay Corner': 'Clay Corner',
        'Clay Door': 'Clay Door',
        'Clay Foundation': 'Clay Foundation',
        'Clay Roof': 'Clay Roof',
        'Clay Wall': 'Clay Wall',
        'Clay Wall with Window': 'Clay Wall with Window',
        'Clay Wall with Windows': 'Clay Wall with Windows',
        'Stone Wall': 'Stone Wall',
        'Stone Door': 'Stone Door',
        'Stone Roof': 'Stone Roof',
        'Stone Wall with Window': 'Stone Wall with Window',
        'Ammo Chest': 'Ammo Chest',
        'Gigantic Chest': 'Gigantic Chest',
        'Large Chest': 'Large Chest',
        'Large Water Bag': 'Large Water Bag',
        'Medium Chest': 'Medium Chest',
        'Medium Water Bag': 'Medium Water Bag',
        'Obsidian Canister': 'Obsidian Canister',
        'Obsidian Pot': 'Obsidian Pot',
        'Small Water Bag': 'Small Water Bag',
        'Small Chest': 'Small Chest',
        'Water Pitcher': 'Water Pitcher',
        'Clan Flag': 'Clan Flag',
        'Clan Flag Hanging': 'Clan Flag Hanging',
        'Heavy Wood Battlements': 'Heavy Wood Battlements',
        'Heavy Wood Corner': 'Heavy Wood Corner',
        'Heavy Wood Door': 'Heavy Wood Door',
        'Heavy Wood Double Slit Wall': 'Heavy Wood Double Slit Wall',
        'Heavy Wood Foundation': 'Heavy Wood Foundation',
        'Heavy Wood Roof': 'Heavy Wood Roof',
        'Heavy Wood Slit Wall': 'Heavy Wood Slit Wall',
        'Heavy Wood Wall 1': 'Heavy Wood Wall 1',
        'Heavy Wood Wall 2': 'Heavy Wood Wall 2',
        'Light Wood Door': 'Light Wood Door',
        'Light Wood Foundation': 'Light Wood Foundation',
        'Light Wood Guard Rail': 'Light Wood Guard Rail',
        'Light Wood Roof': 'Light Wood Roof',
        'Light Wood Stairs': 'Light Wood Stairs',
        'Light Wood Wooden Battlements': 'Light Wood Wooden Battlements',
        'Light Wood Wooden Corner': 'Light Wood Wooden Corner',
        'Light Wood Wooden Double Slit Wall': 'Light Wood Wooden Double Slit Wall',
        'Light Wood Wooden Slit Wall': 'Light Wood Wooden Slit Wall',
        'Light Wood Wooden Wall': 'Light Wood Wooden Wall',
        'Medium Wood Battlements': 'Medium Wood Battlements',
        'Medium Wood Door': 'Medium Wood Door',
        'Medium Wood Double Slit Wall': 'Medium Wood Double Slit Wall',
        'Medium Wood Foundation': 'Medium Wood Foundation',
        'Medium Wood Roof': 'Medium Wood Roof',
        'Medium Wood Slit Wall': 'Medium Wood Slit Wall',
        'Medium Wood Wall': 'Medium Wood Wall',
        'Cloth Door': 'Cloth Door',
        'Sandbag Roof': 'Sandbag Roof',
        'Sandbag Wall': 'Sandbag Wall',
        'Sandbag Wall Window': 'Sandbag Wall Window',
        Crane: 'Crane',
        'Hose Station': 'Hose Station',
        Rangefinder: 'Rangefinder',
        Ballista: 'Ballista',
        Catapult: 'Catapult',
        'Gun Pod': 'Gun Pod',
        'Net Thrower': 'Net Thrower',
        'Remote Ballista': 'Remote Ballista',
        Repeater: 'Repeater',
        'Scattershot Gun': 'Scattershot Gun',
        Slingshot: 'Slingshot',
        'Small Ballista': 'Small Ballista',
        'Gun Pod Plating': 'Gun Pod Plating',
        'Gun Pod Shell': 'Gun Pod Shell',
        'Chair Comfortable': 'Chair Comfortable',
        'Chair Simple': 'Chair Simple',
        'Chair Throne': 'Chair Throne',
        Table: 'Table',
        'Basket Open': 'Basket Open',
        'Basket Tall': 'Basket Tall',
        'Basket Wide': 'Basket Wide',
        'Carpet Dark': 'Carpet Dark',
        'Carpet Light': 'Carpet Light',
        'Fire Goblet': 'Fire Goblet',
        'Lamp Double Hanging': 'Lamp Double Hanging',
        'Lamp Overhanging': 'Lamp Overhanging',
        'Lamp Single Hanging': 'Lamp Single Hanging',
        'Lamp Standing': 'Lamp Standing',
        'Advanced Fiberworking Station': 'Advanced Fiberworking Station',
        'Advanced Furnace': 'Advanced Furnace',
        'Advanced Woodworking Station': 'Advanced Woodworking Station',
        'Artificer Woodworking Station': 'Artificer Woodworking Station',
        'Camp Fire': 'Camp Fire',
        'Dyeing Station': 'Dyeing Station',
        'Fiberworking Station': 'Fiberworking Station',
        Furnace: 'Furnace',
        Lumbermill: 'Lumbermill',
        'Obsidian Machine': 'Obsidian Machine',
        'Purification Station': 'Purification Station',
        Quarry: 'Quarry',
        'Infused Obsidian Bottle': 'Infused Obsidian Bottle',
        'Soil Excavator': 'Soil Excavator',
        'Stomping Station': 'Stomping Station',
        'Torque Windmill': 'Torque Windmill',
        'Water Condenser': 'Water Condenser',
        'Woodworking Station': 'Woodworking Station',
        'Cauterizing Station': 'Cauterizing Station',
        'Defensive Tower': 'Defensive Tower',
        'Rupu Sling': 'Rupu Sling',
        'Bone Bolt': 'Bone Bolt',
        'Bone Harpoon': 'Bone Harpoon',
        'Ceramic-Tipped Bolt': 'Ceramic-Tipped Bolt',
        'Ceramic-Tipped Harpoon': 'Ceramic-Tipped Harpoon',
        'Fire Bolt': 'Fire Bolt',
        'Flint Bolt': 'Flint Bolt',
        'Flint Harpoon': 'Flint Harpoon',
        'Hellfire Bolt': 'Hellfire Bolt',
        'Iron-Tipped Bolt': 'Iron-Tipped Bolt',
        'Iron-Tipped Harpoon': 'Iron-Tipped Harpoon',
        'Explosive Bolt': 'Explosive Bolt',
        'Catapult Boulder': 'Catapult Boulder',
        'Fire Bomb': 'Fire Bomb',
        'Charged Boulder': 'Charged Boulder',
        Bombolt: 'Bombolt',
        Net: 'Net',
        Dart: 'Dart',
        'Floating Mine': 'Floating Mine',
        'Explosive Dart': 'Explosive Dart',
        'Hullbreaker Scattershot': 'Hullbreaker Scattershot',
        Scattershot: 'Scattershot',
        'Aloe Goo Bomb': 'Aloe Goo Bomb',
        'Chalk Bomb': 'Chalk Bomb',
        'Cluster Bomb': 'Cluster Bomb',
        'Green Death Bomb': 'Green Death Bomb',
        'Insect Bomb': 'Insect Bomb',
        'Rupu Rock': 'Rupu Rock',
        'Small Boulder': 'Small Boulder',
        'Sulfur Bomb': 'Sulfur Bomb',
        'Gas Mask': 'Gas Mask',
        'Baskwood Armor': 'Baskwood Armor',
        'Baskwood Boots': 'Baskwood Boots',
        'Baskwood Bracers': 'Baskwood Bracers',
        'Carapace Armor': 'Carapace Armor',
        'Carapace Boots': 'Carapace Boots',
        'Carapace Gauntlets': 'Carapace Gauntlets',
        Cloak: 'Cloak',
        'Feather Boots': 'Feather Boots',
        'Fiber Arm Wraps': 'Fiber Arm Wraps',
        'Fiber Headwrap': 'Fiber Headwrap',
        'Fiber Sandals': 'Fiber Sandals',
        'Fiber Shirt And Trousers': 'Fiber Shirt And Trousers',
        'Brittle Bone Armor': 'Brittle Bone Armor',
        'Forester\'s Armor': 'Forester\'s Armor',
        'Forester\'s Sandals': 'Forester\'s Sandals',
        'Forester\'s Sleeves': 'Forester\'s Sleeves',
        'Iron Studded Armor': 'Iron Studded Armor',
        'Iron Studded Boots': 'Iron Studded Boots',
        'Iron Studded Gauntlets': 'Iron Studded Gauntlets',
        'Redwood Wood Armor': 'Redwood Wood Armor',
        'Redwood Wood Boots': 'Redwood Wood Boots',
        'Redwood Wood Bracers': 'Redwood Wood Bracers',
        'Cloaked Rupu Fur Armor': 'Cloaked Rupu Fur Armor',
        'Rupu Fur Armor': 'Rupu Fur Armor',
        'Rupu Fur Sandals': 'Rupu Fur Sandals',
        'Rupu Fur Sleeves': 'Rupu Fur Sleeves',
        'Triple Stitch Armor': 'Triple Stitch Armor',
        'Triple Stitch Boots': 'Triple Stitch Boots',
        'Triple Stitch Bracers': 'Triple Stitch Bracers',
        Kite: 'Kite',
        Exoskeleton: 'Exoskeleton',
        'Durable Water Sack': 'Durable Water Sack',
        'Heavy Backpack': 'Heavy Backpack',
        'Light Backpack': 'Light Backpack',
        'Split Durable Water Sack': 'Split Durable Water Sack',
        'Medium Backpack': 'Medium Backpack',
        'Torque Backpack': 'Torque Backpack',
        'Water Circulator': 'Water Circulator',
        Wingsuit: 'Wingsuit',
        'Bone Bottle': 'Bone Bottle',
        'Ceramic Flask': 'Ceramic Flask',
        'Improvised Bottle': 'Improvised Bottle',
        'Makeshift Bottle': 'Makeshift Bottle',
        'Obsidian Flask': 'Obsidian Flask',
        'Split Bone Bottle': 'Split Bone Bottle',
        'Split Ceramic Flask': 'Split Ceramic Flask',
        'Foraging Pouch': 'Foraging Pouch',
        'Large Gathering Pouch': 'Large Gathering Pouch',
        'Beltless Grappling Hook': 'Beltless Grappling Hook',
        'Fast Grappling Hook': 'Fast Grappling Hook',
        'Long Grappling Hook': 'Long Grappling Hook',
        'Repaired Grappling Hook': 'Repaired Grappling Hook',
        'Torque Battery': 'Torque Battery',
        'Primitive Bandage': 'Primitive Bandage',
        'Sterile Bandage': 'Sterile Bandage',
        'Magma Seeds': 'Magma Seeds',
        Bonebreaker: 'Bonebreaker',
        'Desert Mule': 'Desert Mule',
        'Worm Tincture': 'Worm Tincture',
        'Fury Fumes': 'Fury Fumes',
        'Jojo Mojo': 'Jojo Mojo',
        'Race Dust': 'Race Dust',
        'Rupu Repellent': 'Rupu Repellent',
        'Sinus Destroyer': 'Sinus Destroyer',
        'Vision Powder': 'Vision Powder',
        'Beat Stick': 'Beat Stick',
        'Blunt Quarterstaff': 'Blunt Quarterstaff',
        'Bonespike Sword': 'Bonespike Sword',
        'Bouldercut Battle Axe': 'Bouldercut Battle Axe',
        'Firestone Bladestaff': 'Firestone Bladestaff',
        'Firestone Bludgeon': 'Firestone Bludgeon',
        'Firestone Bozdogan': 'Firestone Bozdogan',
        'Firestone Hammerstaff': 'Firestone Hammerstaff',
        'Firestone Kopesh': 'Firestone Kopesh',
        'Firestone Longblade': 'Firestone Longblade',
        'Ironblade Quarterstaff': 'Ironblade Quarterstaff',
        'Jaggertooth Club': 'Jaggertooth Club',
        'Jaggertooth Maul': 'Jaggertooth Maul',
        Javelin: 'Javelin',
        'Long Bonespike Swordstaff': 'Long Bonespike Swordstaff',
        'Long Ceramic Hoofmace': 'Long Ceramic Hoofmace',
        'Nibiran Battle Axe': 'Nibiran Battle Axe',
        'Nibiran Curved Dagger': 'Nibiran Curved Dagger',
        'Nibiran Decapitator': 'Nibiran Decapitator',
        'Nibiran Hammer': 'Nibiran Hammer',
        'Nibiran Quarterstaff': 'Nibiran Quarterstaff',
        'Nibiran Warhammer': 'Nibiran Warhammer',
        'Paddleblade Quarterstaff': 'Paddleblade Quarterstaff',
        'Rawbone Club': 'Rawbone Club',
        'Rawbone Maul': 'Rawbone Maul',
        'Rawbone Quarterstaff': 'Rawbone Quarterstaff',
        'Sawtooth Sword': 'Sawtooth Sword',
        'Short Ceramic Hoofmace': 'Short Ceramic Hoofmace',
        'Short Malletblade': 'Short Malletblade',
        Singblade: 'Singblade',
        'Spikebone Club': 'Spikebone Club',
        'Spikebone Maul': 'Spikebone Maul',
        'Throwing Net': 'Throwing Net',
        Torch: 'Torch',
        'Traveller\'s Staff': 'Traveller\'s Staff',
        'Wyndan Flame Sword': 'Wyndan Flame Sword',
        'Wyndan Hammer': 'Wyndan Hammer',
        'Wyndan Sabre': 'Wyndan Sabre',
        'Wyndan Warhammer': 'Wyndan Warhammer',
        'Wyndanblade Quarterstaff': 'Wyndanblade Quarterstaff',
        Firebomb: 'Firebomb',
        'Firestone Axe': 'Firestone Axe',
        'Firestone Battleaxe': 'Firestone Battleaxe',
        'Advanced Hatchet': 'Advanced Hatchet',
        'Bouldercut Hand Axe': 'Bouldercut Hand Axe',
        'Heavy Rawbone Hand Axe': 'Heavy Rawbone Hand Axe',
        'Nibiran Hand Axe': 'Nibiran Hand Axe',
        'Rawbone Battle Axe': 'Rawbone Battle Axe',
        'Rawbone Hand Axe': 'Rawbone Hand Axe',
        'Woodcutter\'s Hatchet': 'Woodcutter\'s Hatchet',
        'Advanced Pickaxe': 'Advanced Pickaxe',
        'Master Pickaxe': 'Master Pickaxe',
        'Simple Pickaxe': 'Simple Pickaxe',
        'Simple Repair Hammer': 'Simple Repair Hammer',
        Scythe: 'Scythe',
        'Simple Sickle': 'Simple Sickle',
        'Nibiran Ingot': 'Nibiran Ingot',
        'Lava Fuel': 'Lava Fuel',
        'Buffalo Walker Body': 'Buffalo Walker Body',
        'Buffalo Walker Legs (1 of 2)': 'Buffalo Walker Legs (1 of 2)',
        'Buffalo Walker Legs Armored (1 of 2)': 'Buffalo Walker Legs Armored (1 of 2)',
        'Buffalo Walker Legs Heavy (1 of 2)': 'Buffalo Walker Legs Heavy (1 of 2)',
        'Buffalo Walker Wings Heavy (1 of 2)': 'Buffalo Walker Wings Heavy (1 of 2)',
        'Buffalo Walker Wings Medium (1 of 2)': 'Buffalo Walker Wings Medium (1 of 2)',
        'Buffalo Walker Wings Raider (1 of 2)': 'Buffalo Walker Wings Raider (1 of 2)',
        'Buffalo Walker Wings Rugged (1 of 2)': 'Buffalo Walker Wings Rugged (1 of 2)',
        'Buffalo Walker Wings Skirmish (1 of 2)': 'Buffalo Walker Wings Skirmish (1 of 2)',
        'Buffalo Walker Wings Small (1 of 2)': 'Buffalo Walker Wings Small (1 of 2)',
        'Buffalo Walker Wings (1 of 2)': 'Buffalo Walker Wings (1 of 2)',
        'Buffalo Walker Upgrade - Cargo - Tier 2': 'Buffalo Walker Upgrade - Cargo - Tier 2',
        'Buffalo Walker Upgrade - Durability - Tier 2': 'Buffalo Walker Upgrade - Durability - Tier 2',
        'Buffalo Walker Upgrade - Gear - Tier 2': 'Buffalo Walker Upgrade - Gear - Tier 2',
        'Buffalo Walker Upgrade - Mobility - Tier 2': 'Buffalo Walker Upgrade - Mobility - Tier 2',
        'Buffalo Walker Upgrade - Torque - Tier 2': 'Buffalo Walker Upgrade - Torque - Tier 2',
        'Buffalo Walker Upgrade - Water - Tier 2': 'Buffalo Walker Upgrade - Water - Tier 2',
        'Buffalo Walker Upgrade - Cargo - Tier 3': 'Buffalo Walker Upgrade - Cargo - Tier 3',
        'Buffalo Walker Upgrade - Durability - Tier 3': 'Buffalo Walker Upgrade - Durability - Tier 3',
        'Buffalo Walker Upgrade - Gear - Tier 3': 'Buffalo Walker Upgrade - Gear - Tier 3',
        'Buffalo Walker Upgrade - Mobility - Tier 3': 'Buffalo Walker Upgrade - Mobility - Tier 3',
        'Buffalo Walker Upgrade - Torque - Tier 3': 'Buffalo Walker Upgrade - Torque - Tier 3',
        'Buffalo Walker Upgrade - Water - Tier 3': 'Buffalo Walker Upgrade - Water - Tier 3',
        'Buffalo Walker Upgrade - Cargo - Tier 4': 'Buffalo Walker Upgrade - Cargo - Tier 4',
        'Buffalo Walker Upgrade - Durability - Tier 4': 'Buffalo Walker Upgrade - Durability - Tier 4',
        'Buffalo Walker Upgrade - Gear - Tier 4': 'Buffalo Walker Upgrade - Gear - Tier 4',
        'Buffalo Walker Upgrade - Mobility - Tier 4': 'Buffalo Walker Upgrade - Mobility - Tier 4',
        'Buffalo Walker Upgrade - Torque - Tier 4': 'Buffalo Walker Upgrade - Torque - Tier 4',
        'Buffalo Walker Upgrade - Water - Tier 4': 'Buffalo Walker Upgrade - Water - Tier 4',
        'Camelop Walker Body': 'Camelop Walker Body',
        'Camelop Walker Legs (1 of 2)': 'Camelop Walker Legs (1 of 2)',
        'Camelop Walker Upgrade - Torque - Tier 2': 'Camelop Walker Upgrade - Torque - Tier 2',
        'Camelop Walker Upgrade - Water - Tier 2': 'Camelop Walker Upgrade - Water - Tier 2',
        'Camelop Walker Upgrade - Torque - Tier 3': 'Camelop Walker Upgrade - Torque - Tier 3',
        'Camelop Walker Upgrade - Water - Tier 3': 'Camelop Walker Upgrade - Water - Tier 3',
        'Camelop Walker Upgrade - Torque - Tier 4': 'Camelop Walker Upgrade - Torque - Tier 4',
        'Camelop Walker Upgrade - Water - Tier 4': 'Camelop Walker Upgrade - Water - Tier 4',
        'Cobra Walker Body': 'Cobra Walker Body',
        'Cobra Walker Legs (1 of 2)': 'Cobra Walker Legs (1 of 2)',
        'Cobra Walker Upgrade - Cargo - Tier 2': 'Cobra Walker Upgrade - Cargo - Tier 2',
        'Cobra Walker Upgrade - Torque - Tier 2': 'Cobra Walker Upgrade - Torque - Tier 2',
        'Cobra Walker Upgrade - Water - Tier 2': 'Cobra Walker Upgrade - Water - Tier 2',
        'Cobra Walker Upgrade - Cargo - Tier 3': 'Cobra Walker Upgrade - Cargo - Tier 3',
        'Cobra Walker Upgrade - Torque - Tier 3': 'Cobra Walker Upgrade - Torque - Tier 3',
        'Cobra Walker Upgrade - Water - Tier 3': 'Cobra Walker Upgrade - Water - Tier 3',
        'Cobra Walker Upgrade - Cargo - Tier 4': 'Cobra Walker Upgrade - Cargo - Tier 4',
        'Cobra Walker Upgrade - Torque - Tier 4': 'Cobra Walker Upgrade - Torque - Tier 4',
        'Cobra Walker Upgrade - Water - Tier 4': 'Cobra Walker Upgrade - Water - Tier 4',
        'Dinghy Walker Body': 'Dinghy Walker Body',
        'Dinghy Walker Legs (1 of 2)': 'Dinghy Walker Legs (1 of 2)',
        'Dinghy Walker Wings Small (1 of 2)': 'Dinghy Walker Wings Small (1 of 2)',
        'Dinghy Walker Wings (1 of 2)': 'Dinghy Walker Wings (1 of 2)',
        'Dinghy Walker Upgrade - Cargo - Tier 2': 'Dinghy Walker Upgrade - Cargo - Tier 2',
        'Dinghy Walker Upgrade - Durability - Tier 2': 'Dinghy Walker Upgrade - Durability - Tier 2',
        'Dinghy Walker Upgrade - Gear - Tier 2': 'Dinghy Walker Upgrade - Gear - Tier 2',
        'Dinghy Walker Upgrade - Mobility - Tier 2': 'Dinghy Walker Upgrade - Mobility - Tier 2',
        'Dinghy Walker Upgrade - Torque - Tier 2': 'Dinghy Walker Upgrade - Torque - Tier 2',
        'Dinghy Walker Upgrade - Water - Tier 2': 'Dinghy Walker Upgrade - Water - Tier 2',
        'Dinghy Walker Upgrade - Cargo - Tier 3': 'Dinghy Walker Upgrade - Cargo - Tier 3',
        'Dinghy Walker Upgrade - Durability - Tier 3': 'Dinghy Walker Upgrade - Durability - Tier 3',
        'Dinghy Walker Upgrade - Gear - Tier 3': 'Dinghy Walker Upgrade - Gear - Tier 3',
        'Dinghy Walker Upgrade - Mobility - Tier 3': 'Dinghy Walker Upgrade - Mobility - Tier 3',
        'Dinghy Walker Upgrade - Torque - Tier 3': 'Dinghy Walker Upgrade - Torque - Tier 3',
        'Dinghy Walker Upgrade - Water - Tier 3': 'Dinghy Walker Upgrade - Water - Tier 3',
        'Dinghy Walker Upgrade - Cargo - Tier 4': 'Dinghy Walker Upgrade - Cargo - Tier 4',
        'Dinghy Walker Upgrade - Durability - Tier 4': 'Dinghy Walker Upgrade - Durability - Tier 4',
        'Dinghy Walker Upgrade - Gear - Tier 4': 'Dinghy Walker Upgrade - Gear - Tier 4',
        'Dinghy Walker Upgrade - Mobility - Tier 4': 'Dinghy Walker Upgrade - Mobility - Tier 4',
        'Dinghy Walker Upgrade - Torque - Tier 4': 'Dinghy Walker Upgrade - Torque - Tier 4',
        'Dinghy Walker Upgrade - Water - Tier 4': 'Dinghy Walker Upgrade - Water - Tier 4',
        'Domus Walker Body': 'Domus Walker Body',
        'Domus Walker Legs Armored (1 of 2)': 'Domus Walker Legs Armored (1 of 2)',
        'Domus Walker Legs (1 of 2)': 'Domus Walker Legs (1 of 2)',
        'Domus Walker Legs Heavy (1 of 2)': 'Domus Walker Legs Heavy (1 of 2)',
        'Domus Walker Wings Heavy (1 of 2)': 'Domus Walker Wings Heavy (1 of 2)',
        'Domus Walker Large Wings (1 of 2)': 'Domus Walker Large Wings (1 of 2)',
        'Domus Walker Wings Medium (1 of 2)': 'Domus Walker Wings Medium (1 of 2)',
        'Domus Walker Wings Raider (1 of 2)': 'Domus Walker Wings Raider (1 of 2)',
        'Domus Walker Wings Rugged (1 of 2)': 'Domus Walker Wings Rugged (1 of 2)',
        'Domus Walker Wings Skirmish (1 of 2)': 'Domus Walker Wings Skirmish (1 of 2)',
        'Domus Walker Wings Small (1 of 2)': 'Domus Walker Wings Small (1 of 2)',
        'Domus Walker Wings (1 of 2)': 'Domus Walker Wings (1 of 2)',
        'Domus Walker Upgrade - Cargo - Tier 2': 'Domus Walker Upgrade - Cargo - Tier 2',
        'Domus Walker Upgrade - Durability - Tier 2': 'Domus Walker Upgrade - Durability - Tier 2',
        'Domus Walker Upgrade - Gear - Tier 2': 'Domus Walker Upgrade - Gear - Tier 2',
        'Domus Walker Upgrade - Mobility - Tier 2': 'Domus Walker Upgrade - Mobility - Tier 2',
        'Domus Walker Upgrade - Torque - Tier 2': 'Domus Walker Upgrade - Torque - Tier 2',
        'Domus Walker Upgrade - Water - Tier 2': 'Domus Walker Upgrade - Water - Tier 2',
        'Domus Walker Upgrade - Cargo - Tier 3': 'Domus Walker Upgrade - Cargo - Tier 3',
        'Domus Walker Upgrade - Durability - Tier 3': 'Domus Walker Upgrade - Durability - Tier 3',
        'Domus Walker Upgrade - Gear - Tier 3': 'Domus Walker Upgrade - Gear - Tier 3',
        'Domus Walker Upgrade - Mobility - Tier 3': 'Domus Walker Upgrade - Mobility - Tier 3',
        'Domus Walker Upgrade - Torque - Tier 3': 'Domus Walker Upgrade - Torque - Tier 3',
        'Domus Walker Upgrade - Water - Tier 3': 'Domus Walker Upgrade - Water - Tier 3',
        'Domus Walker Upgrade - Cargo - Tier 4': 'Domus Walker Upgrade - Cargo - Tier 4',
        'Domus Walker Upgrade - Durability - Tier 4': 'Domus Walker Upgrade - Durability - Tier 4',
        'Domus Walker Upgrade - Gear - Tier 4': 'Domus Walker Upgrade - Gear - Tier 4',
        'Domus Walker Upgrade - Mobility - Tier 4': 'Domus Walker Upgrade - Mobility - Tier 4',
        'Domus Walker Upgrade - Torque - Tier 4': 'Domus Walker Upgrade - Torque - Tier 4',
        'Domus Walker Upgrade - Water - Tier 4': 'Domus Walker Upgrade - Water - Tier 4',
        'Falco Walker Body': 'Falco Walker Body',
        'Falco Walker Legs Armored (1 of 2)': 'Falco Walker Legs Armored (1 of 2)',
        'Falco Walker Legs (1 of 2)': 'Falco Walker Legs (1 of 2)',
        'Falco Walker Legs Heavy (1 of 2)': 'Falco Walker Legs Heavy (1 of 2)',
        'Falco Walker Wings (1 of 2)': 'Falco Walker Wings (1 of 2)',
        'Falco Walker Wings Heavy (1 of 2)': 'Falco Walker Wings Heavy (1 of 2)',
        'Falco Walker Wings Large (1 of 2)': 'Falco Walker Wings Large (1 of 2)',
        'Falco Walker Wings Medium (1 of 2)': 'Falco Walker Wings Medium (1 of 2)',
        'Falco Walker Wings Raider (1 of 2)': 'Falco Walker Wings Raider (1 of 2)',
        'Falco Walker Wings Rugged (1 of 2)': 'Falco Walker Wings Rugged (1 of 2)',
        'Falco Walker Wings Skirmish (1 of 2)': 'Falco Walker Wings Skirmish (1 of 2)',
        'Falco Walker Wings Small (1 of 2)': 'Falco Walker Wings Small (1 of 2)',
        'Falco Walker Upgrade - Cargo - Tier 1': 'Falco Walker Upgrade - Cargo - Tier 1',
        'Falco Walker Upgrade - Durability - Tier 1': 'Falco Walker Upgrade - Durability - Tier 1',
        'Falco Walker Upgrade - Gear - Tier 1': 'Falco Walker Upgrade - Gear - Tier 1',
        'Falco Walker Upgrade - Mobility - Tier 1': 'Falco Walker Upgrade - Mobility - Tier 1',
        'Falco Walker Upgrade - Torque - Tier 1': 'Falco Walker Upgrade - Torque - Tier 1',
        'Falco Walker Upgrade - Water - Tier 1': 'Falco Walker Upgrade - Water - Tier 1',
        'Falco Walker Upgrade - Cargo - Tier 2': 'Falco Walker Upgrade - Cargo - Tier 2',
        'Falco Walker Upgrade - Durability - Tier 2': 'Falco Walker Upgrade - Durability - Tier 2',
        'Falco Walker Upgrade - Gear - Tier 2': 'Falco Walker Upgrade - Gear - Tier 2',
        'Falco Walker Upgrade - Mobility - Tier 2': 'Falco Walker Upgrade - Mobility - Tier 2',
        'Falco Walker Upgrade - Torque - Tier 2': 'Falco Walker Upgrade - Torque - Tier 2',
        'Falco Walker Upgrade - Water - Tier 2': 'Falco Walker Upgrade - Water - Tier 2',
        'Falco Walker Upgrade - Cargo - Tier 3': 'Falco Walker Upgrade - Cargo - Tier 3',
        'Falco Walker Upgrade - Durability - Tier 3': 'Falco Walker Upgrade - Durability - Tier 3',
        'Falco Walker Upgrade - Gear - Tier 3': 'Falco Walker Upgrade - Gear - Tier 3',
        'Falco Walker Upgrade - Mobility - Tier 3': 'Falco Walker Upgrade - Mobility - Tier 3',
        'Falco Walker Upgrade - Torque - Tier 3': 'Falco Walker Upgrade - Torque - Tier 3',
        'Falco Walker Upgrade - Water - Tier 3': 'Falco Walker Upgrade - Water - Tier 3',
        'Falco Walker Upgrade - Cargo - Tier 4': 'Falco Walker Upgrade - Cargo - Tier 4',
        'Falco Walker Upgrade - Durability - Tier 4': 'Falco Walker Upgrade - Durability - Tier 4',
        'Falco Walker Upgrade - Gear - Tier 4': 'Falco Walker Upgrade - Gear - Tier 4',
        'Falco Walker Upgrade - Mobility - Tier 4': 'Falco Walker Upgrade - Mobility - Tier 4',
        'Falco Walker Upgrade - Torque - Tier 4': 'Falco Walker Upgrade - Torque - Tier 4',
        'Falco Walker Upgrade - Water - Tier 4': 'Falco Walker Upgrade - Water - Tier 4',
        'Firefly Walker Body': 'Firefly Walker Body',
        'Firefly Walker Legs (1 of 2)': 'Firefly Walker Legs (1 of 2)',
        'Firefly Walker Wings (1 of 2)': 'Firefly Walker Wings (1 of 2)',
        'Firefly Walker Upgrade - Cargo - Tier 1': 'Firefly Walker Upgrade - Cargo - Tier 1',
        'Firefly Walker Upgrade - Durability - Tier 1': 'Firefly Walker Upgrade - Durability - Tier 1',
        'Firefly Walker Upgrade - Gear - Tier 1': 'Firefly Walker Upgrade - Gear - Tier 1',
        'Firefly Walker Upgrade - Mobility - Tier 1': 'Firefly Walker Upgrade - Mobility - Tier 1',
        'Firefly Walker Upgrade - Water - Tier 1': 'Firefly Walker Upgrade - Water - Tier 1',
        'Firefly Walker Upgrade - Cargo - Tier 2': 'Firefly Walker Upgrade - Cargo - Tier 2',
        'Firefly Walker Upgrade - Durability - Tier 2': 'Firefly Walker Upgrade - Durability - Tier 2',
        'Firefly Walker Upgrade - Gear - Tier 2': 'Firefly Walker Upgrade - Gear - Tier 2',
        'Firefly Walker Upgrade - Mobility - Tier 2': 'Firefly Walker Upgrade - Mobility - Tier 2',
        'Firefly Walker Upgrade - Torque - Tier 2': 'Firefly Walker Upgrade - Torque - Tier 2',
        'Firefly Walker Upgrade - Water - Tier 2': 'Firefly Walker Upgrade - Water - Tier 2',
        'Firefly Walker Upgrade - Cargo - Tier 3': 'Firefly Walker Upgrade - Cargo - Tier 3',
        'Firefly Walker Upgrade - Durability - Tier 3': 'Firefly Walker Upgrade - Durability - Tier 3',
        'Firefly Walker Upgrade - Gear - Tier 3': 'Firefly Walker Upgrade - Gear - Tier 3',
        'Firefly Walker Upgrade - Mobility - Tier 3': 'Firefly Walker Upgrade - Mobility - Tier 3',
        'Firefly Walker Upgrade - Torque - Tier 3': 'Firefly Walker Upgrade - Torque - Tier 3',
        'Firefly Walker Upgrade - Water - Tier 3': 'Firefly Walker Upgrade - Water - Tier 3',
        'Firefly Walker Upgrade - Cargo - Tier 4': 'Firefly Walker Upgrade - Cargo - Tier 4',
        'Firefly Walker Upgrade - Durability - Tier 4': 'Firefly Walker Upgrade - Durability - Tier 4',
        'Firefly Walker Upgrade - Gear - Tier 4': 'Firefly Walker Upgrade - Gear - Tier 4',
        'Firefly Walker Upgrade - Mobility - Tier 4': 'Firefly Walker Upgrade - Mobility - Tier 4',
        'Firefly Walker Upgrade - Torque - Tier 4': 'Firefly Walker Upgrade - Torque - Tier 4',
        'Firefly Walker Upgrade - Water - Tier 4': 'Firefly Walker Upgrade - Water - Tier 4',
        'Hornet Walker Body': 'Hornet Walker Body',
        'Hornet Walker Legs (1 of 2)': 'Hornet Walker Legs (1 of 2)',
        'Hornet Walker Legs Heavy (1 of 2)': 'Hornet Walker Legs Heavy (1 of 2)',
        'Hornet Walker Wings Heavy (1 of 2)': 'Hornet Walker Wings Heavy (1 of 2)',
        'Hornet Walker Large Wings (1 of 2)': 'Hornet Walker Large Wings (1 of 2)',
        'Hornet Walker Wings Medium (1 of 2)': 'Hornet Walker Wings Medium (1 of 2)',
        'Hornet Walker Wings Raider (1 of 2)': 'Hornet Walker Wings Raider (1 of 2)',
        'Hornet Walker Wings Rugged (1 of 2)': 'Hornet Walker Wings Rugged (1 of 2)',
        'Hornet Walker Wings Skirmish (1 of 2)': 'Hornet Walker Wings Skirmish (1 of 2)',
        'Hornet Walker Wings Small (1 of 2)': 'Hornet Walker Wings Small (1 of 2)',
        'Hornet Walker Wings (1 of 2)': 'Hornet Walker Wings (1 of 2)',
        'Hornet Walker Upgrade - Cargo - Tier 2': 'Hornet Walker Upgrade - Cargo - Tier 2',
        'Hornet Walker Upgrade - Durability - Tier 2': 'Hornet Walker Upgrade - Durability - Tier 2',
        'Hornet Walker Upgrade - Gear - Tier 2': 'Hornet Walker Upgrade - Gear - Tier 2',
        'Hornet Walker Upgrade - Mobility - Tier 2': 'Hornet Walker Upgrade - Mobility - Tier 2',
        'Hornet Walker Upgrade - Torque - Tier 2': 'Hornet Walker Upgrade - Torque - Tier 2',
        'Hornet Walker Upgrade - Water - Tier 2': 'Hornet Walker Upgrade - Water - Tier 2',
        'Hornet Walker Upgrade - Cargo - Tier 3': 'Hornet Walker Upgrade - Cargo - Tier 3',
        'Hornet Walker Upgrade - Durability - Tier 3': 'Hornet Walker Upgrade - Durability - Tier 3',
        'Hornet Walker Upgrade - Gear - Tier 3': 'Hornet Walker Upgrade - Gear - Tier 3',
        'Hornet Walker Upgrade - Mobility - Tier 3': 'Hornet Walker Upgrade - Mobility - Tier 3',
        'Hornet Walker Upgrade - Torque - Tier 3': 'Hornet Walker Upgrade - Torque - Tier 3',
        'Hornet Walker Upgrade - Water - Tier 3': 'Hornet Walker Upgrade - Water - Tier 3',
        'Hornet Walker Upgrade - Cargo - Tier 4': 'Hornet Walker Upgrade - Cargo - Tier 4',
        'Hornet Walker Upgrade - Durability - Tier 4': 'Hornet Walker Upgrade - Durability - Tier 4',
        'Hornet Walker Upgrade - Gear - Tier 4': 'Hornet Walker Upgrade - Gear - Tier 4',
        'Hornet Walker Upgrade - Mobility - Tier 4': 'Hornet Walker Upgrade - Mobility - Tier 4',
        'Hornet Walker Upgrade - Torque - Tier 4': 'Hornet Walker Upgrade - Torque - Tier 4',
        'Hornet Walker Upgrade - Water - Tier 4': 'Hornet Walker Upgrade - Water - Tier 4',
        'Mollusk Walker Body': 'Mollusk Walker Body',
        'Mollusk Walker Legs (1 of 2)': 'Mollusk Walker Legs (1 of 2)',
        'Mollusk Walker Legs Armored (1 of 2)': 'Mollusk Walker Legs Armored (1 of 2)',
        'Mollusk Walker Wings (1 of 2)': 'Mollusk Walker Wings (1 of 2)',
        'Mollusk Walker Wings Heavy (1 of 2)': 'Mollusk Walker Wings Heavy (1 of 2)',
        'Mollusk Walker Wings Medium (1 of 2)': 'Mollusk Walker Wings Medium (1 of 2)',
        'Mollusk Walker Wings Raider (1 of 2)': 'Mollusk Walker Wings Raider (1 of 2)',
        'Mollusk Walker Wings Rugged (1 of 2)': 'Mollusk Walker Wings Rugged (1 of 2)',
        'Mollusk Walker Wings Skirmish (1 of 2)': 'Mollusk Walker Wings Skirmish (1 of 2)',
        'Mollusk Walker Wings Small (1 of 2)': 'Mollusk Walker Wings Small (1 of 2)',
        'Mollusk Walker Upgrade - Cargo - Tier 1': 'Mollusk Walker Upgrade - Cargo - Tier 1',
        'Mollusk Walker Upgrade - Durability - Tier 1': 'Mollusk Walker Upgrade - Durability - Tier 1',
        'Mollusk Walker Upgrade - Gear - Tier 1': 'Mollusk Walker Upgrade - Gear - Tier 1',
        'Mollusk Walker Upgrade - Mobility - Tier 1': 'Mollusk Walker Upgrade - Mobility - Tier 1',
        'Mollusk Walker Upgrade - Torque - Tier 1': 'Mollusk Walker Upgrade - Torque - Tier 1',
        'Mollusk Walker Upgrade - Water - Tier 1': 'Mollusk Walker Upgrade - Water - Tier 1',
        'Mollusk Walker Upgrade - Cargo - Tier 2': 'Mollusk Walker Upgrade - Cargo - Tier 2',
        'Mollusk Walker Upgrade - Durability - Tier 2': 'Mollusk Walker Upgrade - Durability - Tier 2',
        'Mollusk Walker Upgrade - Gear - Tier 2': 'Mollusk Walker Upgrade - Gear - Tier 2',
        'Mollusk Walker Upgrade - Mobility - Tier 2': 'Mollusk Walker Upgrade - Mobility - Tier 2',
        'Mollusk Walker Upgrade - Torque - Tier 2': 'Mollusk Walker Upgrade - Torque - Tier 2',
        'Mollusk Walker Upgrade - Water - Tier 2': 'Mollusk Walker Upgrade - Water - Tier 2',
        'Mollusk Walker Upgrade - Cargo - Tier 3': 'Mollusk Walker Upgrade - Cargo - Tier 3',
        'Mollusk Walker Upgrade - Durability - Tier 3': 'Mollusk Walker Upgrade - Durability - Tier 3',
        'Mollusk Walker Upgrade - Gear - Tier 3': 'Mollusk Walker Upgrade - Gear - Tier 3',
        'Mollusk Walker Upgrade - Mobility - Tier 3': 'Mollusk Walker Upgrade - Mobility - Tier 3',
        'Mollusk Walker Upgrade - Torque - Tier 3': 'Mollusk Walker Upgrade - Torque - Tier 3',
        'Mollusk Walker Upgrade - Water - Tier 3': 'Mollusk Walker Upgrade - Water - Tier 3',
        'Mollusk Walker Upgrade - Cargo - Tier 4': 'Mollusk Walker Upgrade - Cargo - Tier 4',
        'Mollusk Walker Upgrade - Durability - Tier 4': 'Mollusk Walker Upgrade - Durability - Tier 4',
        'Mollusk Walker Upgrade - Gear - Tier 4': 'Mollusk Walker Upgrade - Gear - Tier 4',
        'Mollusk Walker Upgrade - Mobility - Tier 4': 'Mollusk Walker Upgrade - Mobility - Tier 4',
        'Mollusk Walker Upgrade - Torque - Tier 4': 'Mollusk Walker Upgrade - Torque - Tier 4',
        'Mollusk Walker Upgrade - Water - Tier 4': 'Mollusk Walker Upgrade - Water - Tier 4',
        'Panda Walker Body': 'Panda Walker Body',
        'Panda Walker Legs Armored (1 of 2)': 'Panda Walker Legs Armored (1 of 2)',
        'Panda Walker Legs Heavy (1 of 2)': 'Panda Walker Legs Heavy (1 of 2)',
        'Panda Walker Legs (1 of 2)': 'Panda Walker Legs (1 of 2)',
        'Panda Walker Wings Heavy (1 of 2)': 'Panda Walker Wings Heavy (1 of 2)',
        'Panda Walker Large Wings (1 of 2)': 'Panda Walker Large Wings (1 of 2)',
        'Panda Walker Wings Medium (1 of 2)': 'Panda Walker Wings Medium (1 of 2)',
        'Panda Walker Wings Raider (1 of 2)': 'Panda Walker Wings Raider (1 of 2)',
        'Panda Walker Wings Rugged (1 of 2)': 'Panda Walker Wings Rugged (1 of 2)',
        'Panda Walker Wings Skirmish (1 of 2)': 'Panda Walker Wings Skirmish (1 of 2)',
        'Panda Walker Wings Small (1 of 2)': 'Panda Walker Wings Small (1 of 2)',
        'Panda Walker Wings (1 of 2)': 'Panda Walker Wings (1 of 2)',
        'Panda Walker Upgrade - Cargo - Tier 2': 'Panda Walker Upgrade - Cargo - Tier 2',
        'Panda Walker Upgrade - Durability - Tier 2': 'Panda Walker Upgrade - Durability - Tier 2',
        'Panda Walker Upgrade - Gear - Tier 2': 'Panda Walker Upgrade - Gear - Tier 2',
        'Panda Walker Upgrade - Mobility - Tier 2': 'Panda Walker Upgrade - Mobility - Tier 2',
        'Panda Walker Upgrade - Torque - Tier 2': 'Panda Walker Upgrade - Torque - Tier 2',
        'Panda Walker Upgrade - Water - Tier 2': 'Panda Walker Upgrade - Water - Tier 2',
        'Panda Walker Upgrade - Cargo - Tier 3': 'Panda Walker Upgrade - Cargo - Tier 3',
        'Panda Walker Upgrade - Durability - Tier 3': 'Panda Walker Upgrade - Durability - Tier 3',
        'Panda Walker Upgrade - Gear - Tier 3': 'Panda Walker Upgrade - Gear - Tier 3',
        'Panda Walker Upgrade - Mobility - Tier 3': 'Panda Walker Upgrade - Mobility - Tier 3',
        'Panda Walker Upgrade - Torque - Tier 3': 'Panda Walker Upgrade - Torque - Tier 3',
        'Panda Walker Upgrade - Water - Tier 3': 'Panda Walker Upgrade - Water - Tier 3',
        'Panda Walker Upgrade - Cargo - Tier 4': 'Panda Walker Upgrade - Cargo - Tier 4',
        'Panda Walker Upgrade - Durability - Tier 4': 'Panda Walker Upgrade - Durability - Tier 4',
        'Panda Walker Upgrade - Gear - Tier 4': 'Panda Walker Upgrade - Gear - Tier 4',
        'Panda Walker Upgrade - Mobility - Tier 4': 'Panda Walker Upgrade - Mobility - Tier 4',
        'Panda Walker Upgrade - Torque - Tier 4': 'Panda Walker Upgrade - Torque - Tier 4',
        'Panda Walker Upgrade - Water - Tier 4': 'Panda Walker Upgrade - Water - Tier 4',
        'Proxy Walker Body': 'Proxy Walker Body',
        'Proxy Walker Legs Armored (1 of 2)': 'Proxy Walker Legs Armored (1 of 2)',
        'Proxy Walker Legs Heavy (1 of 2)': 'Proxy Walker Legs Heavy (1 of 2)',
        'Proxy Walker Legs (1 of 2)': 'Proxy Walker Legs (1 of 2)',
        'Schmetterling Walker Body': 'Schmetterling Walker Body',
        'Schmetterling Walker Legs Armored (1 of 2)': 'Schmetterling Walker Legs Armored (1 of 2)',
        'Schmetterling Walker Legs Heavy (1 of 2)': 'Schmetterling Walker Legs Heavy (1 of 2)',
        'Schmetterling Walker Legs (1 of 2)': 'Schmetterling Walker Legs (1 of 2)',
        'Schmetterling Walker Wings Heavy (1 of 2)': 'Schmetterling Walker Wings Heavy (1 of 2)',
        'Schmetterling Walker Large Wings (1 of 2)': 'Schmetterling Walker Large Wings (1 of 2)',
        'Schmetterling Walker Wings Medium (1 of 2)': 'Schmetterling Walker Wings Medium (1 of 2)',
        'Schmetterling Walker Wings Raider (1 of 2)': 'Schmetterling Walker Wings Raider (1 of 2)',
        'Schmetterling Walker Wings Rugged (1 of 2)': 'Schmetterling Walker Wings Rugged (1 of 2)',
        'Schmetterling Walker Wings Skirmish (1 of 2)': 'Schmetterling Walker Wings Skirmish (1 of 2)',
        'Schmetterling Walker Wings Small (1 of 2)': 'Schmetterling Walker Wings Small (1 of 2)',
        'Schmetterling Walker Wings (1 of 2)': 'Schmetterling Walker Wings (1 of 2)',
        'Schmetterling Walker Upgrade - Cargo - Tier 1': 'Schmetterling Walker Upgrade - Cargo - Tier 1',
        'Schmetterling Walker Upgrade - Durability - Tier 1': 'Schmetterling Walker Upgrade - Durability - Tier 1',
        'Schmetterling Walker Upgrade - Gear - Tier 1': 'Schmetterling Walker Upgrade - Gear - Tier 1',
        'Schmetterling Walker Upgrade - Mobility - Tier 1': 'Schmetterling Walker Upgrade - Mobility - Tier 1',
        'Schmetterling Walker Upgrade - Torque - Tier 1': 'Schmetterling Walker Upgrade - Torque - Tier 1',
        'Schmetterling Walker Upgrade - Water - Tier 1': 'Schmetterling Walker Upgrade - Water - Tier 1',
        'Schmetterling Walker Upgrade - Cargo - Tier 2': 'Schmetterling Walker Upgrade - Cargo - Tier 2',
        'Schmetterling Walker Upgrade - Durability - Tier 2': 'Schmetterling Walker Upgrade - Durability - Tier 2',
        'Schmetterling Walker Upgrade - Gear - Tier 2': 'Schmetterling Walker Upgrade - Gear - Tier 2',
        'Schmetterling Walker Upgrade - Mobility - Tier 2': 'Schmetterling Walker Upgrade - Mobility - Tier 2',
        'Schmetterling Walker Upgrade - Torque - Tier 2': 'Schmetterling Walker Upgrade - Torque - Tier 2',
        'Schmetterling Walker Upgrade - Water - Tier 2': 'Schmetterling Walker Upgrade - Water - Tier 2',
        'Schmetterling Walker Upgrade - Cargo - Tier 3': 'Schmetterling Walker Upgrade - Cargo - Tier 3',
        'Schmetterling Walker Upgrade - Durability - Tier 3': 'Schmetterling Walker Upgrade - Durability - Tier 3',
        'Schmetterling Walker Upgrade - Gear - Tier 3': 'Schmetterling Walker Upgrade - Gear - Tier 3',
        'Schmetterling Walker Upgrade - Mobility - Tier 3': 'Schmetterling Walker Upgrade - Mobility - Tier 3',
        'Schmetterling Walker Upgrade - Torque - Tier 3': 'Schmetterling Walker Upgrade - Torque - Tier 3',
        'Schmetterling Walker Upgrade - Water - Tier 3': 'Schmetterling Walker Upgrade - Water - Tier 3',
        'Schmetterling Walker Upgrade - Cargo - Tier 4': 'Schmetterling Walker Upgrade - Cargo - Tier 4',
        'Schmetterling Walker Upgrade - Durability - Tier 4': 'Schmetterling Walker Upgrade - Durability - Tier 4',
        'Schmetterling Walker Upgrade - Gear - Tier 4': 'Schmetterling Walker Upgrade - Gear - Tier 4',
        'Schmetterling Walker Upgrade - Mobility - Tier 4': 'Schmetterling Walker Upgrade - Mobility - Tier 4',
        'Schmetterling Walker Upgrade - Torque - Tier 4': 'Schmetterling Walker Upgrade - Torque - Tier 4',
        'Schmetterling Walker Upgrade - Water - Tier 4': 'Schmetterling Walker Upgrade - Water - Tier 4',
        'Nomad Spider Walker Body': 'Nomad Spider Walker Body',
        'Spider Walker With Ballista': 'Spider Walker With Ballista',
        'Spider Walker Legs Armored (1 of 2)': 'Spider Walker Legs Armored (1 of 2)',
        'Spider Walker Legs (1 of 2)': 'Spider Walker Legs (1 of 2)',
        'Spider Walker Upgrade - Cargo - Tier 1': 'Spider Walker Upgrade - Cargo - Tier 1',
        'Spider Walker Upgrade - Durability - Tier 1': 'Spider Walker Upgrade - Durability - Tier 1',
        'Spider Walker Upgrade - Gear - Tier 1': 'Spider Walker Upgrade - Gear - Tier 1',
        'Spider Walker Upgrade - Mobility - Tier 1': 'Spider Walker Upgrade - Mobility - Tier 1',
        'Spider Walker Upgrade - Water - Tier 1': 'Spider Walker Upgrade - Water - Tier 1',
        'Spider Walker Upgrade - Cargo - Tier 2': 'Spider Walker Upgrade - Cargo - Tier 2',
        'Spider Walker Upgrade - Durability - Tier 2': 'Spider Walker Upgrade - Durability - Tier 2',
        'Spider Walker Upgrade - Gear - Tier 2': 'Spider Walker Upgrade - Gear - Tier 2',
        'Spider Walker Upgrade - Mobility - Tier 2': 'Spider Walker Upgrade - Mobility - Tier 2',
        'Spider Walker Upgrade - Torque - Tier 2': 'Spider Walker Upgrade - Torque - Tier 2',
        'Spider Walker Upgrade - Water - Tier 2': 'Spider Walker Upgrade - Water - Tier 2',
        'Spider Walker Upgrade - Cargo - Tier 3': 'Spider Walker Upgrade - Cargo - Tier 3',
        'Spider Walker Upgrade - Durability - Tier 3': 'Spider Walker Upgrade - Durability - Tier 3',
        'Spider Walker Upgrade - Gear - Tier 3': 'Spider Walker Upgrade - Gear - Tier 3',
        'Spider Walker Upgrade - Mobility - Tier 3': 'Spider Walker Upgrade - Mobility - Tier 3',
        'Spider Walker Upgrade - Torque - Tier 3': 'Spider Walker Upgrade - Torque - Tier 3',
        'Spider Walker Upgrade - Water - Tier 3': 'Spider Walker Upgrade - Water - Tier 3',
        'Spider Walker Upgrade - Cargo - Tier 4': 'Spider Walker Upgrade - Cargo - Tier 4',
        'Spider Walker Upgrade - Durability - Tier 4': 'Spider Walker Upgrade - Durability - Tier 4',
        'Spider Walker Upgrade - Gear - Tier 4': 'Spider Walker Upgrade - Gear - Tier 4',
        'Spider Walker Upgrade - Mobility - Tier 4': 'Spider Walker Upgrade - Mobility - Tier 4',
        'Spider Walker Upgrade - Torque - Tier 4': 'Spider Walker Upgrade - Torque - Tier 4',
        'Spider Walker Upgrade - Water - Tier 4': 'Spider Walker Upgrade - Water - Tier 4',
        'Stiletto Walker Body': 'Stiletto Walker Body',
        'Stiletto Walker Legs (1 of 2)': 'Stiletto Walker Legs (1 of 2)',
        'Stiletto Walker Legs Armored (1 of 2)': 'Stiletto Walker Legs Armored (1 of 2)',
        'Stiletto Walker Wings Heavy (1 of 2)': 'Stiletto Walker Wings Heavy (1 of 2)',
        'Stiletto Walker Wings Medium (1 of 2)': 'Stiletto Walker Wings Medium (1 of 2)',
        'Stiletto Walker Wings Raider (1 of 2)': 'Stiletto Walker Wings Raider (1 of 2)',
        'Stiletto Walker Wings Rugged (1 of 2)': 'Stiletto Walker Wings Rugged (1 of 2)',
        'Stiletto Walker Wings Skirmish (1 of 2)': 'Stiletto Walker Wings Skirmish (1 of 2)',
        'Stiletto Walker Wings Small (1 of 2)': 'Stiletto Walker Wings Small (1 of 2)',
        'Stiletto Walker Wings (1 of 2)': 'Stiletto Walker Wings (1 of 2)',
        'Stiletto Walker Upgrade - Cargo - Tier 2': 'Stiletto Walker Upgrade - Cargo - Tier 2',
        'Stiletto Walker Upgrade - Durability - Tier 2': 'Stiletto Walker Upgrade - Durability - Tier 2',
        'Stiletto Walker Upgrade - Gear - Tier 2': 'Stiletto Walker Upgrade - Gear - Tier 2',
        'Stiletto Walker Upgrade - Mobility - Tier 2': 'Stiletto Walker Upgrade - Mobility - Tier 2',
        'Stiletto Walker Upgrade - Torque - Tier 2': 'Stiletto Walker Upgrade - Torque - Tier 2',
        'Stiletto Walker Upgrade - Water - Tier 2': 'Stiletto Walker Upgrade - Water - Tier 2',
        'Stiletto Walker Upgrade - Cargo - Tier 3': 'Stiletto Walker Upgrade - Cargo - Tier 3',
        'Stiletto Walker Upgrade - Durability - Tier 3': 'Stiletto Walker Upgrade - Durability - Tier 3',
        'Stiletto Walker Upgrade - Gear - Tier 3': 'Stiletto Walker Upgrade - Gear - Tier 3',
        'Stiletto Walker Upgrade - Mobility - Tier 3': 'Stiletto Walker Upgrade - Mobility - Tier 3',
        'Stiletto Walker Upgrade - Torque - Tier 3': 'Stiletto Walker Upgrade - Torque - Tier 3',
        'Stiletto Walker Upgrade - Water - Tier 3': 'Stiletto Walker Upgrade - Water - Tier 3',
        'Stiletto Walker Upgrade - Cargo - Tier 4': 'Stiletto Walker Upgrade - Cargo - Tier 4',
        'Stiletto Walker Upgrade - Durability - Tier 4': 'Stiletto Walker Upgrade - Durability - Tier 4',
        'Stiletto Walker Upgrade - Gear - Tier 4': 'Stiletto Walker Upgrade - Gear - Tier 4',
        'Stiletto Walker Upgrade - Mobility - Tier 4': 'Stiletto Walker Upgrade - Mobility - Tier 4',
        'Stiletto Walker Upgrade - Torque - Tier 4': 'Stiletto Walker Upgrade - Torque - Tier 4',
        'Stiletto Walker Upgrade - Water - Tier 4': 'Stiletto Walker Upgrade - Water - Tier 4',
        'Titan Walker Body': 'Titan Walker Body',
        'Titan Walker Legs Armored (1 of 2)': 'Titan Walker Legs Armored (1 of 2)',
        'Titan Walker Legs Heavy (1 of 2)': 'Titan Walker Legs Heavy (1 of 2)',
        'Titan Walker Legs (1 of 2)': 'Titan Walker Legs (1 of 2)',
        'Titan Walker Wings Heavy (1 of 2)': 'Titan Walker Wings Heavy (1 of 2)',
        'Titan Walker Large Wings (1 of 2)': 'Titan Walker Large Wings (1 of 2)',
        'Titan Walker Wings Medium (1 of 2)': 'Titan Walker Wings Medium (1 of 2)',
        'Titan Walker Wings Raider (1 of 2)': 'Titan Walker Wings Raider (1 of 2)',
        'Titan Walker Wings Rugged (1 of 2)': 'Titan Walker Wings Rugged (1 of 2)',
        'Titan Walker Wings Skirmish (1 of 2)': 'Titan Walker Wings Skirmish (1 of 2)',
        'Titan Walker Wings Small (1 of 2)': 'Titan Walker Wings Small (1 of 2)',
        'Titan Walker Wings (1 of 2)': 'Titan Walker Wings (1 of 2)',
        'Titan Walker Upgrade - Cargo - Tier 2': 'Titan Walker Upgrade - Cargo - Tier 2',
        'Titan Walker Upgrade - Durability - Tier 2': 'Titan Walker Upgrade - Durability - Tier 2',
        'Titan Walker Upgrade - Gear - Tier 2': 'Titan Walker Upgrade - Gear - Tier 2',
        'Titan Walker Upgrade - Mobility - Tier 2': 'Titan Walker Upgrade - Mobility - Tier 2',
        'Titan Walker Upgrade - Torque - Tier 2': 'Titan Walker Upgrade - Torque - Tier 2',
        'Titan Walker Upgrade - Water - Tier 2': 'Titan Walker Upgrade - Water - Tier 2',
        'Titan Walker Upgrade - Cargo - Tier 3': 'Titan Walker Upgrade - Cargo - Tier 3',
        'Titan Walker Upgrade - Durability - Tier 3': 'Titan Walker Upgrade - Durability - Tier 3',
        'Titan Walker Upgrade - Gear - Tier 3': 'Titan Walker Upgrade - Gear - Tier 3',
        'Titan Walker Upgrade - Mobility - Tier 3': 'Titan Walker Upgrade - Mobility - Tier 3',
        'Titan Walker Upgrade - Torque - Tier 3': 'Titan Walker Upgrade - Torque - Tier 3',
        'Titan Walker Upgrade - Water - Tier 3': 'Titan Walker Upgrade - Water - Tier 3',
        'Titan Walker Upgrade - Cargo - Tier 4': 'Titan Walker Upgrade - Cargo - Tier 4',
        'Titan Walker Upgrade - Durability - Tier 4': 'Titan Walker Upgrade - Durability - Tier 4',
        'Titan Walker Upgrade - Gear - Tier 4': 'Titan Walker Upgrade - Gear - Tier 4',
        'Titan Walker Upgrade - Mobility - Tier 4': 'Titan Walker Upgrade - Mobility - Tier 4',
        'Titan Walker Upgrade - Torque - Tier 4': 'Titan Walker Upgrade - Torque - Tier 4',
        'Titan Walker Upgrade - Water - Tier 4': 'Titan Walker Upgrade - Water - Tier 4',
        'Toboggan Walker Body': 'Toboggan Walker Body',
        'Toboggan Walker Legs Armored (1 of 2)': 'Toboggan Walker Legs Armored (1 of 2)',
        'Toboggan Walker Legs Heavy (1 of 2)': 'Toboggan Walker Legs Heavy (1 of 2)',
        'Toboggan Walker Legs (1 of 2)': 'Toboggan Walker Legs (1 of 2)',
        'Toboggan Walker Wings Heavy (1 of 2)': 'Toboggan Walker Wings Heavy (1 of 2)',
        'Toboggan Walker Large Wings (1 of 2)': 'Toboggan Walker Large Wings (1 of 2)',
        'Toboggan Walker Wings Medium (1 of 2)': 'Toboggan Walker Wings Medium (1 of 2)',
        'Toboggan Walker Wings Raider (1 of 2)': 'Toboggan Walker Wings Raider (1 of 2)',
        'Toboggan Walker Wings Rugged (1 of 2)': 'Toboggan Walker Wings Rugged (1 of 2)',
        'Toboggan Walker Wings Skirmish (1 of 2)': 'Toboggan Walker Wings Skirmish (1 of 2)',
        'Toboggan Walker Wings Small (1 of 2)': 'Toboggan Walker Wings Small (1 of 2)',
        'Toboggan Walker Wings (1 of 2)': 'Toboggan Walker Wings (1 of 2)',
        'Toboggan Walker Upgrade - Cargo - Tier 2': 'Toboggan Walker Upgrade - Cargo - Tier 2',
        'Toboggan Walker Upgrade - Durability - Tier 2': 'Toboggan Walker Upgrade - Durability - Tier 2',
        'Toboggan Walker Upgrade - Gear - Tier 2': 'Toboggan Walker Upgrade - Gear - Tier 2',
        'Toboggan Walker Upgrade - Mobility - Tier 2': 'Toboggan Walker Upgrade - Mobility - Tier 2',
        'Toboggan Walker Upgrade - Torque - Tier 2': 'Toboggan Walker Upgrade - Torque - Tier 2',
        'Toboggan Walker Upgrade - Water - Tier 2': 'Toboggan Walker Upgrade - Water - Tier 2',
        'Toboggan Walker Upgrade - Cargo - Tier 3': 'Toboggan Walker Upgrade - Cargo - Tier 3',
        'Toboggan Walker Upgrade - Durability - Tier 3': 'Toboggan Walker Upgrade - Durability - Tier 3',
        'Toboggan Walker Upgrade - Gear - Tier 3': 'Toboggan Walker Upgrade - Gear - Tier 3',
        'Toboggan Walker Upgrade - Mobility - Tier 3': 'Toboggan Walker Upgrade - Mobility - Tier 3',
        'Toboggan Walker Upgrade - Torque - Tier 3': 'Toboggan Walker Upgrade - Torque - Tier 3',
        'Toboggan Walker Upgrade - Water - Tier 3': 'Toboggan Walker Upgrade - Water - Tier 3',
        'Toboggan Walker Upgrade - Cargo - Tier 4': 'Toboggan Walker Upgrade - Cargo - Tier 4',
        'Toboggan Walker Upgrade - Durability - Tier 4': 'Toboggan Walker Upgrade - Durability - Tier 4',
        'Toboggan Walker Upgrade - Gear - Tier 4': 'Toboggan Walker Upgrade - Gear - Tier 4',
        'Toboggan Walker Upgrade - Mobility - Tier 4': 'Toboggan Walker Upgrade - Mobility - Tier 4',
        'Toboggan Walker Upgrade - Torque - Tier 4': 'Toboggan Walker Upgrade - Torque - Tier 4',
        'Toboggan Walker Upgrade - Water - Tier 4': 'Toboggan Walker Upgrade - Water - Tier 4',
        'Long Sawblade': 'Long Sawblade',
        'Sawblade Tool': 'Sawblade Tool',
        'Steering Levers': 'Steering Levers',
        'Tool Pod': 'Tool Pod',
        'Walker Climber': 'Walker Climber',
        'Walker Packing Compartment': 'Walker Packing Compartment',
        'Tusker Walker Body': 'Tusker Walker Body',
        'Tusker Walker Legs Armored (1 of 2)': 'Tusker Walker Legs Armored (1 of 2)',
        'Tusker Walker Legs Heavy (1 of 2)': 'Tusker Walker Legs Heavy (1 of 2)',
        'Tusker Walker Legs (1 of 2)': 'Tusker Walker Legs (1 of 2)',
        'Tusker Walker Wings Heavy (1 of 2)': 'Tusker Walker Wings Heavy (1 of 2)',
        'Tusker Walker Large Wings (1 of 2)': 'Tusker Walker Large Wings (1 of 2)',
        'Tusker Walker Wings Medium (1 of 2)': 'Tusker Walker Wings Medium (1 of 2)',
        'Tusker Walker Wings Raider (1 of 2)': 'Tusker Walker Wings Raider (1 of 2)',
        'Tusker Walker Wings Rugged (1 of 2)': 'Tusker Walker Wings Rugged (1 of 2)',
        'Tusker Walker Wings Skirmish (1 of 2)': 'Tusker Walker Wings Skirmish (1 of 2)',
        'Tusker Walker Wings Small (1 of 2)': 'Tusker Walker Wings Small (1 of 2)',
        'Tusker Walker Wings (1 of 2)': 'Tusker Walker Wings (1 of 2)',
        'Tusker Walker Upgrade - Cargo - Tier 2': 'Tusker Walker Upgrade - Cargo - Tier 2',
        'Tusker Walker Upgrade - Durability - Tier 2': 'Tusker Walker Upgrade - Durability - Tier 2',
        'Tusker Walker Upgrade - Gear - Tier 2': 'Tusker Walker Upgrade - Gear - Tier 2',
        'Tusker Walker Upgrade - Mobility - Tier 2': 'Tusker Walker Upgrade - Mobility - Tier 2',
        'Tusker Walker Upgrade - Torque - Tier 2': 'Tusker Walker Upgrade - Torque - Tier 2',
        'Tusker Walker Upgrade - Water - Tier 2': 'Tusker Walker Upgrade - Water - Tier 2',
        'Tusker Walker Upgrade - Cargo - Tier 3': 'Tusker Walker Upgrade - Cargo - Tier 3',
        'Tusker Walker Upgrade - Durability - Tier 3': 'Tusker Walker Upgrade - Durability - Tier 3',
        'Tusker Walker Upgrade - Gear - Tier 3': 'Tusker Walker Upgrade - Gear - Tier 3',
        'Tusker Walker Upgrade - Mobility - Tier 3': 'Tusker Walker Upgrade - Mobility - Tier 3',
        'Tusker Walker Upgrade - Torque - Tier 3': 'Tusker Walker Upgrade - Torque - Tier 3',
        'Tusker Walker Upgrade - Water - Tier 3': 'Tusker Walker Upgrade - Water - Tier 3',
        'Tusker Walker Upgrade - Cargo - Tier 4': 'Tusker Walker Upgrade - Cargo - Tier 4',
        'Tusker Walker Upgrade - Durability - Tier 4': 'Tusker Walker Upgrade - Durability - Tier 4',
        'Tusker Walker Upgrade - Gear - Tier 4': 'Tusker Walker Upgrade - Gear - Tier 4',
        'Tusker Walker Upgrade - Mobility - Tier 4': 'Tusker Walker Upgrade - Mobility - Tier 4',
        'Tusker Walker Upgrade - Torque - Tier 4': 'Tusker Walker Upgrade - Torque - Tier 4',
        'Tusker Walker Upgrade - Water - Tier 4': 'Tusker Walker Upgrade - Water - Tier 4',
        'Silur Walker Body': 'Silur Walker Body',
        'Silur Walker Legs (1 of 2)': 'Silur Walker Legs (1 of 2)',
        'Silur Walker Upgrade - Water - Tier 2': 'Silur Walker Upgrade - Water - Tier 2',
        'Silur Walker Upgrade - Torque - Tier 2': 'Silur Walker Upgrade - Torque - Tier 2',
        'Silur Walker Upgrade - Torque - Tier 3': 'Silur Walker Upgrade - Torque - Tier 3',
        'Silur Walker Upgrade - Water - Tier 3': 'Silur Walker Upgrade - Water - Tier 3',
        'Silur Walker Upgrade - Torque - Tier 4': 'Silur Walker Upgrade - Torque - Tier 4',
        'Silur Walker Upgrade - Water - Tier 4': 'Silur Walker Upgrade - Water - Tier 4',
        'Silur Walker Legs Armored (1 of 2)': 'Silur Walker Legs Armored (1 of 2)',
        'Silur Walker Legs Heavy (1 of 2)': 'Silur Walker Legs Heavy (1 of 2)',
        'Battle Fan': 'Battle Fan',
        'Hardened Hellfire Bolt': 'Hardened Hellfire Bolt',
        'Base Maintenance Chest': 'Base Maintenance Chest',
        'Hercul Walker Body': 'Hercul Walker Body',
        'Hercul Walker Legs (1 of 2)': 'Hercul Walker Legs (1 of 2)',
        'Hercul Walker Wings (1 of 2)': 'Hercul Walker Wings (1 of 2)',
        'Hercul Walker Legs Armored (1 of 2)': 'Hercul Walker Legs Armored (1 of 2)',
        'Hercul Walker Wings Heavy (1 of 2)': 'Hercul Walker Wings Heavy (1 of 2)',
        'Hercul Walker Wings Medium (1 of 2)': 'Hercul Walker Wings Medium (1 of 2)',
        'Hercul Walker Wings Raider (1 of 2)': 'Hercul Walker Wings Raider (1 of 2)',
        'Hercul Walker Wings Rugged (1 of 2)': 'Hercul Walker Wings Rugged (1 of 2)',
        'Hercul Walker Wings Skirmish (1 of 2)': 'Hercul Walker Wings Skirmish (1 of 2)',
        'Hercul Walker Wings Small (1 of 2)': 'Hercul Walker Wings Small (1 of 2)',
        'Hercul Walker Upgrade - Torque - Tier 2': 'Hercul Walker Upgrade - Torque - Tier 2',
        'Hercul Walker Upgrade - Water - Tier 2': 'Hercul Walker Upgrade - Water - Tier 2',
        'Hercul Walker Upgrade - Torque - Tier 3': 'Hercul Walker Upgrade - Torque - Tier 3',
        'Hercul Walker Upgrade - Water - Tier 3': 'Hercul Walker Upgrade - Water - Tier 3',
        'Hercul Walker Upgrade - Torque - Tier 4': 'Hercul Walker Upgrade - Torque - Tier 4',
        'Hercul Walker Upgrade - Water - Tier 4': 'Hercul Walker Upgrade - Water - Tier 4',
        'Balang Walker Body': 'Balang Walker Body',
        'Balang Walker Legs (1 of 2)': 'Balang Walker Legs (1 of 2)',
        'Balang Walker Wings': 'Balang Walker Wings',
        'Balang Walker Wings Small': 'Balang Walker Wings Small',
        'Balang Walker Upgrade - Torque - Tier 2': 'Balang Walker Upgrade - Torque - Tier 2',
        'Balang Walker Upgrade - Water - Tier 2': 'Balang Walker Upgrade - Water - Tier 2',
        'Balang Walker Upgrade - Torque - Tier 3': 'Balang Walker Upgrade - Torque - Tier 3',
        'Balang Walker Upgrade - Water - Tier 3': 'Balang Walker Upgrade - Water - Tier 3',
        'Balang Walker Upgrade - Torque - Tier 4': 'Balang Walker Upgrade - Torque - Tier 4',
        'Balang Walker Upgrade - Water - Tier 4': 'Balang Walker Upgrade - Water - Tier 4',
        'Large Base Walker Packer': 'Large Base Walker Packer',
        'Small Base Walker Packer': 'Small Base Walker Packer',
        'Poaching Hut': 'Poaching Hut',
        'Giant Wall': 'Giant Wall',
        'Giant Wall Gate': 'Giant Wall Gate',
        'Steering Levers Cage': 'Steering Levers Cage',
        'Compacted Torque Battery': 'Compacted Torque Battery',
        'Net Pouch': 'Net Pouch',
        'Bent Wooden Planks': 'Bent Wooden Planks',
        'Fiery Concoction': 'Fiery Concoction',
        Lightwood: 'Lightwood',
        'Wood Log': 'Wood Log',
        'Worm Fang': 'Worm Fang',
        'Worm Sand': 'Worm Sand',
        'Armory Module': 'Armory Module',
        'Battery Module': 'Battery Module',
        'Bullrush Module': 'Bullrush Module',
        'Craftsman Module': 'Craftsman Module',
        'Foraging Module': 'Foraging Module',
        'Fireproof Module': 'Fireproof Module',
        'Fortress Module': 'Fortress Module',
        'Harpoon Protection Module': 'Harpoon Protection Module',
        'Hearth Module': 'Hearth Module',
        'Hull Hardening Module': 'Hull Hardening Module',
        'Lifeforce Module': 'Lifeforce Module',
        'Lumberjack Module': 'Lumberjack Module',
        'Merchant Module': 'Merchant Module',
        'Pack Mule Module': 'Pack Mule Module',
        'Sandy Module': 'Sandy Module',
        'Scavenger Module': 'Scavenger Module',
        'Torque Module': 'Torque Module',
        'Watery Module': 'Watery Module',
        'Weightless Module': 'Weightless Module',
        'Giant Wall Packer': 'Giant Wall Packer',
        'Buffalo Walker Upgrade - Cargo - Tier 1': 'Buffalo Walker Upgrade - Cargo - Tier 1',
        'Buffalo Walker Upgrade - Durability - Tier 1': 'Buffalo Walker Upgrade - Durability - Tier 1',
        'Buffalo Walker Upgrade - Gear - Tier 1': 'Buffalo Walker Upgrade - Gear - Tier 1',
        'Buffalo Walker Upgrade - Mobility - Tier 1': 'Buffalo Walker Upgrade - Mobility - Tier 1',
        'Buffalo Walker Upgrade - Torque - Tier 1': 'Buffalo Walker Upgrade - Torque - Tier 1',
        'Buffalo Walker Upgrade - Water - Tier 1': 'Buffalo Walker Upgrade - Water - Tier 1',
        'Cobra Walker Upgrade - Water - Tier 1': 'Cobra Walker Upgrade - Water - Tier 1',
        'Dinghy Walker Upgrade - Cargo - Tier 1': 'Dinghy Walker Upgrade - Cargo - Tier 1',
        'Dinghy Walker Upgrade - Durability - Tier 1': 'Dinghy Walker Upgrade - Durability - Tier 1',
        'Dinghy Walker Upgrade - Gear - Tier 1': 'Dinghy Walker Upgrade - Gear - Tier 1',
        'Dinghy Walker Upgrade - Mobility - Tier 1': 'Dinghy Walker Upgrade - Mobility - Tier 1',
        'Dinghy Walker Upgrade - Torque - Tier 1': 'Dinghy Walker Upgrade - Torque - Tier 1',
        'Dinghy Walker Upgrade - Water - Tier 1': 'Dinghy Walker Upgrade - Water - Tier 1',
        'Hornet Walker Legs Armored (1 of 2)': 'Hornet Walker Legs Armored (1 of 2)',
        'Hornet Walker Upgrade - Cargo - Tier 1': 'Hornet Walker Upgrade - Cargo - Tier 1',
        'Hornet Walker Upgrade - Durability - Tier 1': 'Hornet Walker Upgrade - Durability - Tier 1',
        'Hornet Walker Upgrade - Gear - Tier 1': 'Hornet Walker Upgrade - Gear - Tier 1',
        'Hornet Walker Upgrade - Mobility - Tier 1': 'Hornet Walker Upgrade - Mobility - Tier 1',
        'Hornet Walker Upgrade - Torque - Tier 1': 'Hornet Walker Upgrade - Torque - Tier 1',
        'Hornet Walker Upgrade - Water - Tier 1': 'Hornet Walker Upgrade - Water - Tier 1',
        'Titan Walker Upgrade - Cargo - Tier 1': 'Titan Walker Upgrade - Cargo - Tier 1',
        'Titan Walker Upgrade - Durability - Tier 1': 'Titan Walker Upgrade - Durability - Tier 1',
        'Titan Walker Upgrade - Gear - Tier 1': 'Titan Walker Upgrade - Gear - Tier 1',
        'Titan Walker Upgrade - Mobility - Tier 1': 'Titan Walker Upgrade - Mobility - Tier 1',
        'Titan Walker Upgrade - Torque - Tier 1': 'Titan Walker Upgrade - Torque - Tier 1',
        'Titan Walker Upgrade - Water - Tier 1': 'Titan Walker Upgrade - Water - Tier 1',
        'Toboggan Walker Upgrade - Cargo - Tier 1': 'Toboggan Walker Upgrade - Cargo - Tier 1',
        'Toboggan Walker Upgrade - Durability - Tier 1': 'Toboggan Walker Upgrade - Durability - Tier 1',
        'Toboggan Walker Upgrade - Gear - Tier 1': 'Toboggan Walker Upgrade - Gear - Tier 1',
        'Toboggan Walker Upgrade - Mobility - Tier 1': 'Toboggan Walker Upgrade - Mobility - Tier 1',
        'Toboggan Walker Upgrade - Torque - Tier 1': 'Toboggan Walker Upgrade - Torque - Tier 1',
        'Toboggan Walker Upgrade - Water - Tier 1': 'Toboggan Walker Upgrade - Water - Tier 1',
        'Tusker Walker Upgrade - Cargo - Tier 1': 'Tusker Walker Upgrade - Cargo - Tier 1',
        'Tusker Walker Upgrade - Durability - Tier 1': 'Tusker Walker Upgrade - Durability - Tier 1',
        'Tusker Walker Upgrade - Gear - Tier 1': 'Tusker Walker Upgrade - Gear - Tier 1',
        'Tusker Walker Upgrade - Mobility - Tier 1': 'Tusker Walker Upgrade - Mobility - Tier 1',
        'Tusker Walker Upgrade - Torque - Tier 1': 'Tusker Walker Upgrade - Torque - Tier 1',
        'Tusker Walker Upgrade - Water - Tier 1': 'Tusker Walker Upgrade - Water - Tier 1',
        'Balang Walker Wings (1 of 2)': 'Balang Walker Wings (1 of 2)',
        'Balang Walker Wings Small (1 of 2)': 'Balang Walker Wings Small (1 of 2)',
        'Raptor Sky Walker Body': 'Raptor Sky Walker Body',
        'Raptor Sky Walker Legs (1 of 2)': 'Raptor Sky Walker Legs (1 of 2)',
        'Raptor Sky Walker Wings (1 of 2)': 'Raptor Sky Walker Wings (1 of 2)',
        'Raptor Walker Upgrade - Cargo - Tier 1': 'Raptor Walker Upgrade - Cargo - Tier 1',
        'Raptor Walker Upgrade - Durability - Tier 1': 'Raptor Walker Upgrade - Durability - Tier 1',
        'Raptor Walker Upgrade - Gear - Tier 1': 'Raptor Walker Upgrade - Gear - Tier 1',
        'Raptor Walker Upgrade - Torque - Tier 1': 'Raptor Walker Upgrade - Torque - Tier 1',
        'Raptor Walker Upgrade - Water - Tier 1': 'Raptor Walker Upgrade - Water - Tier 1',
        'Raptor Walker Upgrade - Cargo - Tier 2': 'Raptor Walker Upgrade - Cargo - Tier 2',
        'Raptor Walker Upgrade - Durability - Tier 2': 'Raptor Walker Upgrade - Durability - Tier 2',
        'Raptor Walker Upgrade - Gear - Tier 2': 'Raptor Walker Upgrade - Gear - Tier 2',
        'Raptor Walker Upgrade - Torque - Tier 2': 'Raptor Walker Upgrade - Torque - Tier 2',
        'Raptor Walker Upgrade - Water - Tier 2': 'Raptor Walker Upgrade - Water - Tier 2',
        'Raptor Walker Upgrade - Cargo - Tier 3': 'Raptor Walker Upgrade - Cargo - Tier 3',
        'Raptor Walker Upgrade - Durability - Tier 3': 'Raptor Walker Upgrade - Durability - Tier 3',
        'Raptor Walker Upgrade - Gear - Tier 3': 'Raptor Walker Upgrade - Gear - Tier 3',
        'Raptor Walker Upgrade - Torque - Tier 3': 'Raptor Walker Upgrade - Torque - Tier 3',
        'Raptor Walker Upgrade - Water - Tier 3': 'Raptor Walker Upgrade - Water - Tier 3',
        'Raptor Walker Upgrade - Cargo - Tier 4': 'Raptor Walker Upgrade - Cargo - Tier 4',
        'Raptor Walker Upgrade - Durability - Tier 4': 'Raptor Walker Upgrade - Durability - Tier 4',
        'Raptor Walker Upgrade - Gear - Tier 4': 'Raptor Walker Upgrade - Gear - Tier 4',
        'Raptor Walker Upgrade - Torque - Tier 4': 'Raptor Walker Upgrade - Torque - Tier 4',
        'Raptor Walker Upgrade - Water - Tier 4': 'Raptor Walker Upgrade - Water - Tier 4'
    }
};
export default all;