export const config = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  RESOURCES_URL: process.env.NEXT_PUBLIC_RESOURCES_URL,
  DISCORD_CLIENT_ID: process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID,
  PLAUSIBLE_URL: process.env.NEXT_PUBLIC_PLAUSIBLE_URL,
};

export const DEFAULT_LANGUAGE = "en";
