"use client";

const {
  NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_RESOURCES_URL,
  NEXT_PUBLIC_DISCORD_CLIENT_ID,
  NEXT_PUBLIC_PLAUSIBLE_URL,
} = process.env;

export const config = {
  API_URL: NEXT_PUBLIC_API_URL,
  RESOURCES_URL: NEXT_PUBLIC_RESOURCES_URL,
  DISCORD_CLIENT_ID: NEXT_PUBLIC_DISCORD_CLIENT_ID,
  PLAUSIBLE_URL: NEXT_PUBLIC_PLAUSIBLE_URL,
};

export const DEFAULT_LANGUAGE = "en";
