name: Update Items daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-items:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Download and update items
      run: |
        # Download the remote file
        curl -s https://raw.githubusercontent.com/Stiletto-lo/loDataExtractor/main/exported/items_min.json > remote_items.json
        
        # Compare files and update if different
        if ! diff -q remote_items.json public/json/items_min.json > /dev/null 2>&1; then
          echo "Files are different, updating items_min.json"
          cp remote_items.json public/json/items_min.json
          echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
        else
          echo "Files are identical, no update needed"
          echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
        fi
        
        # Clean up temporary file
        rm -f remote_items.json

    - name: Create Pull Request
      if: env.UPDATE_NEEDED == 'true'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "chore: Update items from loDataExtractor"
        body: |
          This PR updates `items_min.json` with the latest version from the loDataExtractor repository.
          
          **Changes:**
          - Updated `public/json/items_min.json` with latest data
          
          This is an automated update that runs daily.
        branch: update/items-${{ github.run_id }}
        commit-message: "chore: Update items from loDataExtractor"
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        labels: |
          automated
          update
          data
        delete-branch: true
        base: master